SET NAMES utf8mb4;

DELETE ge FROM grammar_examples ge JOIN grammar_lessons gl ON gl.id = ge.grammar_lesson_id WHERE gl.jlpt_level_id = 1;

DELETE FROM grammar_lessons WHERE jlpt_level_id = 1;

DELETE FROM grammar_chapters WHERE jlpt_level_id = 1;

INSERT INTO grammar_chapters (id, jlpt_level_id, chapter_number, name, description, display_order, is_published, version) VALUES
(1, 1, 1, 'Bài 1', 'Ngữ pháp N5 - Bài 1', 1, TRUE, 1),
(2, 1, 2, 'Bài 2', 'Ngữ pháp N5 - Bài 2', 2, TRUE, 1),
(3, 1, 3, 'Bài 3', 'Ngữ pháp N5 - Bài 3', 3, TRUE, 1),
(4, 1, 4, 'Bài 4', 'Ngữ pháp N5 - Bài 4', 4, TRUE, 1),
(5, 1, 5, 'Bài 5', 'Ngữ pháp N5 - Bài 5', 5, TRUE, 1),
(6, 1, 6, 'Bài 6', 'Ngữ pháp N5 - Bài 6', 6, TRUE, 1),
(7, 1, 7, 'Bài 7', 'Ngữ pháp N5 - Bài 7', 7, TRUE, 1),
(8, 1, 8, 'Bài 8', 'Ngữ pháp N5 - Bài 8', 8, TRUE, 1),
(9, 1, 9, 'Bài 9', 'Ngữ pháp N5 - Bài 9', 9, TRUE, 1),
(10, 1, 10, 'Bài 10', 'Ngữ pháp N5 - Bài 10', 10, TRUE, 1),
(11, 1, 11, 'Bài 11', 'Ngữ pháp N5 - Bài 11', 11, TRUE, 1),
(12, 1, 12, 'Bài 12', 'Ngữ pháp N5 - Bài 12', 12, TRUE, 1),
(13, 1, 13, 'Bài 13', 'Ngữ pháp N5 - Bài 13', 13, TRUE, 1),
(14, 1, 14, 'Bài 14', 'Ngữ pháp N5 - Bài 14', 14, TRUE, 1),
(15, 1, 15, 'Bài 15', 'Ngữ pháp N5 - Bài 15', 15, TRUE, 1),
(16, 1, 16, 'Bài 16', 'Ngữ pháp N5 - Bài 16', 16, TRUE, 1),
(17, 1, 17, 'Bài 17', 'Ngữ pháp N5 - Bài 17', 17, TRUE, 1),
(18, 1, 18, 'Bài 18', 'Ngữ pháp N5 - Bài 18', 18, TRUE, 1),
(19, 1, 19, 'Bài 19', 'Ngữ pháp N5 - Bài 19', 19, TRUE, 1),
(20, 1, 20, 'Bài 20', 'Ngữ pháp N5 - Bài 20', 20, TRUE, 1),
(21, 1, 21, 'Bài 21', 'Ngữ pháp N5 - Bài 21', 21, TRUE, 1),
(22, 1, 22, 'Bài 22', 'Ngữ pháp N5 - Bài 22', 22, TRUE, 1),
(23, 1, 23, 'Bài 23', 'Ngữ pháp N5 - Bài 23', 23, TRUE, 1),
(24, 1, 24, 'Bài 24', 'Ngữ pháp N5 - Bài 24', 24, TRUE, 1),
(25, 1, 25, 'Bài 25', 'Ngữ pháp N5 - Bài 25', 25, TRUE, 1)
ON DUPLICATE KEY UPDATE
    jlpt_level_id = VALUES(jlpt_level_id),
    chapter_number = VALUES(chapter_number),
    name = VALUES(name),
    description = VALUES(description),
    display_order = VALUES(display_order),
    is_published = VALUES(is_published),
    version = VALUES(version);

INSERT INTO grammar_lessons (id, grammar_chapter_id, title, pattern, meaning_vi, explanation, formation, jlpt_level_id, display_order, is_published, version) VALUES
(1, 1, 'Câu khẳng định:', 'S: Chủ ngữ (わたし、ヤマダさん、ちち、はは、あのひ / と、。。。)', 'Câu khẳng định:', 'Tôi là Samurai. Tôi là giáo viên. Tôi là người Việt Nam. Tôi 18 tuổi. 1. CÂU KHẲNG ĐỊNH 2. CÂU PHỦ ĐỊNH 3. CÂU NGHI VẤN • Hỏi tuổi:', 'S: Chủ ngữ (わたし、ヤマダさん、ちち、はは、あのひ / と、。。。) / N: Tên, nghề nghiệp, quốc tịch (～じん), tuổi (～さい)。。。', 1, 1, TRUE, 1),
(2, 1, 'Câu phủ định:', 'Câu phủ định:', 'Câu phủ định:', 'Tôi không phải là bác sĩ.', 'わたし は いしゃ じゃありません。', 1, 2, TRUE, 1),
(3, 1, 'Câu nghi vấn:', 'Câu nghi vấn:', 'Câu nghi vấn:', 'N N • Từ để hỏi:', 'Q：ミンさんは がくせいですか。 / A： / はい、がくせい です。', 1, 3, TRUE, 1),
(4, 1, 'Trợ từ の：', 'Trợ từ の：', 'Trợ từ の：', 'Ý nghĩa: N2 của N1', '4. Trợ từ の： / サムライにほんご の がくせい。 / わたしは ハノイだいがくの がくせいです。', 1, 4, TRUE, 1),
(5, 1, 'Trợ từ も:', 'S は từ để hỏi / N1 の N2', 'Trợ từ も:', 'Ý nghĩa: A là N. B cũng là N.', '5. Trợ từ も: / S は từ để hỏi / ですか。', 1, 5, TRUE, 1),
(6, 2, 'Cái này/ đó/ kia:', '➢ これ：Dùng để chỉ vật ở gần người nói, xa người nghe. / ➢ それ：Dùng để chỉ vật ở gần người nghe, xa người nói.', 'Cái này/ đó/ kia:', 'Cách dùng:', '➢ これ：Dùng để chỉ vật ở gần người nói, xa người nghe. / ➢ それ：Dùng để chỉ vật ở gần người nghe, xa người nói. / ➢ あれ：Dùng để chỉ vật ở xa 2 người.', 1, 1, TRUE, 1),
(7, 2, '～ Này/ Đó/ Kia:', '➢ Nhấn mạnh vào đối tượng trước mắt. / ➢ Về tương quan khoảng cách, giống với これ／それ／あれ.', '～ Này/ Đó/ Kia:', 'Cách dùng: ➢ Nhấn mạnh vào đối tượng trước mắt. Lưu ý:', '2. ～ Này/ Đó/ Kia: / ➢ Nhấn mạnh vào đối tượng trước mắt. / ➢ Về tương quan khoảng cách, giống với これ／それ／あれ.', 1, 2, TRUE, 1),
(8, 2, 'そうです: Đúng vậy, đúng rồi', 'そうです: Đúng vậy, đúng rồi / ちがいます: Không phải, sai rồi', 'そうです: Đúng vậy, đúng rồi', 'A： VD:', 'そうです: Đúng vậy, đúng rồi / ちがいます: Không phải, sai rồi / Q：これ／それ／あれ', 1, 3, TRUE, 1),
(9, 2, 'Là N1 hay là N2:', 'N1 / の N2', 'Là N1 hay là N2:', 'Cách dùng: ➢ Là câu hỏi lựa chọn. ➢ Dùng khi phân vân, không biết rõ đối tượng là ai (cái gì). N1 (người) (đồ vật) Lưu ý:', '4. Là N1 hay là N2: / N1 / の N2', 1, 4, TRUE, 1),
(10, 2, 'N2 của N1:', 'N2 đôi khi được lược bỏ khi đã được nhắc đến trước đó hay đã', 'N2 của N1:', 'Cách dùng: Dùng để miêu tả 1 món đồ thuộc quyền sở hữu của ai đó. Lưu ý: N2 đôi khi được lược bỏ khi đã được nhắc đến trước đó hay đã rõ nghĩa.', '5. N2 của N1: / N2 đôi khi được lược bỏ khi đã được nhắc đến trước đó hay đã / これは わたしの チョコレートです。', 1, 5, TRUE, 1),
(11, 2, 'Cái này/ Đó/ Kia là ∼ về ∼', '➢ Trợ từ の: thuộc về.', 'Cái này/ Đó/ Kia là ∼ về ∼', 'Cách dùng: ➢ Dùng khi muốn nói về thuộc tính của đồ vật: lĩnh vực, chuyên ngành,…', '➢ Trợ từ の: thuộc về. / これは えいごの じしょです。 / Q:このN／その N／あの N はだれの ですか。', 1, 6, TRUE, 1),
(12, 3, 'Chỗ này/ đó/ kia là N:', 'Chỗ này/ đó/ kia là N: / ここ', 'Chỗ này/ đó/ kia là N:', 'Chú ý:', 'Chỗ này/ đó/ kia là N: / ここ / そこ は N です。', 1, 1, TRUE, 1),
(13, 3, 'S là ở N:', 'S: người, vật, địa điểm. / N: địa điểm.', 'S là ở N:', 'Cách dùng: S: người, vật, địa điểm. N: địa điểm. Nhấn mạnh chủ ngữ đang ở địa điểm N.', '2. S là ở N: / S は N です。 / S: người, vật, địa điểm.', 1, 2, TRUE, 1),
(14, 3, 'N là ở đâu?', 'N là ở đâu?', 'N là ở đâu?', 'Cô Linh ở đâu? Cô Linh ở trong phòng học. • Cách nói trang trọng hơn:', '3. N là ở đâu? / Q： N は どこですか。 / A： Địa điểm です。', 1, 3, TRUE, 1),
(15, 3, 'Hỏi tên nước, công ty, trường học：', 'かいしゃ', 'Hỏi tên nước, công ty, trường học：', 'Bạn đến từ quốc gia nào? Tôi đến từ Việt Nam.', 'A： おくに / だいがく は どちらですか。 / かいしゃ', 1, 4, TRUE, 1),
(16, 3, 'Trợ từ の (xuất xứ):', 'これ / あれ', 'Trợ từ の (xuất xứ):', 'Đây là giày Nhật.', '5. Trợ từ の (xuất xứ): / これ / それ は nơi sản xuất の N です。', 1, 5, TRUE, 1),
(17, 3, 'Giá tiền của đồ vật:', 'この / あの', 'Giá tiền của đồ vật:', 'Chiếc đồng hồ này có giá 600 Yên.', 'この / その N は ～えん・ドル・ドンです。 / あの', 1, 6, TRUE, 1),
(18, 4, 'Bây giờ là ～ giờ ～ phút:', 'いま、～時 / じ', 'Bây giờ là ～ giờ ～ phút:', 'Cách dùng: ：chỉ số giờ • Số đếm + ：chỉ số phút ：chỉ giờ rưỡi Lưu ý: Để phân biệt thời gian buổi sáng, chiều, hay tối, người ta thêm', 'いま、～時 / じ / ～分', 1, 1, TRUE, 1),
(19, 4, 'Là thứ mấy?:', 'Là thứ mấy?:', 'Là thứ mấy?:', 'Hôm nay là thứ mấy? Hôm nay là thứ 5.', 'Q: ～は なんようびですか。 / A：～ようびです。 / Q: きょうは なんようびですか。', 1, 2, TRUE, 1),
(20, 4, 'Động từ ます:', '✓ Động từ là loại từ kết thúc bằng ます. / おきます', 'Động từ ます:', 'Tôi học bài mỗi tối. Chú ý:', '3. Động từ ます: / ✓ Động từ là loại từ kết thúc bằng ます. / おきます', 1, 3, TRUE, 1),
(21, 4, 'Làm V vào lúc ～ giờ：', 'ねます / ねません', 'Làm V vào lúc ～ giờ：', 'Hôm qua tôi đã ngủ lúc 10 giờ tối.', '4. Làm V vào lúc ～ giờ： / ねます / ねません', 1, 4, TRUE, 1),
(22, 4, 'Từ ～ đến :', 'N1, N2: thời gian, địa điểm. / ➢ から：biểu thị điểm bắt đầu.', 'Từ ～ đến :', 'Ý nghĩa: ➢ Là cách nói khoảng thời gian từ lúc nào đến lúc nào, từ đâu đến đâu.', 'です。 / V ます。 / N1, N2: thời gian, địa điểm.', 1, 5, TRUE, 1),
(23, 4, 'N1 và N2:', 'N1 と N2', 'N1 và N2:', 'Cách dùng: ➢ Ý nghĩa: với, và, cùng. ➢ Dùng để nối danh từ với danh từ.', '6. N1 và N2: / N1 と N2 / このびじゅつかんは きんようびと どようび やすみます。', 1, 6, TRUE, 1),
(24, 5, 'Nói ngày, tháng, năm:', 'Nói ngày, tháng, năm:', 'Nói ngày, tháng, năm:', 'Hôm nay là ngày mùng 1 tháng 4.', 'Nói ngày, tháng, năm: / Thời gian は ～ねん～がつ～にちです。 / Thời gian: きょう、～のたんじょうび、あした、。。。', 1, 1, TRUE, 1),
(25, 5, 'Động từ chuyển động:', 'S は N へ いきます (đi) / きます (đến)', 'Động từ chuyển động:', 'Ý nghĩa: Đi, đến, về một địa điểm nào đó. Chú ý: Trợ từ へ dùng để chỉ phương hướng di chuyển.', '1. NGÀY, THÁNG, NĂM 4. TRỢ TỪ で / 2. ĐỘNG TỪ CHUYỂN ĐỘNG H 5. TRỢ TỪ と / 3. ĐI/ ĐẾN/ VỀ ĐÂU', 1, 2, TRUE, 1),
(26, 5, 'Hỏi đi/ đến/ về đâu?:', 'Hỏi đi/ đến/ về đâu?:', 'Hỏi đi/ đến/ về đâu?:', 'Tháng 7 này cậu đi đâu không? Tớ đi Đà Nẵng', 'Q: どこへ いきますか。 / A： Địa điểm へ いきます。 / どこも いきません。', 1, 3, TRUE, 1),
(27, 5, 'Bằng phương tiện gì 「で」：', 'S は N で N へ いきます / (phương tiện) (địa điểm) きます', 'Bằng phương tiện gì 「で」：', 'Tôi đến siêu thị bằng xe đạp. • Hỏi đi bằng phương tiện gì?', '4. Bằng phương tiện gì 「で」： / S は N で N へ いきます / (phương tiện) (địa điểm) きます', 1, 4, TRUE, 1),
(28, 5, 'Làm gì với ai đó 「と」：', 'Làm gì với ai đó 「と」：', 'Làm gì với ai đó 「と」：', 'Mẫu ngữ pháp N5: Làm gì với ai đó 「と」：.', '5. Làm gì với ai đó 「と」： / S は N と N へ いきます。 / (người) (địa điểm) きます。', 1, 5, TRUE, 1),
(29, 6, 'Ăn ～, uống ～, làm ～：', '➢ N: Danh từ (đối tượng của hành động V). / ➢ V: Tha động từ (những động từ có sự tác động trực tiếp của', 'Ăn ～, uống ～, làm ～：', 'Cách dùng: ➢ N: Danh từ (đối tượng của hành động V). ➢ V: Tha động từ (những động từ có sự tác động trực tiếp của con người).', 'N を V ます。 / ➢ N: Danh từ (đối tượng của hành động V). / ➢ V: Tha động từ (những động từ có sự tác động trực tiếp của', 1, 1, TRUE, 1),
(30, 6, 'Làm, chơi, tổ chức:', 'Làm, chơi, tổ chức:', 'Làm, chơi, tổ chức:', 'Cuối tuần tớ sẽ chơi tennis. • Làm (đã làm) gì? Cách dùng: ➢ Đây là mẫu câu hỏi chung cho tất cả các động từ. ➢ Nếu không làm gì thì sẽ trả lời:', 'N を します。 / しゅうまつ テニスを します。 / Q：なにを しますか／しましたか。', 1, 2, TRUE, 1),
(31, 6, '～Làm (đã làm) cái gì ở đâu?:', '～Làm (đã làm) cái gì ở đâu?:', '～Làm (đã làm) cái gì ở đâu?:', 'Cậu ăn trưa ở đâu? Tớ ăn trưa ở nhà ăn.', 'Q: どこで N を しますか／しましたか。 / A：Địa điểm で (N を） V ます／ました。 / Q: どこで ひるごはんを たべますか。', 1, 3, TRUE, 1),
(32, 6, 'Cùng ～ với mình chứ?', '➢ ええ、いいですね: Vâng, hay nhỉ (được đấy nhỉ). / ➢ すみません、ちょっと。。。: Xin lỗi, nhưng mà….', 'Cùng ～ với mình chứ?', 'Cách dùng: ➢ Dùng để mời, đề nghị ai đó cùng làm việc gì đó với mình. (Đây là cách từ chối khéo lời mời)', 'Q：いっしょに V ませんか。 / A： ええ、いいですね。 / すみません、ちょっと。。。', 1, 4, TRUE, 1),
(33, 6, 'Cùng làm ～nhé：', '➢ 「ませんか」： / ➢ 「ましょう」：', 'Cùng làm ～nhé：', 'Cách dùng: ➢ Mời, đề nghị ai đó làm gì cùng mình, thể hiện thái độ chủ động của người nói. ➢ Hô hào mọi người cùng làm gì đó. ✓ Sử dụng khi chưa biết người nghe có đồng ý với lời mời, đề nghị hay là không. ✓ Thể hiện thái độ rụt rè, giữ ý của người nói. ✓ Sử dụng khi đã biết người nghe đã đồng ý với lời mời, đề nghị của mình. ✓ Mẫu câu này cũng được dùng để trả lời cho mẫu', 'N を ましょう。 / • Phân biệt 「ませんか」 và「ましょう」。 / ➢ 「ませんか」：', 1, 5, TRUE, 1),
(34, 7, 'Dùng phương tiện, cách thức nào đó để ~ ：', 'Dùng phương tiện, cách thức nào đó để ~ ：', 'Dùng phương tiện, cách thức nào đó để ~ ：', 'Cắt giấy bằng kéo. • Làm V bằng phương tiện, công cụ nào?', 'N で Ｎを V ます。 / はさみで かみを きります。 / • Làm V bằng phương tiện, công cụ nào?', 1, 1, TRUE, 1),
(35, 7, 'A trong ngôn ngữ nào đó là B:', 'A trong ngôn ngữ nào đó là B: / Chú ý: A , B có thể là 1 câu, 1 từ ngữ hoặc 1 đại từ chỉ thẳng.', 'A trong ngôn ngữ nào đó là B:', 'Chú ý: A , B có thể là 1 câu, 1 từ ngữ hoặc 1 đại từ chỉ thẳng.', 'A trong ngôn ngữ nào đó là B: / Ａは ～ごで Ｂです。 / ほん', 1, 2, TRUE, 1),
(36, 7, 'Câu cho nhận 1 N:', 'người cho người nhận V cho / ➢ A cho B 1 N nào đó.', 'Câu cho nhận 1 N:', 'Ý nghĩa: ➢ A cho B 1 N nào đó. ➢ V cho:', '3. Câu cho nhận 1 N: / A は B に Ｎを Ｖます。 / người cho người nhận V cho', 1, 3, TRUE, 1),
(37, 7, 'Đã làm xong V rồi:', 'Đã làm xong V rồi:', 'Đã làm xong V rồi:', 'Tôi đã ăn sáng rồi. • Đã làm V chưa?', 'Đã làm xong V rồi: / Ｓは もう Ｎを Ｖました。 / わたしは もう あさごはんを たべました。', 1, 4, TRUE, 1),
(38, 8, 'Tính từ:', '• Tính từ đuôi い：', 'Tính từ:', 'Tính từ:', '• Tính từ đuôi い： / つめたい (lạnh)、やすい (rẻ)、たかい(cao/ đắt)、。。。 / Tính từ đuôi な：', 1, 1, TRUE, 1),
(39, 8, 'Câu khẳng định của tính từ:', '➢ N thì ∼ / ➢ Ở mẫu câu này, nếu tính từ đuôi いthì giữ nguyên い, tính từ', 'Câu khẳng định của tính từ:', 'Ý nghĩa: ➢ N thì ∼', 'N は A い／ A なです。 / 1. TÍNH TỪ. / 2. CÂU KHẲNG ĐỊNH CỦA TÍNH TỪ.', 1, 2, TRUE, 1),
(40, 8, 'Câu phủ định của tính từ:', '➢ N thì không∼ / 「いい」→ 「よくない」', 'Câu phủ định của tính từ:', 'Ý nghĩa: ➢ N thì không∼ ➢ Trường hợp phủ định của tính từ:', 'Ｎは A い くないです。 / A な じゃ（では）ありません。 / ➢ N thì không∼', 1, 3, TRUE, 1),
(41, 8, 'Tính từ bổ nghĩa cho danh từ:', 'A いN2', 'Tính từ bổ nghĩa cho danh từ:', 'Cách dùng: ➢ Khi tính từ bổ nghĩa cho danh từ, cả cụm tính từ + danh từ đó được coi như 1 danh từ. Vì thế, khi chia phủ định, quá khứ thì chia như 1 danh từ.', 'N1 は A な N2 です。 / A いN2', 1, 4, TRUE, 1),
(42, 8, '∼ và, hơn nữa ∼:', 'Câu 1 そして Câu 2 / Chú ý: Phân biệt そして và と', '∼ và, hơn nữa ∼:', 'Cách dùng: Nối 2 câu tương đồng với nhau về nghĩa. Chú ý: Phân biệt そして và と', 'Câu 1 そして Câu 2 / ➢ そして：Sử dụng để nối 2 câu. / ➢ と ：Sử dụng để nối 2 danh từ.', 1, 5, TRUE, 1),
(43, 8, '∼nhưng, ∼:', 'Câu 1 が Câu 2', '∼nhưng, ∼:', 'Cách dùng: Nối 2 câu có ý nghĩa trái ngược nhau.', 'Câu 1 が Câu 2', 1, 6, TRUE, 1),
(44, 8, '∼như thế nào?:', '∼như thế nào?:', '∼như thế nào?:', 'Cách dùng: ➢ Dùng để hỏi về cảm tưởng, tính chất, tình trạng của người hay vật. ➢ Khi trả lời thì không cần kết hợp danh từ ở phía sau. ➢ Khi trả lời thì phải sử dụng mẫu tính từ bổ nghĩa cho danh từ.', 'Q： N は どうですか。 / A： A い／A なです。 / Q： N1 は どん な N2 ですか。', 1, 7, TRUE, 1),
(45, 8, '∼cái nào?:', '∼cái nào?:', '∼cái nào?:', 'Cách dùng: ➢ Sử dụng để yêu cầu người nghe xác định một vật nào đó trong một nhóm từ hai vật trở lên. ➢ Chúng ta dùng mẫu câu tính từ bổ nghĩa cho danh từ để trả lời cho câu hỏi trên.', 'N は どれですか。 / Q： ミンさんの くるまは どれですか。 / A： あおい くるまです。', 1, 8, TRUE, 1),
(46, 9, 'Thích, ghét ∼:', 'Thích, ghét ∼:', 'Thích, ghét ∼:', 'Tôi thích sushi. • Thích, ghét ∼ không ? Lưu ý: 1. THÍCH, GHÉT∼ 2. GIỎI, KÉM∼ 3. HIỂU, KHÔNG HIỂU∼ 4. CÓ, KHÔNG CÓ∼ 5. PHÓ TỪ CHỈ MỨC ĐỘ 6. N NHƯ THẾ NÀO? 7. ∼ NHƯNG, TUY NHIÊN 8. VÌ ∼ NÊN (CÂU NGUYÊN NHÂN KẾT QUẢ)', 'S は Ｎが すきです。 / きらいです。 / Q: Ｓは Ｎが すき/きらい ですか。', 1, 1, TRUE, 1),
(47, 9, 'Giỏi, kém ∼:', 'Giỏi, kém ∼:', 'Giỏi, kém ∼:', 'Tôi nhảy giỏi.', 'S は Ｎが じょうず／ へたです。', 1, 2, TRUE, 1),
(48, 9, 'Hiểu/ không hiểu ∼:', 'Hiểu/ không hiểu ∼:', 'Hiểu/ không hiểu ∼:', 'Tôi hiểu tiếng Nhật. • Biết, không biết ∼ không?', 'S は N が わかります。 / わかりません。 / わたしは にほんご が わかります。', 1, 3, TRUE, 1),
(49, 9, 'Có/ không có ∼:', 'Có/ không có ∼:', 'Có/ không có ∼:', 'Nam có xe ô tô đẹp. • Có ∼ không?:', 'S は N が あります。 / ありません。 / ナムさんは きれいな くるまが あります。', 1, 4, TRUE, 1),
(50, 9, 'Phó từ chỉ mức độ:', 'ぜんぜん(hoàn toàn không) / あまり(không…lắm)', 'Phó từ chỉ mức độ:', 'Tôi hiểu 1 chút tiếng Nhật. • Phó từ chỉ số lượng:', 'ぜんぜん(hoàn toàn không) / あまり(không…lắm) / すこし(một chút)', 1, 5, TRUE, 1),
(51, 9, 'N như thế nào?', 'A な', 'N như thế nào?', 'Bạn thích môn thể thao nào? Tôi thích bóng đá.', 'N như thế nào? / Q: どんなＮ が すき/きらいですか。 / A: A い Ｎ が すき/きらいです。', 1, 6, TRUE, 1),
(52, 9, 'Vì ∼ nên (câu nguyên nhân, kết quả):', 'Câu nguyên nhân + から+ Câu kết quả.', 'Vì ∼ nên (câu nguyên nhân, kết quả):', 'Vì không có thời gian nên không chơi thể thao.', 'Câu nguyên nhân + から+ Câu kết quả. / じかんが ありませんから、スポーツを しません。', 1, 7, TRUE, 1),
(53, 9, 'Tại sao/ Vì sao ～:', 'Tại sao/ Vì sao ～:', 'Tại sao/ Vì sao ～:', 'Tại sao/ Vì sao ～:', 'Q: どうして + V ますか。 / V ませんか。 / A: Lý do + から。', 1, 8, TRUE, 1),
(54, 10, 'Cách nói vị trí cụ thể:', 'N１の N２', 'Cách nói vị trí cụ thể:', 'Trên bàn.', 'N１の N２', 1, 1, TRUE, 1),
(55, 10, 'Ở địa điểm ∼ có N:', 'Ở địa điểm ∼ có N: / ➢ Làm gì ở ∼ thì dùng trợ từ で sau địa điểm.', 'Ở địa điểm ∼ có N:', 'Chị Mai có quyển từ điển tiếng Nhật.', 'Ở địa điểm ∼ có N: / N1 に N2 が あります。 / N1 に N2 が います。', 1, 2, TRUE, 1),
(56, 10, 'Nhấn mạnh N ở ∼:', 'Ｎ1 は N2 に います', 'Nhấn mạnh N ở ∼:', 'Rau và hoa quả thì có ở trong tủ lạnh. • N (đồ vật) có ở đâu? • N (người, con vật) có ở đâu?', '3. Nhấn mạnh N ở ∼: / Ｎ1 は N2 に あります。 / Ｎ1 は N2 に います', 1, 3, TRUE, 1),
(57, 10, '∼ và ∼ và…:', 'N1 や N2 … など / ➢ と： Dùng để liệt kê toàn bộ danh từ.', '∼ và ∼ và…:', 'Cách dùng: や…や…など： Dùng để liệt kê các danh từ. (ngoài những thứ đó ra vẫn còn những thứ khác)', 'N1 や N2 … など / ➢ と： Dùng để liệt kê toàn bộ danh từ. / ➢ や： Dùng để liệt kê 1 số danh từ tượng trưng.', 1, 4, TRUE, 1),
(58, 11, 'Số lượng từ đi với câu có động từ:', 'Số lượng từ đi với câu có động từ:', 'Số lượng từ đi với câu có động từ:', 'Tôi 25 tuổi. Số lượng từ đi với câu có động từ:', 'N は Số lượng từ です。 / N Trợ từ Số lượng từ V ます。 / が あります／います', 1, 1, TRUE, 1),
(59, 11, 'Làm V trong khoảng thời gian:', 'Làm V trong khoảng thời gian:', 'Làm V trong khoảng thời gian:', 'Tôi đã học tiếng Nhật trong khoảng 2 tháng. Làm V trong khoảng bao lâu?', 'Làm V trong khoảng thời gian: / N ぐらい V ます。 / 2 かげつぐらい 日本語', 1, 2, TRUE, 1),
(60, 11, 'Làm V ～ lần trong khoảng thời gian ～ (câu tần', 'Làm V ～ lần trong khoảng thời gian ～ (câu tần', 'Làm V ～ lần trong khoảng thời gian ～ (câu tần', '1 ngày tôi ăn cơm 3 lần. • Làm V bao nhiêu lần trong khoảng thời gian N: (khoảng thời gian)', '3. Làm V ～ lần trong khoảng thời gian ～ (câu tần / N に ～かい N を V ます。 / わたしは いちにちに ３かい ごはんを たべます。', 1, 3, TRUE, 1),
(61, 11, 'Chỉ ～:', 'だけ thay thế cho が、を. / Các trợ từ khác như に、で、から thì có thể đứng trước', 'Chỉ ～:', 'Cách dùng:', 'N だけ。 / だけ thay thế cho が、を. / Các trợ từ khác như に、で、から thì có thể đứng trước', 1, 4, TRUE, 1),
(62, 12, 'Quá khứ của tính từ và danh từ', 'Tính từ đuôi「な」và danh từ:', 'Quá khứ của tính từ và danh từ', 'Sáng nay trời (đã) mưa. 1. QUÁ KHỨ CỦA TÍNH TỪ VÀ DANH TỪ. 2. N1 HƠN N2. 3. N1 VÀ N2 THÌ CÁI NÀO ~ HƠN? 4. TRONG N1 THÌ N2 LÀ ~ NHẤT. Khẳng định: (đã～) Phủ định: (đã không～)', 'Tính từ đuôi「な」và danh từ: / N／A（な）でした。 / N／A（な）じゃありませんでした。', 1, 1, TRUE, 1),
(63, 12, 'N1 hơn N2:', 'N1 hơn N2: / Ø Phó từ thường đi kèm là ずっと (hơn hẳn).', 'N1 hơn N2:', 'Cách dùng: Ø Mẫu câu này dùng để so sánh 2 danh từ với nhau.', 'N1 hơn N2: / N1 は N2 より A です。 / Ø Phó từ thường đi kèm là ずっと (hơn hẳn).', 1, 2, TRUE, 1),
(64, 12, 'N1 và N2 thì cái nào ∼ hơn?', '(Cả N1 và N2 đều ~)', 'N1 và N2 thì cái nào ∼ hơn?', 'Núi và biển bạn thích cái nào hơn? Tôi thích biển hơn.', '3. N1 và N2 thì cái nào ∼ hơn? / Q： N1 と N2 と どちらが A ですか。 / A： N1／N2 の ほうが A です。', 1, 3, TRUE, 1),
(65, 12, 'Trong N1 thì N2 là ~ nhất:', 'Trong N1 thì N2 là ~ nhất: / Ø N2 phải thuộc phạm vi N1.', 'Trong N1 thì N2 là ~ nhất:', 'Chú ý: Ø N2 phải thuộc phạm vi N1.', 'Trong N1 thì N2 là ~ nhất: / N1（のなか）で N2 が いちばん A です。 / Ø N2 phải thuộc phạm vi N1.', 1, 4, TRUE, 1),
(66, 13, 'Muốn/ không muốn cái gì đó', 'KHÔNG DÙNG khi nói đến ước muốn, ham thích của / NGƯỜI KHÁC.', 'Muốn/ không muốn cái gì đó', 'Cách dùng: Dùng để nói ước muốn, ham thích của bản thân. KHÔNG DÙNG khi nói đến ước muốn, ham thích của NGƯỜI KHÁC. Chú ý: N : Đồ vật, người, động vật.', '(わたし は) N が ほしいです。 / ほしくないです。 / KHÔNG DÙNG khi nói đến ước muốn, ham thích của', 1, 1, TRUE, 1),
(67, 13, 'Muốn, không muốn làm hành động gì đó:', '• Động từ thể たい:', 'Muốn, không muốn làm hành động gì đó:', '• Tôi thích, muốn làm N: Cách dùng: Dùng để nói mong muốn làm việc gì đó của người nói. KHÔNG DÙNG khi nói đến mong muốn làm hành động của NGƯỜI KHÁC. Chú ý:', '• Động từ thể たい: / Cách chia: Bỏ đuôi ます rồi thêm たい。 / むかえます(đón) → むかえたい', 1, 2, TRUE, 1),
(68, 13, 'Đi/ đến/ trở về địa điểm để làm V,N:', 'Đi/ đến/ trở về địa điểm để làm V,N: / V ます きます', 'Đi/ đến/ trở về địa điểm để làm V,N:', 'Cách dùng: Mẫu câu dùng để nói mục đích đi/ đến/ trở về đâu đó để thực hiện hành động.', 'Đi/ đến/ trở về địa điểm để làm V,N: / V ます きます / Địa điểm へ V しますに いきます', 1, 3, TRUE, 1),
(69, 14, 'Phân nhóm động từ. Động từ được chia làm 3 nhóm', 'Là những động từ đứng trước đuôi ますlà các chữ cái thuộc cột', 'Phân nhóm động từ. Động từ được chia làm 3 nhóm', '• Động từ nhóm II: thuộc cột e. 1. PHÂN NHÓM ĐỘNG TỪ. 3. HÃY ~ 4. ĐANG LÀM V ~ 5. ĐỂ TÔI LÀM ~ GIÚP BẠN NHÉ.', 'Là những động từ đứng trước đuôi ますlà các chữ cái thuộc cột / のみます(uống) いそぎます(nhanh) / はたらきます(làm việc) あそびます(chơi)', 1, 1, TRUE, 1),
(70, 14, 'Cách chia thể て:', 'Cách chia thể て: / ～います', 'Cách chia thể て:', 'Ø Cách chia 2:', 'Cách chia thể て: / ～います / ～ちます ～って', 1, 2, TRUE, 1),
(71, 14, 'Hãy ～:', 'Ø Khi nhờ vả thì thường thêm むみませんが đầu câu.', 'Hãy ～:', 'Cách dùng: Ø Dùng để sai khiến, yêu cầu, khuyên nhủ, nhờ vả ai đó. Chú ý: Không dùng mẫu này với ý nghĩa sai khiến với người trên.', 'V て ＋ ください。 / Ø Khi nhờ vả thì thường thêm むみませんが đầu câu. / すみませんが、タクシー を よんで ください。', 1, 3, TRUE, 1),
(72, 14, 'Đang làm V～：', 'Đang làm V～：', 'Đang làm V～：', 'Bây giờ anh Nam đang bơi ở trong bể bơi. • Bây giờ ～ đang ～ phải không?', 'Đang làm V～： / V て ＋ います。 / いま、ナムさんは プールで およいで います。', 1, 4, TRUE, 1),
(73, 14, 'Để tôi làm ～ giúp bạn nhé：', 'Ø Cách kết hợp: V bỏ ます thêm ましょうか.', 'Để tôi làm ～ giúp bạn nhé：', 'Cách dùng: Ø Dùng khi muốn đề nghị làm 1 việc gì đó cho người nghe.', 'Q: V ましょうか。 / A: すみません、おねがいします。 / いい、けっこうです。', 1, 5, TRUE, 1),
(74, 15, 'Làm V cũng được:', 'Làm V cũng được:', 'Làm V cũng được:', 'Cách dùng: Dùng để biểu thị sự được phép làm V.', 'Làm V cũng được: / (S は) N を V てもいいです。 / • Làm V có được không?', 1, 1, TRUE, 1),
(75, 15, 'Không được làm V:', 'Không được làm V: / Dùng để biểu thị sự cấm đoán, không được phép làm V.', 'Không được làm V:', 'Cách dùng: Dùng để biểu thị sự cấm đoán, không được phép làm V.', 'Không được làm V: / (S は) N を V ては いけません。 / Dùng để biểu thị sự cấm đoán, không được phép làm V.', 1, 2, TRUE, 1),
(76, 15, 'Đang trong tình trạng làm V:', 'Đang trong tình trạng làm V: / Ø Nếu là thói quen trong quá khứ thì sẽ chia thành', 'Đang trong tình trạng làm V:', 'Cách dùng: Ø Trạng thái của hành động diễn ra từ QK-HT-TL. Ø Thói quen , tập quán được lặp đi lặp lại trong 1 thời gian. Ø Nếu là thói quen trong quá khứ thì sẽ chia thành', 'Đang trong tình trạng làm V: / (S は) N を V ています。 / Ø Nếu là thói quen trong quá khứ thì sẽ chia thành', 1, 3, TRUE, 1),
(77, 16, 'Làm V1, làm V2, rồi làm …', 'Ø Thường hay thêm それからtrước hành động cuối cùng.', 'Làm V1, làm V2, rồi làm …', 'Cách dùng: Ø Liệt kê hai hay nhiều hành động theo trật tự thời gian. Ø Thì của câu được biểu thị ở động từ cuối cùng.', 'V1 て、V2 て、。。。V ます。 / Ø Thường hay thêm それからtrước hành động cuối cùng. / きのう しごとが おわって、おかねを だして、', 1, 1, TRUE, 1),
(78, 16, 'Làm V1 rồi làm V2:', 'Ø Nhấn mạnh sau khi hành động V1 kết thúc thì liền sau đó', 'Làm V1 rồi làm V2:', 'Cách dùng: Ø Nhấn mạnh sau khi hành động V1 kết thúc thì liền sau đó là hành động V2 xảy ra. Ø Thì của câu được biểu thị ở động từ cuối cùng.', 'V1 てから、V2 ます。 / Ø Nhấn mạnh sau khi hành động V1 kết thúc thì liền sau đó / でんわを かけてから、ともだちの うちに いきます。', 1, 2, TRUE, 1),
(79, 16, 'Cách nối tính từ và danh từ:', 'A い → くて ＋ A い／A な／N / A な ／N → で ＋ A い／A な／N', 'Cách nối tính từ và danh từ:', 'Cách dùng: Ø Dùng để nối 2 hay nhiều tính từ, danh từ với nhau. Ø Vì mang ý nghĩa “và” nên KHÔNG dùng để nối 2 câu có ý nghĩa trái ngược nhau.', 'A い → くて ＋ A い／A な／N / A な ／N → で ＋ A い／A な／N / Ø Vì mang ý nghĩa “và” nên KHÔNG dùng để nối 2 câu có', 1, 3, TRUE, 1),
(80, 16, 'N2 (của) N1 thì:', 'N2 (của) N1 thì: / Ø Dùng để miêu tả đặc điểm, tính chất của N1.', 'N2 (của) N1 thì:', 'Cách dùng: Ø Dùng để miêu tả đặc điểm, tính chất của N1. Ø N2 là thuộc tính, thành phần của N1.', 'N2 (của) N1 thì: / N1 は N2 が A です。 / Ø Dùng để miêu tả đặc điểm, tính chất của N1.', 1, 4, TRUE, 1),
(81, 16, 'Làm ～ như thế nào?', 'Làm ～ như thế nào?', 'Làm ～ như thế nào?', 'Mẫu ngữ pháp N5: Làm ～ như thế nào?.', 'Làm ～ như thế nào?', 1, 5, TRUE, 1),
(82, 16, 'N NÀO?', 'Ø Nhấn mạnh sau khi hành động V1 kết thúc thì liền sau đó', 'N NÀO?', 'Cách dùng: Ø Nhấn mạnh sau khi hành động V1 kết thúc thì liền sau đó là hành động V2 xảy ra. Ø Thì của câu được biểu thị ở động từ cuối cùng.', '6. N NÀO? / V1 てから、V2 ます。 / Ø Nhấn mạnh sau khi hành động V1 kết thúc thì liền sau đó', 1, 6, TRUE, 1),
(83, 17, 'Xin đừng làm V:', 'Xin đừng làm V: / • Thể ない：', 'Xin đừng làm V:', '1. XIN ĐỪNG LÀM V. 2. PHẢI LÀM V, BẮT BUỘC PHẢI LÀM V. 3. KHÔNG LÀM V CŨNG ĐƯỢC. 4. CHẬM NHẤT, CHO ĐẾN TRƯỚC KHI. 5. NHẤN MẠNH N. Ø Động từ nhóm II:', 'Xin đừng làm V: / • Thể ない： / Ｖない ＝ Ｖません', 1, 1, TRUE, 1),
(84, 17, 'Phải làm V, bắt buộc phải làm V:', 'Phải làm V, bắt buộc phải làm V:', 'Phải làm V, bắt buộc phải làm V:', 'Cách dùng: Khi một việc coi như nghĩa vụ phải làm, bất chấp ý hướng của người làm. Chú ý: Mặc dù động từ chia ở dạng phủ định nhưng cả câu không mang nghĩa phủ định.', 'Phải làm V, bắt buộc phải làm V: / V なければ なりません。 / V ない + ければ なりません。', 1, 2, TRUE, 1),
(85, 17, 'Không cần làm V cũng được:', 'Không cần làm V cũng được:', 'Không cần làm V cũng được:', 'Không cần trả tiền cũng được.', 'Không cần làm V cũng được: / V なくてもいいです。 / V ない + くて もいいです。', 1, 3, TRUE, 1),
(86, 17, 'Chậm nhất, cho đến trước khi:', 'N までに', 'Chậm nhất, cho đến trước khi:', 'Cách dùng: Chỉ rõ thời gian cuối mà một hành động hay một công việc phải được tiến hành trước thời hạn được chỉ định.', 'N までに / 金曜日 / きんようび', 1, 4, TRUE, 1),
(87, 17, 'Nhấn mạnh N:', 'Nhấn mạnh N: / ～N を V ます', 'Nhấn mạnh N:', 'Cách dùng: Ø Đưa tân ngữ lên làm chủ ngữ để nhằm nhấn mạnh ý muốn diễn tả.', 'Nhấn mạnh N: / ～N を V ます / N は～ V ます', 1, 5, TRUE, 1),
(88, 18, 'Có thể/ có khả năng:', 'Ｖ(từ điển) ＝ Ｖます / ～i ます → ～u', 'Có thể/ có khả năng:', '1. CÓ THỂ/ CÓ KHẢ NĂNG. 2. SỞ THÍCH. 3. TRƯỚC (KHI). 4. MÃI MÀ KHÔNG. 5. RẤT MUỐN ～/ NHẤT ĐỊNH HÃY ～. Ø Động từ nhóm II:', 'Ｖ(từ điển) ＝ Ｖます / ～i ます → ～u / あいます(gặp) → あう', 1, 1, TRUE, 1),
(89, 18, 'Sở thích:', 'V ること', 'Sở thích:', 'Sở thích của tôi là du lịch. • Sở thích của bạn là gì?', '（わたしの）しゅみは N です。 / V ること / しゅみは なんですか。', 1, 2, TRUE, 1),
(90, 18, 'Trước khi làm ～ thì làm V2 :', 'V1 る まえに、V2 / N の', 'Trước khi làm ～ thì làm V2 :', 'Chú ý: Ø Thì của câu được biểu thị ở V2.', 'V1 る まえに、V2 / N の / Ø N là danh từ chỉ hành động, hành vi: りょこう(du lịch)、', 1, 3, TRUE, 1),
(91, 18, 'Mãi mà không:', 'Mãi mà không:', 'Mãi mà không:', 'Chú ý: Luôn đi kèm với động từ phủ định.', 'なかなか V ません。 / わたしは 日本語 / にほんご', 1, 4, TRUE, 1),
(92, 18, 'Rất muốn ～ nhất định hãy ～:', 'Rất muốn ～ nhất định hãy ～:', 'Rất muốn ～ nhất định hãy ～:', 'Tôi rất muốn leo núi Phú Sĩ.', 'ぜひ、 V たいです。 / ぜひ、 V てください。 / ぜひ、ふじさんに のぼりたいです。', 1, 5, TRUE, 1),
(93, 19, 'Đã từng làm V:', 'Đã từng làm V: / • Thể た：', 'Đã từng làm V:', 'Ø Động từ nhóm II:', 'Đã từng làm V: / • Thể た： / V ます → V て → V た', 1, 1, TRUE, 1),
(94, 19, 'Liệt kê hành động:', 'Liệt kê hành động:', 'Liệt kê hành động:', 'Cách dùng: Ø Dùng khi muốn biểu hiện một vài hành động đại diện trong số nhiều hành động mà chủ thể thực hiện, không cần quan tâm cái nào xảy ra trước cái nào xảy ra sau. Ø Thì của mẫu câu được thể hiện ở cuối câu.', 'V1 たり、V2 たり します。 / 日曜日 / にちようび', 1, 2, TRUE, 1),
(95, 19, 'Trở nên, trở thành:', 'A い → く / N に', 'Trở nên, trở thành:', 'Cách dùng: Chỉ sự thay đổi một tình trạng hay một điều kiện. sáng → tối, gầy → béo, to → nhỏ.', 'A い → く / A な → に なります／なりました。 / N に', 1, 3, TRUE, 1),
(96, 20, 'Thể thông thường và thể lịch sự:', 'THỂ THÔNG THƯỜNG / V ます', 'Thể thông thường và thể lịch sự:', 'Mỗi ngày tôi thức dậy lúc 6 giờ. • Dạng câu hỏi của động từ： cuối câu. Khi trả lời ở dạng câu hỏi có hoặc không:', 'THỂ THÔNG THƯỜNG / V ます / V る', 1, 1, TRUE, 1),
(97, 20, 'けど：nhưng Cách dùng:', 'けど：nhưng', 'けど：nhưng Cách dùng:', 'Cách dùng: Ø Hay được dùng trong hội thoại.', 'けど：nhưng / Ø けど có chức năng giống が。 / Tiếng Nhật khó nhưng mà thú vị.', 1, 2, TRUE, 1),
(98, 21, 'Tôi nghĩ là:', 'Tôi nghĩ là:', 'Tôi nghĩ là:', 'Cách dùng: Ø Biểu thị phỏng đoán, phán đoán chủ quan. Ø Bày tỏ ý kiến, đánh giá cá nhân. Ø Thể hiện sự đồng tình hoặc không đồng tình với ý kiến của người khác.', 'Thể thông thường とおもいます。', 1, 1, TRUE, 1),
(99, 21, 'Trích dẫn lời nói:', 'Trích dẫn lời nói:', 'Trích dẫn lời nói:', '• Trích dẫn lời nói của người khác. Ø Trích dẫn lời nói trực tiếp:', '1. TÔI NGHĨ LÀ. / 2. TRÍCH DẪN LỜI NÓI. / 3. ～PHẢI KHÔNG NHỈ?/ ～ĐÚNG KHÔNG?', 1, 2, TRUE, 1),
(100, 21, '～Phải không nhỉ?/ ～đúng không?', 'Ａな/Ｎだ→Ｎ', '～Phải không nhỉ?/ ～đúng không?', 'Cách dùng: Ø Kêu gọi sự đồng tình, xác nhận sự đồng ý của người nghe. Ø Phát âm lên cao giọng ở cuối câu.', 'Thể thông thường でしょう。 / Ａな/Ｎだ→Ｎ / かれは ハンサムでしょう。', 1, 3, TRUE, 1),
(101, 21, 'Ở đâu có điều gì đó:', 'Ở đâu có điều gì đó:', 'Ở đâu có điều gì đó:', 'Ở Hà Nội có trận bóng đá giữa Việt Nam và Thái Lan. • 1 sự việc diễn ra ở 1 tình huống nào đó:', 'Địa điểm で N が あります。 / ハノイで タイと ベトナムのサッカーの / しあいが あります。', 1, 4, TRUE, 1),
(102, 22, 'Mệnh đề bổ ngữ:', 'Mệnh đề bổ ngữ:', 'Mệnh đề bổ ngữ:', 'Định nghĩa: Ø Bổ ngữ là thành phần bổ sung thêm ý nghĩa, làm rõ nghĩa hơn cho danh từ. Ø Phần bổ ngữ luôn đứng trước danh từ mà nó bổ nghĩa. • Mệnh đề bổ nghĩa đã học: Ø Danh từ bổ nghĩa cho danh từ', 'Giáo viên tiếng Nhật. / 1. MỆNH ĐỀ BỔ NGỮ. / 2. MỆNH ĐỀ BỔ NGỮ CHO DANH TỪ LÀ VỊ NGỮ.', 1, 1, TRUE, 1),
(103, 22, 'Mệnh đề bổ ngữ cho danh từ là vị ngữ:', '=> trợ từ が. / Ø Chủ ngữ chính của câu => trợ từ は.', 'Mệnh đề bổ ngữ cho danh từ là vị ngữ:', 'Ý nghĩa: S là N mà. Lưu ý: Ø Chủ ngữ của mệnh đề bổ nghĩa cho danh từ => chủ ngữ phụ nguyên.', 'S は 文(thể thông thường) N です。 / => trợ từ が. / Ø Chủ ngữ chính của câu => trợ từ は.', 1, 2, TRUE, 1),
(104, 22, 'Mệnh đề bổ ngữ cho danh từ là chủ ngữ:', 'もの ひと ところ', 'Mệnh đề bổ ngữ cho danh từ là chủ ngữ:', 'Ý nghĩa: N mà… là…', '文(thể thông thường) N は ～ です。 / もの ひと ところ / めがねを かけている 人 はマイさんです。', 1, 3, TRUE, 1),
(105, 22, 'Mệnh đề bổ ngữ cho danh từ là chủ ngữ và vị ngữ:', '文(thể thông thường)N は 文(thể thông thường)N です. / S N', 'Mệnh đề bổ ngữ cho danh từ là chủ ngữ và vị ngữ:', 'Đôi giày mà tôi đang đi là đôi giày mà mẹ tôi đã mua.', '文(thể thông thường)N は 文(thể thông thường)N です. / S N', 1, 4, TRUE, 1),
(106, 22, 'Mệnh đề bổ ngữ cho danh từ là tân ngữ:', 'Mệnh đề bổ ngữ cho danh từ là tân ngữ:', 'Mệnh đề bổ ngữ cho danh từ là tân ngữ:', 'Tôi thích người mà có tính hài hước.', 'S は 文(thể thông thường)N+ を～。 / O が～。 / ユーモアが あるひと がすきです。', 1, 5, TRUE, 1),
(107, 22, 'Có (không có) thời gian, cuộc hẹn, việc bận, tiền để làm gì đó:', 'V る ＋ じかん／やくそく ＋ が あります', 'Có (không có) thời gian, cuộc hẹn, việc bận, tiền để làm gì đó:', 'Tôi không có thời gian để ăn trưa.', 'V る ＋ じかん／やくそく ＋ が あります / thể thông ようじ／おかね ありません。', 1, 6, TRUE, 1),
(108, 22, 'Chúng ta hãy cùng ～', 'Chúng ta hãy cùng ～', 'Chúng ta hãy cùng ～', 'Cách dùng: Ø Biểu thị đề nghị cả người nói và người nghe cùng làm một việc gì đó.', 'V ます → ましょうか。', 1, 7, TRUE, 1),
(109, 23, 'Khi/ lúc (trạng ngữ chỉ thời gian):', 'V る/ V ない / A い/ A な ＋とき', 'Khi/ lúc (trạng ngữ chỉ thời gian):', 'Chú ý: Ø Thời của mệnh đề bổ ngữ KHÔNG phụ thuộc vào thời của mệnh đề chính.', 'V る/ V ない / A い/ A な ＋とき / N の', 1, 1, TRUE, 1),
(110, 23, 'Trước khi/ sau khi:', 'V る / ＋とき', 'Trước khi/ sau khi:', 'Trước khi/ sau khi: Lưu ý: VD:', 'V る / 1. KHI/ LÚC (TRẠNG NGỮ CHỈ THỜI GIAN). / 3. HỄ/ CỨ LÀM V1 THÌ V2 TỰ DIỄN RA.', 1, 2, TRUE, 1),
(111, 23, 'Hễ/ cứ làm V1 thì V2 tự diễn ra:', 'Hễ/ cứ làm V1 thì V2 tự diễn ra:', 'Hễ/ cứ làm V1 thì V2 tự diễn ra:', 'Cách dùng: Ø Diễn tả một sự việc hiển nhiên, tự nhiên. Ø Dùng để hướng dẫn cách sử dụng máy móc, thiết bị. Ø Dùng để chỉ đường.', 'V１ると、 V２。 / はるになると、はなが さきます。 / V1 て、V2 て、V3 と、địa điểm にN があります。', 1, 3, TRUE, 1),
(112, 24, 'Cho, tặng hành động:', 'わたし', 'Cho, tặng hành động:', 'Ý nghĩa: A làm V cho B', 'A は B に N を V てあげます。 / わたし / わたしは おとうとに とけいを なおしてあげました。', 1, 1, TRUE, 1),
(113, 24, 'Nhận hành động:', 'Nhận hành động:', 'Nhận hành động:', 'Ý nghĩa: A được B làm V cho.', 'Nhận hành động: / A は B に N を V てもらいます。 / わたしは むすこに えを かいてもらいました。', 1, 2, TRUE, 1),
(114, 24, 'Cho, tặng (tôi):', 'Ø B thường là: 私 / わたし', 'Cho, tặng (tôi):', 'Cách dùng: Ø Ai đó cho, tặng mình (người thân) cái gì đó.', 'A は B に N を くれます。 / Ø B thường là: 私 / わたし', 1, 3, TRUE, 1),
(115, 24, 'Cho, tặng (tôi) hành động:', 'Cho, tặng (tôi) hành động:', 'Cho, tặng (tôi) hành động:', 'Ý nghĩa: A làm V cho B(tôi).', 'A は B に N を V てくれます。 / むすこは えを かいてくれました。', 1, 4, TRUE, 1),
(116, 24, 'Nhấn mạnh danh từ:', 'Nhấn mạnh danh từ:', 'Nhấn mạnh danh từ:', 'Mẹ đã nấu món ăn này cho tôi. Món ăn này là mẹ nấu cho tôi.', '5. Nhấn mạnh danh từ: / S は N を V ます。 / N は S が V ます。', 1, 5, TRUE, 1),
(117, 25, 'Câu điều kiện giả đinh: nếu…thì…:', 'A い → A かった / A な → A だった', 'Câu điều kiện giả đinh: nếu…thì…:', 'Cách dùng: Ø Dùng khi người nói muốn bày tỏ lập trường, ý kiến, mong muốn, yêu cầu, lời mời…của mình trong điều kiện giả định đó. của người nói.', 'A い → A かった / A な → A だった / （もし） N → N だった ら', 1, 1, TRUE, 1),
(118, 25, 'Sau khi làm V1 thì làm V2:', 'V1 たら、V2 / Ø Nhấn mạnh thứ tự trước sau của hành động.', 'Sau khi làm V1 thì làm V2:', 'Cách dùng: Ø Nhấn mạnh thứ tự trước sau của hành động. Ø V2 (mệnh đề chính) luôn ở thời hiện tại.', 'V1 たら、V2 / Ø Nhấn mạnh thứ tự trước sau của hành động. / (= V1 てから、V2)', 1, 2, TRUE, 1),
(119, 25, 'Câu mệnh đề ngược nghĩa: dù, cho dù… thì vẫn…:', 'A い → A くて / A な → A で', 'Câu mệnh đề ngược nghĩa: dù, cho dù… thì vẫn…:', 'Cách dùng: Ø Mệnh đề ngược nghĩa: Vế 1 có xảy ra như thế nào thì vế 2 vẫn sẽ xảy ra. Nhấn mạnh về mức độ điều kiện.', 'A い → A くて / A な → A で / （いくら）N → N で も', 1, 3, TRUE, 1)
ON DUPLICATE KEY UPDATE
    grammar_chapter_id = VALUES(grammar_chapter_id),
    title = VALUES(title),
    pattern = VALUES(pattern),
    meaning_vi = VALUES(meaning_vi),
    explanation = VALUES(explanation),
    formation = VALUES(formation),
    jlpt_level_id = VALUES(jlpt_level_id),
    display_order = VALUES(display_order),
    is_published = VALUES(is_published),
    version = VALUES(version);

INSERT INTO grammar_examples (id, grammar_lesson_id, japanese_text, reading, meaning_vi, display_order) VALUES
(1, 1, 'わたし は サムライです。', NULL, 'Tôi là Samurai.', 1),
(2, 1, 'わたし は きょうしです。', NULL, 'Tôi là giáo viên.', 2),
(3, 2, 'わたし は いしゃ じゃありません。', NULL, 'Tôi không phải là bác sĩ.', 1),
(4, 3, 'いいえ、がくせい じゃありません。', NULL, 'N N', 1),
(5, 3, 'おいくつですか。', NULL, '• Từ để hỏi:', 2),
(6, 4, 'サムライにほんご の がくせい。', NULL, 'Học viên của Samurai nihongo.', 1),
(7, 4, 'わたしは ハノイだいがくの がくせいです。', NULL, 'Tôi là học sinh của trường đại học Hà Nội.', 2),
(8, 5, '私もベトナム人です。', NULL, 'Tôi cũng là người Việt Nam.', 1),
(9, 6, 'これは とけいです。', NULL, 'Đây là đồng hồ.', 1),
(10, 6, 'それは じしょです。', NULL, 'Đó là quyển từ điển.', 2),
(11, 7, 'このひとは ミンさんです。', NULL, 'Người này là Minh Q：～', 1),
(12, 8, '教室に学生がいます。', NULL, 'Trong lớp có học sinh.', 1),
(13, 9, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: Là N1 hay là N2:.', 1),
(14, 10, 'これは わたしの チョコレートです。', NULL, 'Đây là sô cô la của tôi. • Cái này là N của ai? (đồ vật) • N này là của ai?', 1),
(15, 11, 'これは えいごの じしょです。', NULL, 'Đây là quyển từ điển tiếng Anh.', 1),
(16, 12, 'ここ は きょうしつ です。', NULL, 'Đây là phòng học.', 1),
(17, 12, 'こちら は わたしのかいしゃ です。', NULL, 'Đây là công ty của tôi. • Chỗ này/đó/kia không phải là N :', 2),
(18, 13, 'コンピューターは じむしょです。', NULL, 'Máy tính ở văn phòng.', 1),
(19, 14, 'トイレはどこですか。', NULL, 'Nhà vệ sinh ở đâu?', 1),
(20, 15, 'B: ベトナムです。', NULL, 'Tôi đến từ Việt Nam.', 1),
(21, 16, 'B：イギリスの でんわです。', NULL, 'Điện thoại này sản xuất ở Anh.', 1),
(22, 17, 'B： ～えん・ドル・ドンです。', NULL, 'Chiếc ô này bao nhiêu tiền?', 1),
(23, 17, 'B：にじゅうまんドンです。', NULL, 'Chiếc ô này có giá 200.000 đồng.', 2),
(24, 18, 'いま、ごぜん くじです。', NULL, 'Bây giờ là 9 giờ sáng. • Cách nói giờ kém:', 1),
(25, 18, 'まえです。', NULL, 'Cách dùng: ➢ Nói trong phạm vi 10 phút trở về. ➢ Cách nói giờ hơn thì nói như bình thường', 2),
(26, 19, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: Là thứ mấy?:.', 1),
(27, 20, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: Động từ ます:.', 1),
(28, 21, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: Làm V vào lúc ～ giờ：.', 1),
(29, 22, 'あした いちじから ごじまで べんきょうします。', NULL, 'Ngày mai tôi học từ 1 giờ đến 5 giờ.', 1),
(30, 23, 'このびじゅつかんは きんようびと どようび やすみます。', NULL, 'Bảo tàng mĩ thuật này nghỉ vào thứ 6 và thứ 7.', 1),
(31, 24, 'きょうは しがつ ついたちです。', NULL, 'Hôm nay là ngày mùng 1 tháng 4.', 1),
(32, 25, 'わたしは にほんへ きました。', NULL, 'Tôi đã đến Nhật.', 1),
(33, 26, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: Hỏi đi/ đến/ về đâu?:.', 1),
(34, 27, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: Bằng phương tiện gì 「で」：.', 1),
(35, 28, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: Làm gì với ai đó 「と」：.', 1),
(36, 29, 'けさ パンを たべました。', NULL, 'Sáng nay tôi đã ăn bánh mì. Chú ý: • Ăn, uống, làm… cái gì? Q:', 1),
(37, 29, 'おとうさん、なにを のみますか。', NULL, 'A:', 2),
(38, 30, 'しゅうまつ テニスを します。', NULL, 'Cuối tuần tớ sẽ chơi tennis. • Làm (đã làm) gì? Cách dùng: ➢ Đây là mẫu câu hỏi chung cho tất cả các động từ. ➢ Nếu không làm gì thì sẽ trả lời:', 1),
(39, 31, 'トイレはどこですか。', NULL, 'Nhà vệ sinh ở đâu?', 1),
(40, 32, 'この料理はおいしいですが、高いです。', NULL, 'Món này ngon nhưng đắt.', 1),
(41, 33, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: Cùng làm ～nhé：.', 1),
(42, 34, 'はさみで かみを きります。', NULL, 'Cắt giấy bằng kéo. • Làm V bằng phương tiện, công cụ nào?', 1),
(43, 34, 'Ｑ： Ｓは なにで Ｎを Ｖますか。', NULL, 'ĐỂ THỰC HIỆN V. Q:', 2),
(44, 35, 'は えいごで “Book”です。', NULL, 'Sách trong tiếng Anh là “book”. • A trong ngôn ngữ ~ là gì?', 1),
(45, 35, 'Ａは ～ごで なんですか。', NULL, 'Cái này tiếng Nhật là gì?', 2),
(46, 36, 'わたしは ちちに えを あげます。', NULL, 'Tôi tặng bố bức tranh. người nhận người cho V nhận Ý nghĩa: ➢ A nhận từ B 1 N nào đó. ➢ V nhận:', 1),
(47, 36, '✓ ならいます (học từ)', NULL, 'Bố nhận từ tôi bức tranh. Lưu ý: Trong câu nhận: ➢ Nếu đối tượng B (người cho) là một tổ chức , cơ quan thì • Ai cho/ nhận của ai N:', 2),
(48, 37, 'わたしは もう あさごはんを たべました。', NULL, 'Tôi đã ăn sáng rồi. • Đã làm V chưa?', 1),
(49, 38, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: Tính từ:.', 1),
(50, 39, '桜はきれいです。', NULL, 'Hoa anh đào đẹp.', 1),
(51, 40, 'ホアさんは げんき じゃありません。', NULL, 'Bạn Hoa không khỏe. • ∼phải không?', 1),
(52, 41, 'これは新しい本です。', NULL, 'Đây là quyển sách mới.', 1),
(53, 42, 'ナムさんは ハンサムです。そして、しんせつです。', NULL, 'Nam thì đẹp trai và tốt bụng.', 1),
(54, 43, 'この料理はおいしいですが、高いです。', NULL, 'Món này ngon nhưng đắt.', 1),
(55, 44, '日本の生活はどうですか。', NULL, 'Cuộc sống ở Nhật thế nào?', 1),
(56, 45, 'あなたのかばんはどれですか。', NULL, 'Cái cặp của bạn là cái nào?', 1),
(57, 46, 'いいえ、すき/きらい じゃありません。', NULL, 'Lưu ý: Cậu thích xem phim không? Không, tớ không thích xem phim lắm.', 1),
(58, 47, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: Giỏi, kém ∼:.', 1),
(59, 48, 'わたしは にほんご が わかります。', NULL, 'Tôi hiểu tiếng Nhật. • Biết, không biết ∼ không?', 1),
(60, 48, 'いいえ、わかりません。', NULL, 'Cậu biết tiếng Đức không? Có, tôi biết.', 2),
(61, 49, 'ナムさんは きれいな くるまが あります。', NULL, 'Nam có xe ô tô đẹp. • Có ∼ không?:', 1),
(62, 49, 'いいえ、ありません。', NULL, 'Bạn có thời gian không? Không, tôi không có.', 2),
(63, 50, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: Phó từ chỉ mức độ:.', 1),
(64, 51, '日本の生活はどうですか。', NULL, 'Cuộc sống ở Nhật thế nào?', 1),
(65, 52, 'じかんが ありませんから、スポーツを しません。', NULL, 'Vì không có thời gian nên không chơi thể thao.', 1),
(66, 53, '忙しいですから、朝ご飯を食べません。', NULL, 'Vì bận nên tôi không ăn sáng.', 1),
(67, 54, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: Cách nói vị trí cụ thể:.', 1),
(68, 55, 'マイさんは にほんごの じしょが あります。', NULL, 'Chị Mai có quyển từ điển tiếng Nhật. Tôi có con mèo màu trắng. Ở địa điểm ～ có cái gì? Ở địa điểm ～ có con gì? Ở địa điểm ～ có ai? Cách phủ định hoàn toàn:', 1),
(69, 55, 'はこの なかに なにが ありますか。', NULL, 'Ở trong hộp có cái gì đó ?', 2),
(70, 56, 'やさいと くだものは れいぞうこに あります。', NULL, 'Rau và hoa quả thì có ở trong tủ lạnh. • N (đồ vật) có ở đâu? • N (người, con vật) có ở đâu? Công viên thì có ở đâu ? Có ở phía sau trường học.', 1),
(71, 57, '日曜日は映画を見たり、本を読んだりします。', NULL, 'Chủ nhật tôi xem phim, đọc sách...', 1),
(72, 58, 'がっこうに にほんじんの せんせいが ひとりいます。', NULL, 'Ở trường có 1 giáo viên người Nhật.', 1),
(73, 58, 'ごはんを ２はい 食べます。', NULL, 'Tôi ăn 2 bát cơm.', 2),
(74, 59, 'を べんきょうしました。', NULL, 'Tôi đã học tiếng Nhật trong khoảng 2 tháng. Làm V trong khoảng bao lâu? Trưa hôm qua cậu đã ngủ bao lâu. Tớ đã ngủ khoảng 2 tiếng.', 1),
(75, 60, 'わたしは いちにちに ３かい ごはんを たべます。', NULL, '1 ngày tôi ăn cơm 3 lần. • Làm V bao nhiêu lần trong khoảng thời gian N: (khoảng thời gian)', 1),
(76, 60, '１しゅうかんに なんかい スーパーへ いきますか。', NULL, '1 tuần đi siêu thị mấy lần ?', 2),
(77, 61, 'にく だけ たべます 。', NULL, 'Tôi chỉ ăn thịt.', 1),
(78, 62, 'おもしろかったです。', NULL, 'Thú vị lắm.', 1),
(79, 63, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: N1 hơn N2:.', 1),
(80, 64, 'あなたのかばんはどれですか。', NULL, 'Cái cặp của bạn là cái nào?', 1),
(81, 65, 'クラスのなかで ナムさんが いちばん ハンサムです。', NULL, 'Trong lớp thì Nam đẹp trai nhất. • Trong N1 thì cái gì/ai/khi nào/ở đâu là ~ nhất?', 1),
(82, 65, 'いちねんでいつがいちばんすずしいですか。', NULL, 'Trong 1 năm thì khi nào là mát mẻ nhất?', 2),
(83, 66, 'Ｑ： どんなＮが ほしいですか。', NULL, 'Bạn thích 1 chiếc túi xách như thế nào? Tôi thích 1 chiếc túi xách màu vàng.', 1),
(84, 67, 'こいびと と さんぽしたいです。', NULL, 'Muốn đi dạo cùng người yêu . Chú ý: mong muốn của ngôi thứ 3.', 1),
(85, 67, 'たなかさんは やきゅうを したがっています。', NULL, 'Anh Tanaka muốn chơi bóng chày. • Có muốn làm V không? Bạn có muốn chụp ảnh không? Có, tôi muốn chụp ảnh. • Muốn làm gì? Chú ý: Tùy vào động từ sẽ có nghi vấn từ khác nhau', 2),
(86, 68, 'スーパーへ やさいを かいに いきます。', NULL, 'Tôi đi siêu thị để mua rau. • Đi/ đến/ về đâu để làm V: Hôm qua, bạn đi đâu để làm gì? Tôi đi quán cà phê để uống cà phê. • Đi đến đâu để học cái gì?', 1),
(87, 68, 'いきますか。', NULL, 'Cậu đến Mỹ để học gì? Tôi học tiếng Anh.', 2),
(88, 69, 'はたらきます(làm việc) あそびます(chơi)', NULL, '• Động từ nhóm II: thuộc cột e.', 1),
(89, 69, 'あげます(cho) むかえます(đón)', NULL, 'là cột i vẫn được gọi là động từ nhóm 2.', 2),
(90, 70, 'まちます(chờ) ⇒ まって', NULL, 'Ø Cách chia 2:', 1),
(91, 70, 'やすみます(nghỉ ngơi) ⇒ やすんで', NULL, 'Ø Cách chia 3:', 2),
(92, 71, 'すみませんが、タクシー を よんで ください。', NULL, 'Xin lỗi, hãy gọi taxi giúp tôi.', 1),
(93, 72, 'いま、ナムさんは プールで およいで います。', NULL, 'Bây giờ anh Nam đang bơi ở trong bể bơi. • Bây giờ ～ đang ～ phải không? Bé Na đang đọc sách phải không? Ừ, bé Na đang đọc sách. • Bây giờ bạn đang làm gì?', 1),
(94, 72, 'は なにをして いますか。', NULL, 'Bây giờ thầy Minh đang làm gì thế? Thầy đang dạy tiếng Nhật.', 2),
(95, 73, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: Để tôi làm ～ giúp bạn nhé：.', 1),
(96, 74, 'すみません、ちょっと…(きんえんですから）', NULL, 'Xin lỗi, không được….(vì bị cấm)', 1),
(97, 75, 'すわっちゃだめです。', NULL, 'Không được ngồi. • Làm V được không? Tôi đặt ở đây được không?', 1),
(98, 75, 'いいえ、 おいてはいけません。', NULL, 'Không, không được đặt.', 2),
(99, 76, 'に すんでいます。', NULL, 'Tôi đang sống ở Nhật. Chú ý:', 1),
(100, 76, 'を しっていますか。', NULL, 'Có biết sinh nhật của thầy giáo không?', 2),
(101, 77, 'ともだちと ビールを のみに いきました。', NULL, 'Hôm qua tôi làm xong việc, đi rút tiền, rồi đi uống bia với bạn.', 1),
(102, 78, 'でんわを かけてから、ともだちの うちに いきます。', NULL, 'Sau khi gọi điện thoại xong thì tôi đi đến nhà bạn.', 1),
(103, 79, 'ナムさんは ハンサムで あたまがいいです。', NULL, 'Nam thì đẹp trai và thông minh.', 1),
(104, 80, 'にほんは すしが おいしいです。', NULL, 'Sushi của Nhật Bản ngon.', 1),
(105, 81, '日本の生活はどうですか。', NULL, 'Cuộc sống ở Nhật thế nào?', 1),
(106, 82, 'でんわを かけてから、ともだちの うちに いきます。', NULL, 'Sau khi gọi điện thoại xong thì tôi đi đến nhà bạn. Cách nối tính từ và danh từ: Cách dùng: Ø Dùng để nối 2 hay nhiều tính từ, danh từ với nhau. Ø Vì mang ý nghĩa “và” nên KHÔNG dùng để nối 2 câu có ý nghĩa trái ngược nhau.', 1),
(107, 82, 'ナムさんは ハンサムで あたまがいいです。', NULL, 'Nam thì đẹp trai và thông minh. N2 (của) N1 thì: Cách dùng: Ø Dùng để miêu tả đặc điểm, tính chất của N1. Ø N2 là thuộc tính, thành phần của N1.', 2),
(108, 83, 'ここで写真を撮らないでください。', NULL, 'Xin đừng chụp ảnh ở đây.', 1),
(109, 84, 'べんきょうしないとだめです。', NULL, 'Phải học.', 1),
(110, 85, 'おかねを はらわなくてもいいです。', NULL, 'Không cần trả tiền cũng được.', 1),
(111, 86, 'までに、レポートを ださなければなりません。', NULL, 'Cho đến thứ 6 phải nộp báo cáo.', 1),
(112, 87, 'ここに くるまを とめないでください。', NULL, 'Xin đừng đỗ xe ở đây.', 1),
(113, 87, 'くるまは ここに とめないでください。', NULL, 'Xe ô tô thì xin đừng đỗ ở đây.', 2),
(114, 88, '机の上に本があります。', NULL, 'Trên bàn có sách.', 1),
(115, 89, 'しゅみは なんですか。', NULL, 'Q:', 1),
(116, 89, 'しゅみは なんですか。', NULL, 'Sở thích của bạn là gì? Sở thích của tôi là thể thao.', 2),
(117, 90, 'ねる まえに、けいたいでんわを みます。', NULL, 'Trước khi ngủ tôi xem điện thoại.', 1),
(118, 90, 'かいぎの まえに、しりょうを コピーします。', NULL, 'Trước khi diễn ra cuộc họp tôi copy tài liệu. • Cách đây, trước đây (trường hợp của lượng từ (thời gian)):', 2),
(119, 91, 'が なかなかじょうずになりません。', NULL, 'Tôi mãi mà không trở nên giỏi tiếng Nhật được.', 1),
(120, 92, 'ぜひ、ふじさんに のぼりたいです。', NULL, 'Tôi rất muốn leo núi Phú Sĩ.', 1),
(121, 93, 'いっかい', NULL, 'Tôi đã từng cưỡi ngựa. • Đã từng ～ chưa?：', 1),
(122, 93, 'いいえ、いちども ありません。', NULL, 'Bạn đã từng leo núi Phú Sĩ chưa.', 2),
(123, 94, 'たり します。', NULL, 'Chủ nhật tôi sẽ đọc sách, xem ti vi. • Bạn làm gì?', 1),
(124, 94, 'は なにをしますか。', NULL, 'Kì nghỉ bạn làm gì? Tôi trượt tuyết, đi tiệc với bạn.', 2),
(125, 95, 'くらく なります。', NULL, 'Trời trở nên tối. • Ước mơ làm nghề gì: Tương lai bạn muốn làm gì? Tôi muốn trở thành kỹ sư.', 1),
(126, 96, '⇒ まいにち6 じにおきる。', NULL, 'Mỗi ngày tôi thức dậy lúc 6 giờ. • Dạng câu hỏi của động từ： cuối câu. Khi trả lời ở dạng câu hỏi có hoặc không: Em đã ăn sáng chưa? Chưa, em chưa ăn. Lưu ý: Ø Trong cách nói thông thường, ta thuờng lược bỏ cả những trợ từ khi câu văn đã rõ nghĩa. lược bỏ. Bạn đã ăn cơm chưa? Rồi, tôi ăn rồi. THỂ LỊCH SỰ THỂ THÔNG THƯỜNG', 1),
(127, 96, '⇒ きょうはさむいね。', NULL, 'Hôm nay lạnh nhỉ. cuối câu. Cái máy tính đó mới phải không mẹ? Không, máy cũ mà. THỂ LỊCH SỰ THỂ THÔNG THƯỜNG', 2),
(128, 97, 'この料理はおいしいですが、高いです。', NULL, 'Món này ngon nhưng đắt.', 1),
(129, 98, '明日は雨が降ると思います。', NULL, 'Tôi nghĩ ngày mai trời sẽ mưa.', 1),
(130, 99, 'ねる まえに、「おやすみなさい」といいます。', NULL, '• Trích dẫn lời nói của người khác. Ø Trích dẫn lời nói trực tiếp:', 1),
(131, 99, 'します」といいました。', NULL, 'Hoa đã nói là “ Tháng sau sẽ kết hôn”. Ø Trích dẫn lời nói gián tiếp:', 2),
(132, 100, 'かれは ハンサムでしょう。', NULL, 'Anh ấy đẹp trai đúng không?', 1),
(133, 101, 'しあいが あります。', NULL, 'Ở Hà Nội có trận bóng đá giữa Việt Nam và Thái Lan. • 1 sự việc diễn ra ở 1 tình huống nào đó:', 1),
(134, 101, 'かぎで いけんを いいました。', NULL, 'Tôi đã nói lên ý kiến trong cuộc họp.', 2),
(135, 102, 'もの ひと ところ', NULL, 'Ø Tính từ bổ nghĩa cho danh từ: Hoa đẹp. • Mệnh đề bổ nghĩa cho danh từ bằng động từ hoặc 1 câu có động từ: V(thể thông thường) + N Cái bánh mẹ tôi làm.', 1),
(136, 103, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: Mệnh đề bổ ngữ cho danh từ là vị ngữ:.', 1),
(137, 104, 'めがねを かけている 人 はマイさんです。', NULL, 'Người mà đang đeo kính là chị Mai.', 1),
(138, 105, '私は学生です。', NULL, 'Tôi là học sinh.', 1),
(139, 106, 'ユーモアが あるひと がすきです。', NULL, 'Tôi thích người mà có tính hài hước.', 1),
(140, 107, '机の上に本があります。', NULL, 'Trên bàn có sách.', 1),
(141, 108, '名前を書いてください。', NULL, 'Hãy viết tên.', 1),
(142, 109, '暇なとき、本を読みます。', NULL, 'Khi rảnh tôi đọc sách.', 1),
(143, 110, 'ご飯を食べてから、勉強します。', NULL, 'Sau khi ăn cơm, tôi học.', 1),
(144, 111, 'はるになると、はなが さきます。', NULL, 'Cứ xuân sang thì hoa sẽ nở. • Cách chỉ đường liên tiếp:', 1),
(145, 111, 'に びょういんが あります。', NULL, 'Cứ đi thẳng, qua cầu, rẽ phải thì sẽ có bệnh viện ở bên trái.', 2),
(146, 112, 'わたしは おとうとに とけいを なおしてあげました。', NULL, 'Tôi đã sửa đồng hồ cho em trai.', 1),
(147, 113, 'わたしは むすこに えを かいてもらいました。', NULL, 'Tôi được con trai vẽ tranh cho.', 1),
(148, 114, 'けさ ははは「わたしに」おかねを くれました。', NULL, 'Sáng nay mẹ đã cho tôi tiền.', 1),
(149, 115, 'むすこは えを かいてくれました。', NULL, 'Con trai đã vẽ tranh cho tôi.', 1),
(150, 116, 'このりょうり は ははが つくってくれました。', NULL, 'Món ăn này là mẹ nấu cho tôi.', 1),
(151, 117, '雨が降ったら、行きません。', NULL, 'Nếu trời mưa thì tôi không đi.', 1),
(152, 118, 'ご飯を食べてから、勉強します。', NULL, 'Sau khi ăn cơm, tôi học.', 1),
(153, 119, 'あめが ふっても、ジョギングを します。', NULL, 'Dù mưa thì vẫn chạy bộ.', 1)
ON DUPLICATE KEY UPDATE
    grammar_lesson_id = VALUES(grammar_lesson_id),
    japanese_text = VALUES(japanese_text),
    reading = VALUES(reading),
    meaning_vi = VALUES(meaning_vi),
    display_order = VALUES(display_order);
