SET NAMES utf8mb4;

DELETE ge FROM grammar_examples ge JOIN grammar_lessons gl ON gl.id = ge.grammar_lesson_id WHERE gl.jlpt_level_id = 2;

DELETE FROM grammar_lessons WHERE jlpt_level_id = 2;

DELETE FROM grammar_chapters WHERE jlpt_level_id = 2;

INSERT INTO grammar_chapters (id, jlpt_level_id, chapter_number, name, description, display_order, is_published, version) VALUES
(26, 2, 26, 'Bài 26', 'Ngữ pháp N4 - Bài 26', 26, TRUE, 1),
(27, 2, 27, 'Bài 27', 'Ngữ pháp N4 - Bài 27', 27, TRUE, 1),
(28, 2, 28, 'Bài 28', 'Ngữ pháp N4 - Bài 28', 28, TRUE, 1),
(29, 2, 29, 'Bài 29', 'Ngữ pháp N4 - Bài 29', 29, TRUE, 1),
(30, 2, 30, 'Bài 30', 'Ngữ pháp N4 - Bài 30', 30, TRUE, 1),
(31, 2, 31, 'Bài 31', 'Ngữ pháp N4 - Bài 31', 31, TRUE, 1),
(32, 2, 32, 'Bài 32', 'Ngữ pháp N4 - Bài 32', 32, TRUE, 1),
(33, 2, 33, 'Bài 33', 'Ngữ pháp N4 - Bài 33', 33, TRUE, 1),
(34, 2, 34, 'Bài 34', 'Ngữ pháp N4 - Bài 34', 34, TRUE, 1),
(35, 2, 35, 'Bài 35', 'Ngữ pháp N4 - Bài 35', 35, TRUE, 1),
(36, 2, 36, 'Bài 36', 'Ngữ pháp N4 - Bài 36', 36, TRUE, 1),
(37, 2, 37, 'Bài 37', 'Ngữ pháp N4 - Bài 37', 37, TRUE, 1),
(38, 2, 38, 'Bài 38', 'Ngữ pháp N4 - Bài 38', 38, TRUE, 1),
(39, 2, 39, 'Bài 39', 'Ngữ pháp N4 - Bài 39', 39, TRUE, 1),
(40, 2, 40, 'Bài 40', 'Ngữ pháp N4 - Bài 40', 40, TRUE, 1),
(41, 2, 41, 'Bài 41', 'Ngữ pháp N4 - Bài 41', 41, TRUE, 1),
(42, 2, 42, 'Bài 42', 'Ngữ pháp N4 - Bài 42', 42, TRUE, 1),
(43, 2, 43, 'Bài 43', 'Ngữ pháp N4 - Bài 43', 43, TRUE, 1),
(44, 2, 44, 'Bài 44', 'Ngữ pháp N4 - Bài 44', 44, TRUE, 1),
(45, 2, 45, 'Bài 45', 'Ngữ pháp N4 - Bài 45', 45, TRUE, 1),
(46, 2, 46, 'Bài 46', 'Ngữ pháp N4 - Bài 46', 46, TRUE, 1),
(47, 2, 47, 'Bài 47', 'Ngữ pháp N4 - Bài 47', 47, TRUE, 1),
(48, 2, 48, 'Bài 48', 'Ngữ pháp N4 - Bài 48', 48, TRUE, 1),
(49, 2, 49, 'Bài 49', 'Ngữ pháp N4 - Bài 49', 49, TRUE, 1),
(50, 2, 50, 'Bài 50', 'Ngữ pháp N4 - Bài 50', 50, TRUE, 1)
ON DUPLICATE KEY UPDATE
    jlpt_level_id = VALUES(jlpt_level_id),
    chapter_number = VALUES(chapter_number),
    name = VALUES(name),
    description = VALUES(description),
    display_order = VALUES(display_order),
    is_published = VALUES(is_published),
    version = VALUES(version);

INSERT INTO grammar_lessons (id, grammar_chapter_id, title, pattern, meaning_vi, explanation, formation, jlpt_level_id, display_order, is_published, version) VALUES
(120, 26, '～んです', 'V 普通形 / A い ＋ い', '～んです', '(thể thường)', '1. ～んです / 2. ～んですか / 3. V ていただけませんか', 2, 1, TRUE, 1),
(121, 26, '～んです', '～んですか', '～んです', 'Ly hôm nay vui nhỉ. Bạn có người yêu à? ❖ Người nói muốn được cung cấp thêm thông tin về những gì mình đã nhìn hoặc nghe thấy.', '2. ～んです / ～んですか / ひまじゃ', 2, 2, TRUE, 1),
(122, 26, 'V ていただけませんか', '～V ていただけませんか / ❖ So với V てください thì cách nói này lịch sự hơn.', 'V ていただけませんか', 'Bạn copy tài liệu đó giúp tôi được không?', '3. V ていただけませんか / ～V ていただけませんか / ❖ So với V てください thì cách nói này lịch sự hơn.', 2, 3, TRUE, 1),
(123, 26, '～んですが', '～んですが、～ / ❖ が: dùng để nối các vế câu lại với nhau biểu hiện', '～んですが', 'Câu hỏi này tôi vẫn chưa hiểu. Bạn chỉ cho tôi thêm 1 lần nữa được không?', '4. ～んですが / ～んですが、～ / ❖ が: dùng để nối các vế câu lại với nhau biểu hiện', 2, 4, TRUE, 1),
(124, 26, '疑問詞＋V たらいいですか (từ để hỏi)', '疑問詞＋V たらいいですか (từ để hỏi)', '疑問詞＋V たらいいですか (từ để hỏi)', '❖ Dùng khi muốn nghe sự khuyên bảo, hướng dẫn mình nên làm gì. ❖ Từ để hỏi:', '5. 疑問詞＋V たらいいですか (từ để hỏi) / Q: Từ để hỏi ＋ V たらいいですか。 / A: V たら いいです。', 2, 5, TRUE, 1),
(125, 26, 'N (tân ngữ) はすきです', 'N (tân ngữ) はすきです', 'N (tân ngữ) はすきです', 'Tarou ơi, ăn rau đi con. Không, con ghét rau.', '6. N (tân ngữ) はすきです / すきです／きらいです。 / N (tân ngữ) は じょうずです／へたです。', 2, 6, TRUE, 1),
(126, 27, '可能形 (かのうけい)', 'Hàng い(i) / ～(i)ます→～(e)ます', '可能形 (かのうけい)', 'Cách dùng thể khả năng: ❖ Chú ý :', '1. 可能形 (かのうけい) / 2. 見えます・聞こえます / 3. 場所に N ができます', 2, 1, TRUE, 1),
(127, 27, '見えます・聞こえます', '❖ 見 / み', '見えます・聞こえます', 'Từ đây có thể nhìn thấy biển. CHỦ QUAN KHÁCH QUAN PHÂN BIỆT Đeo kính thì nhìn thấy chữ.', '2. 見えます・聞こえます / ❖ 見 / み', 2, 2, TRUE, 1),
(128, 27, '場所 (địa điểm) にN が できます', 'Địa điểm に N が できます', '場所 (địa điểm) にN が できます', 'Trước nhà ga có siêu thị đã được xây xong.', '3. 場所 (địa điểm) にN が できます / Địa điểm に N が できます', 2, 3, TRUE, 1),
(129, 27, 'N(lượng từ)しかＶません', '❖ Ý Nghĩa: Chỉ ~ / ❖ Dù đuôi là ません nhưng là câu khẳng định', 'N(lượng từ)しかＶません', 'Tôi chỉ nói được tiếng Nhật.', '4. N(lượng từ)しかＶません / ❖ Ý Nghĩa: Chỉ ~ / ❖ Dù đuôi là ません nhưng là câu khẳng định', 2, 4, TRUE, 1),
(130, 27, 'N1 は～が、N2 は～', 'N1 は～が、N2 は～ / ❖ Ý Nghĩa: So sánh đối lập 2 vế của câu', 'N1 は～が、N2 は～', 'Tôi thì có thể viết Hiragana nhưng, kanji thì không thể viết.', '5. N1 は～が、N2 は～ / N1 は～が、N2 は～ / ❖ Ý Nghĩa: So sánh đối lập 2 vế của câu', 2, 5, TRUE, 1),
(131, 28, 'ながら', 'ながら', 'ながら', 'Bố tôi vừa uống bia vừa làm việc. Maria vừa đi làm vừa học đại học. ❖ Với các động từ khoảnh khắc (thức dậy, mặc, đội mũ, ❖ Với các động từ di chuyển thì sẽ đặt ở vế sau nhắm vào hành động nào thì hành động đó nằm ở vế sau kết hợp với các dạng này.', '1. ながら / 2. V ています / 3. ～し、～し、それに', 2, 1, TRUE, 1),
(132, 28, 'V ています', 'V ています / ❖ Nếu diễn tả thói quen trong quá khứ thì dung:', 'V ています', 'Ngày nghỉ tôi thường chơi tennis với bạn bè.', '2. V ています / V ています / ❖ Nếu diễn tả thói quen trong quá khứ thì dung:', 2, 2, TRUE, 1),
(133, 28, '～し、～し、それに', '❖ Trợ từ が được chuyển thành も để nhấn mạnh quan điểm. / ❖ それに：hơn nữa, thêm vào đó', '～し、～し、それに', 'Hà Nội vừa náo nhiệt, vừa có phong cảnh đẹp, Hơn nữa lại có nhiều đồ ăn ngon.', '3. ～し、～し、それに / ❖ Trợ từ が được chuyển thành も để nhấn mạnh quan điểm. / ❖ それに：hơn nữa, thêm vào đó', 2, 3, TRUE, 1),
(134, 28, '～し、～し、（それで）', '❖ Ở mẫu câu này phần ～し、～し được dùng để trình bày lý / ❖ それで： vì vậy, vì thế', '～し、～し、（それで）', 'Công việc vừa thú vị, lương cao, vì vậy tôi muốn làm việc ở công ty này.', '4. ～し、～し、（それで） / ❖ Ở mẫu câu này phần ～し、～し được dùng để trình bày lý / ❖ それで： vì vậy, vì thế', 2, 4, TRUE, 1),
(135, 28, '～し、～ から', '＋ し 、～し、（それで）～ / V（普通形）(thể thông thường)', '～し、～ から', 'trình bày lý do cho phần nội dung nói đến phía sau đó. nguyên nhân – lý do, dẫn đến kết quả – kết luận ở', '5. ～し、～ から / ＋ し 、～し、（それで）～ / V（普通形）(thể thông thường)', 2, 5, TRUE, 1),
(136, 29, '(もう／ぜんぶ) +', 'V てしまいます', '(もう／ぜんぶ) +', 'Mẫu ngữ pháp N4: (もう／ぜんぶ) +.', '1.(もう／ぜんぶ) + / V てしまいます', 2, 1, TRUE, 1),
(137, 29, '(もう／ぜんぶ) +', '(もう／ぜんぶ) +', '(もう／ぜんぶ) +', 'Tôi sẽ lau xong toàn bộ bàn của cửa hàng. ❖ Diễn tả hối hận, tiếc nuối về một việc đã xảy ra (chỉ dùng dạng quá khứ)', '２.(もう／ぜんぶ) + / みせ / の机', 2, 2, TRUE, 1),
(138, 29, '(もう／ぜんぶ) +', '(もう／ぜんぶ) +', '(もう／ぜんぶ) +', 'Mẫu ngữ pháp N4: (もう／ぜんぶ) +.', '(もう／ぜんぶ) +', 2, 3, TRUE, 1),
(139, 29, 'N(nơi chốn) に行きます／来ます／帰ります', 'N(nơi chốn) に行きます／来ます／帰ります / Những động từ như 行きます／来ます／帰ります', 'N(nơi chốn) に行きます／来ます／帰ります', 'Phân biệt triệt để toàn bộ 100% hay chưa. VD:', '4. N(nơi chốn) に行きます／来ます／帰ります / N(nơi chốn) に行きます／来ます／帰ります / Những động từ như 行きます／来ます／帰ります', 2, 4, TRUE, 1),
(140, 29, 'それ／その／そう', 'それ／その／そう', 'それ／その／そう', 'Từ tháng sau, tôi sẽ chuyển việc về công ty mẹ ở Osaka Xin chúc mừng anh/chị về điều đó Đi đến nhà ga Đến trường Trở về nhà', '5. それ／その／そう / A: 来月 / らいげつ', 2, 5, TRUE, 1),
(141, 29, 'ありました', '❖ Trong câu trên ［かばんが］ biểu thị rằng người', 'ありました', 'Lấy cho tôi tài liệu ở trên bàn. Vâng, nó không có ở đây. A, nó ở bên cạnh cái máy tính.', '6. ありました / ❖ Trong câu trên ［かばんが］ biểu thị rằng người / A: 机', 2, 6, TRUE, 1),
(142, 29, 'どこかで／どこかに', '❖ どこかで ：Diễn tả nơi diễn ra , xảy ra hành động', 'どこかで／どこかに', 'Tôi lỡ đánh rơi mất ví ở đâu đó rồi.', '7. どこかで／どこかに / ❖ どこかで ：Diễn tả nơi diễn ra , xảy ra hành động / さいふ', 2, 7, TRUE, 1),
(143, 30, 'Chuẩn bị', 'Chuẩn bị', 'Chuẩn bị', 'Mẫu ngữ pháp N4: Chuẩn bị.', 'Chuẩn bị', 2, 1, TRUE, 1),
(144, 30, 'Thực hiện hành động ĐỂ LẦN SAU CÒN DÙNG LẠI,', 'hoặc ĐƯA VỀ TRẠNG THÁI BAN ĐẦU (rửa bát, để', 'Thực hiện hành động ĐỂ LẦN SAU CÒN DÙNG LẠI,', 'Trước giờ học, tôi chuẩn bị trước bài mới. Ví dụ V Tự động từ Tha động từ Ý nghĩa Chỉ diễn tả trạng thái của cửa sổ đang đóng. Diễn tả trạng thái cửa sổ đóng là kết quả có chủ ý của 1 ai đó. Sau khi ăn cơm xong, tôi rửa bát. Tôi tắt điều hòa nhé? Trời nóng nên bạn cứ bật điều hòa như thế nhé.', '2. Thực hiện hành động ĐỂ LẦN SAU CÒN DÙNG LẠI, / hoặc ĐƯA VỀ TRẠNG THÁI BAN ĐẦU (rửa bát, để / 授業', 2, 2, TRUE, 1),
(145, 30, 'また', 'また', 'また', 'Trời vẫn còn đang mưa. ❖ Ý nghĩa : Vẫn chưa…( Diễn tả trạng thái hành động đang diễn ra và chưa xong)', '3. また / あめ / が まだ ふっています。', 2, 3, TRUE, 1),
(146, 30, 'とか', '「とか」và「や」đều được dùng khi liệt kê ví dụ.', 'とか', 'B: À vâng, tôi chơi mấy môn như là quần vợt, bơi lội,... Kết hợp với N Kết hợp với V × Trường hợp sử dụng Văn viết Văn nói', '4. とか / 「とか」và「や」đều được dùng khi liệt kê ví dụ. / A: Anh thường chơi môn thể thao gì?', 2, 4, TRUE, 1),
(147, 30, '格助詞(trợ từ cách) + も', 'Trợ từ も khi kết hợp với danh từ có các trợ từ「が」, / 「を」đi kèm thì các trợ từ 「が」,「を」 sẽ được', '格助詞(trợ từ cách) + も', 'Ngày nghỉ tôi chẳng đi đâu cả.', '5. 格助詞(trợ từ cách) + も / Trợ từ も khi kết hợp với danh từ có các trợ từ「が」, / 「を」đi kèm thì các trợ từ 「が」,「を」 sẽ được', 2, 5, TRUE, 1),
(148, 31, '意向形', 'あいます / あおう', '意向形', 'Nhóm I Nhóm II V D:', '1. 意向形 / 2. ～と思っています / 3. まだ～V ていません', 2, 1, TRUE, 1),
(149, 31, '～ (よう）と思', 'おも / っています', '～ (よう）と思', 'Tôi đang định đi xem phim vào tuần sau.', '2. ～ (よう）と思 / おも / っています', 2, 2, TRUE, 1),
(150, 31, 'まだ～V ていません', '(終わっていません、できていません）', 'まだ～V ていません', 'Tôi vẫn chưa tìm thấy cái túi xách màu trắng của mẹ tôi.', '3. まだ～V ていません / (終わっていません、できていません） / はは', 2, 3, TRUE, 1),
(151, 31, '～つもりです', '❖ 「V るつもりです」: diễn đạt ý định làm 1 việc gì đó / ＋ つもりです', '～つもりです', 'Tôi sẽ không chơi game từ thứ 2 đến thứ 6.', '4. ～つもりです / ❖ 「V るつもりです」: diễn đạt ý định làm 1 việc gì đó / ＋ つもりです', 2, 4, TRUE, 1),
(152, 31, '～予定', 'よてい / です', '～予定', 'Tháng 1 năm sau tôi kế hoạch sẽ kết hôn với người yêu.', '5. ～予定 / よてい / です', 2, 5, TRUE, 1),
(153, 32, 'V た・Ｖない ほうがいいです', 'S は / ほうがいいです', 'V た・Ｖない ほうがいいです', 'Mẫu ngữ pháp N4: V た・Ｖない ほうがいいです.', '1. V た・Ｖない ほうがいいです / 2. ～でしょう / 3. ～かもしれません', 2, 1, TRUE, 1),
(154, 32, '～でしょう', '～でしょう', '～でしょう', 'Cuối tuần có lẽ bão sẽ đến.', '2. ～でしょう / きっと、たぶん、。。。 / しゅうまつ', 2, 2, TRUE, 1),
(155, 32, '～かも しれません', 'V（普通形） / A な/N（普通形）だ', '～かも しれません', 'Lạnh thế nhỉ. Chắc là tối nay tuyết sẽ rơi.', '3. ～かも しれません / V（普通形） / A い（普通形） でしょう。', 2, 3, TRUE, 1),
(156, 32, 'Lượng từ + で', 'Lượng từ + で', 'Lượng từ + で', '15 man yên có đi du lịch Nhật Bản được không?', '4. Lượng từ + で / 15万円 / まんえん', 2, 4, TRUE, 1),
(157, 32, 'Từ để hỏi + か', '何 / なん', 'Từ để hỏi + か', 'VD: Q: Chị có điều gì lo lắng à? A: Tôi đang lo lắng cho sức khỏe của mẹ.', '5. Từ để hỏi + か / 何 / なん', 2, 5, TRUE, 1),
(158, 33, '命令形', 'めいれいけい / ・禁止形', '命令形', 'Thể mệnh lệnh Thể cấm chỉ hoạn, các biển báo giao thông, biển chú ý. CÁCH CHIA THỂ MỆNH LỆNH', '1. 命令形 / めいれいけい / ・禁止形', 2, 1, TRUE, 1),
(159, 33, '～と読', 'よ / みます ・～と書', '～と読', '❖ được đọc là~ ❖ được viết là~ VD:', '2. ～と読 / よ / みます ・～と書', 2, 2, TRUE, 1),
(160, 33, '～という意味', 'い / み', '～という意味', 'Kí hiệu này nghĩa là cấm sử dụng.', '3. ～という意味 / い / み', 2, 3, TRUE, 1),
(161, 33, '～と言', 'い / っていました', '～と言', 'Nam đã nói là bữa tiệc sẽ tổ chức vào 6 giờ.', '4. ～と言 / い / っていました', 2, 4, TRUE, 1),
(162, 33, '～と伝えて いただけませんか', '～と伝えて いただけませんか', '～と伝えて いただけませんか', 'Bà nhắn cho ông giúp cháu là ông nên tập thể dục nhiều được không ạ?', '5. ～と伝えて いただけませんか / おじいさんに よく運動 / うんどう', 2, 5, TRUE, 1),
(163, 34, 'V る・V た・N の ＋とおりに、 V2', 'とおりに、 V2 / V1 る', 'V る・V た・N の ＋とおりに、 V2', 'Sau đây, các bạn hãy cùng nói theo những gì tôi nói. Lưu ý: ❖ Diễn tả hành động V2 bắt chước sau khi V1 đã thực hiện xong xuôi.', '1. V る・V た・N の ＋とおりに、 V2 / 2. V た・N の ＋あとで、 V2 / 3. V１て・V１ないで ＋ V２', 2, 1, TRUE, 1),
(164, 34, 'V た/の＋あとで、 V2', '❖ V2 được thực hiện sau khi V1, N diễn ra hoặc thực hiện / V1 たとおりに、V2', 'V た/の＋あとで、 V2', 'Tôi tắm sau khi chơi bóng đá xong. ❖ Cả hai mẫu câu đều nhấn mạnh trình tự thời gian (làm V1 rồi làm V2 rồi mới làm V3).', '2. V た/の＋あとで、 V2 / ❖ V2 được thực hiện sau khi V1, N diễn ra hoặc thực hiện / V1 たとおりに、V2', 2, 2, TRUE, 1),
(165, 34, '～という意味', 'い / み', '～という意味', 'Lái xe có thắt dây an toàn. Lái xe không thắt dây an toàn. Lưu ý: ❖ V1, V2: Lựa chọn hành động V2 thay vì thực hiện hành động V1.', '3. ～という意味 / い / み', 2, 3, TRUE, 1),
(166, 35, 'Vế trước biểu thị điều kiện cần thiết để vế sau xảy ra', 'Vế trước biểu thị điều kiện cần thiết để vế sau xảy ra', 'Vế trước biểu thị điều kiện cần thiết để vế sau xảy ra', 'Nếu kéo cần gạt thì cửa sẽ mở ra.', 'レーバーを ひけば、ドアが ひらきます。 / Nếu kéo cần gạt thì cửa sẽ mở ra.', 2, 1, TRUE, 1),
(167, 35, 'Người nói đưa ra lời khuyên, gợi ý, ý tưởng, phương án', 'Người nói đưa ra lời khuyên, gợi ý, ý tưởng, phương án', 'Người nói đưa ra lời khuyên, gợi ý, ý tưởng, phương án', 'Nếu anh ấy đi thì tôi cũng đi. V1 + V2 PHÂN BIỆT Hễ mà ~ , cứ ~ thì sẽ ~ → diễn tả sự thật hiển nhiên, quy luật Sử dụng nói trong câu điều kiện : Nếu…..thì…..', '2. Người nói đưa ra lời khuyên, gợi ý, ý tưởng, phương án / 彼が 行けば、私も行きます。 / Nếu anh ấy đi thì tôi cũng đi.', 2, 2, TRUE, 1),
(168, 35, 'từ để hỏi ＋V ば＋いいですか', '（＝たら いいですか）', 'từ để hỏi ＋V ば＋いいですか', 'Tỏ tình khi nào thì tốt nhỉ?', '3. từ để hỏi ＋V ば＋いいですか / （＝たら いいですか） / いつ 告白', 2, 3, TRUE, 1),
(169, 35, 'N なら～', 'N なら～', 'N なら～', 'B: Nếu mà là Hokaido, thì tháng 6 đi ok đấy.', '4. N なら～ / A: 北海道 / ほっかいどう', 2, 4, TRUE, 1),
(170, 35, '～は ありませんか (câu nghi vấn phủ định)', '「～は ありませんか」 giúp cuộc hội thoại thoải mái', '～は ありませんか (câu nghi vấn phủ định)', 'B: Không, tôi không có.', '5. ～は ありませんか (câu nghi vấn phủ định) / 「～は ありませんか」 giúp cuộc hội thoại thoải mái / A: ほかに 意見', 2, 5, TRUE, 1),
(171, 36, 'V1 る・V1 ない ＋ように、V2', 'V1 る・V1 ない ＋ように、V2', 'V1 る・V1 ない ＋ように、V2', 'Mẫu ngữ pháp N4: V1 る・V1 ない ＋ように、V2.', '1. V1 る・V1 ない ＋ように、V2 / 2. V る ＋ ようになります / 3. V1 る・V1 ない ＋ようにしています', 2, 1, TRUE, 1),
(172, 36, 'V る ＋ ようになります', '❖ V: thường là những ĐT thể khả năng.', 'V る ＋ ようになります', 'Nếu kéo cần gạt thì cửa sẽ mở ra. ❖ Ngoài ra, mẫu câu này còn được dùng để biểu thị sự thay đổi thói quen trước kia không có, bây giờ có. (Chú ý: V không phải là ĐT thể khả năng).', '2. V る ＋ ようになります / ❖ V: thường là những ĐT thể khả năng. / 最近', 2, 2, TRUE, 1),
(173, 36, 'V1 る・V1 ない ＋ ようにしています', 'Không sử dụng V るようになりませんでした để trả / はい、読', 'V1 る・V1 ない ＋ ようにしています', 'Chú ý: lời khi phủ định. Rồi, tôi đã có thể đọc được rồi. Chưa, tôi vẫn chưa thể đọc được.', '3. V1 る・V1 ない ＋ ようにしています / Không sử dụng V るようになりませんでした để trả / はい、読', 2, 3, TRUE, 1),
(174, 36, 'V1 る・V1 ない ＋ ようにしてください', '❖ So với ～てください thì mẫu câu này là câu sai', 'V1 る・V1 ない ＋ ようにしてください', 'Các em cố gắng mỗi ngày học tiếng Nhật khoảng 2 tiếng nhé. Chú ý: Không dùng mẫu câu này trong trường hợp sai khiến, nhờ vả việc gì đó được thực hiện ngay tại chỗ.', '4. V1 る・V1 ない ＋ ようにしてください / ❖ So với ～てください thì mẫu câu này là câu sai / 毎日', 2, 4, TRUE, 1),
(175, 36, 'A い → く ・A な → に ＋ V', 'A い → く ・A な → に ＋ V', 'A い → く ・A な → に ＋ V', 'Mỗi sáng tôi cố gắng thức dậy sớm. ＋ V', '5. A い → く ・A な → に ＋ V / 毎朝 / まいあさ', 2, 5, TRUE, 1),
(176, 37, '受身形', 'うけみけい / あいます → あわれます', '受身形', 'Chú ý: ➢ V sau khi chia về bị động được coi như V nhóm 2. ➢ KHÔNG SỬ DỤNG thể bị động với:', '1. 受身形 / うけみけい / 2. N1 はN2 にV 受身', 2, 1, TRUE, 1),
(177, 37, 'N1 はN2 にV受身', 'うけみ / ❖ N1 bị/ được N2 thực hiện hành vi nào đó', 'N1 はN2 にV受身', 'Tôi đã bị trưởng phòng nhờ vả. ⮚ A là người BỊ hành động tác động vào. ⮚ B là người thực hiện hành động tác động vào N đồ sở hữu của A. ⮚ N là những thứ thuộc sở hữu của A (đồ vật, bộ phận cơ thể : chân, tay...vv)', '2. N1 はN2 にV受身 / うけみ / ❖ N1 bị/ được N2 thực hiện hành vi nào đó', 2, 2, TRUE, 1),
(178, 37, 'N が/は V 受身', 'N が/は V 受身', 'N が/は V 受身', 'Dầu mỏ được vận chuyển bằng thuyền.', '3. N が/は V 受身 / せきゆは ふねで はこばれます。', 2, 3, TRUE, 1),
(179, 37, 'N から/で つくります', '❖ S được làm ra/ tạo ra bởi N / ❖ Diễn tả xuất sứ, nguồn gốc về Nguyên vật liệu', 'N から/で つくります', 'Mì ăn liền được làm từ lúa mì.', '4. N から/で つくります / ❖ S được làm ra/ tạo ra bởi N / ❖ Diễn tả xuất sứ, nguồn gốc về Nguyên vật liệu', 2, 4, TRUE, 1),
(180, 38, 'Ⅴる/N ＋ の', 'V る / V た', 'Ⅴる/N ＋ の', 'N', '1. Ⅴる/N ＋ の / 2. V るのは/が A です / 3. V るのを わすれました', 2, 1, TRUE, 1),
(181, 38, 'V るのは/が A です', '❖ Việc làm V thì ~ / giá): 楽しい、面白い、やさしい、むずかしい、', 'V るのは/が A です', 'Việc chăm sóc con cái rất vất vả. ❖ Diễn tả sự YÊU, GHÉT, năng lực (giỏi, kém..) về một việc nào đó.', '2. V るのは/が A です / ❖ Việc làm V thì ~ / giá): 楽しい、面白い、やさしい、むずかしい、', 2, 2, TRUE, 1),
(182, 38, 'V るのを わすれました', 'V るのを わすれました', 'V るのを わすれました', 'Tôi quên mua thịt rồi.', '3. V るのを わすれました / 肉 / にく', 2, 3, TRUE, 1),
(183, 38, 'V る/たのを 知っていますか', 'V る/たのを 知っていますか', 'V る/たのを 知っていますか', 'Bạn có biết anh Yamada đã nghỉ việc tuần trước rồi không? chưa nhận được thông tin từ câu hỏi. tin từ câu hỏi.', '4. V る/たのを 知っていますか / やまださんが 会社 / かいしゃ', 2, 4, TRUE, 1),
(184, 38, 'V/A/N１ ＋のはN2 です', 'V(普通形） / A (い)', 'V/A/N１ ＋のはN2 です', 'Người mà đang dạy tiếng Nhật cho tôi là thầy Nghĩa.', '5. V/A/N１ ＋のはN2 です / V(普通形） / A (い)', 2, 5, TRUE, 1),
(185, 39, 'V て/A いくて・A なで、～', 'V て / V なくて', 'V て/A いくて・A なで、～', 'Chú ý:', '1. V て/A いくて・A なで、～ / 2. N ＋ で / 3. N/A い/A な + ので、～', 2, 1, TRUE, 1),
(186, 39, 'N ＋ で', 'N ＋ で', 'N ＋ で', 'Vì tai nạn giao thông nên bị thương.', '2. N ＋ で / 交通事故 / こうつうじこ', 2, 2, TRUE, 1),
(187, 39, 'N/A い/A な + ので、～', 'N/A い/A な + ので、～', 'N/A い/A な + ので、～', 'Vì xe bus đến muộn nên tôi đến trường muộn.', '3. N/A い/A な + ので、～ / バスが 遅 / おそ', 2, 3, TRUE, 1),
(188, 39, 'N の・V る ＋ 途中で', 'N/ A い thể thông thường / A な/ N thể thông thường', 'N の・V る ＋ 途中で', 'Đang trong giờ học thì có điện thoại.', '4. N の・V る ＋ 途中で / N/ A い thể thông thường / A な/ N thể thông thường', 2, 4, TRUE, 1),
(189, 40, '～ か、～', 'V1（普通形）(thể thường) / A い（普通形）', '～ か、～', 'Nghi vấn từ ＋', '1. ～ か、～ / 2. ～ か どうか、～ / 3. V てみます', 2, 1, TRUE, 1),
(190, 40, '～ か どうか、～', '～ か どうか、～', '～ か どうか、～', 'Tôi không nhớ là trước khi đi ra ngoài đã tắt đèn hay chưa.', '2. ～ か どうか、～ / 出 / で', 2, 2, TRUE, 1),
(191, 40, 'V てみます', 'V1（普通形）(thể thường) / A い（普通形）', 'V てみます', 'Tối nay em muốn ăn thử ở nhà hàng gần ga.', '3. V てみます / V1（普通形）(thể thường) / A い（普通形）', 2, 3, TRUE, 1),
(192, 40, 'A（い）＋ さ', '❖ Chúng ta có thể đổi đuôi「い」của tính từ đuôi い / thành 「さ」để biến tính từ đó thành danh từ.', 'A（い）＋ さ', 'Bạn có biết người ta đo chiều dài của con sông này như thế nào không?', '4. A（い）＋ さ / ❖ Chúng ta có thể đổi đuôi「い」của tính từ đuôi い / thành 「さ」để biến tính từ đó thành danh từ.', 2, 4, TRUE, 1),
(193, 40, 'でしょうか', 'でしょうか', 'でしょうか', 'Cháu Minh và My ở trường như thế nào ạ?', '5. でしょうか / ミンさんとミーさんは 学校 / がっこう', 2, 5, TRUE, 1),
(194, 41, 'もらいます→ いただきます', 'A は B に N を / いただきます', 'もらいます→ いただきます', 'Tôi được trưởng phòng sửa cho lỗi sai trong báo cáo. Tôi được anh trai mua cho xe máy mới.', '1. もらいます→ いただきます / 2. くれます→ くださいます / 3. あげます→ やります', 2, 1, TRUE, 1),
(195, 41, 'くれます→ くださいます', '❖ A cho tôi cái gì đó. / ❖ くださいます： Dùng với người bề trên.', 'くれます→ くださいます', 'Thầy Tanaka cho tôi tivi mới. Con trai tặng tôi bức tranh đẹp vào sinh nhật. ❖ A làm cho tôi cái gì đó.', '2. くれます→ くださいます / ❖ A cho tôi cái gì đó. / ❖ くださいます： Dùng với người bề trên.', 2, 2, TRUE, 1),
(196, 41, 'あげます→ やります', 'A は 私に N をV て / くださいます', 'あげます→ やります', 'Mỗi ngày tôi đều tưới nước cho hoa. ❖ A làm cho B việc gì đó.', '3. あげます→ やります / A は 私に N をV て / くださいます', 2, 3, TRUE, 1),
(197, 41, 'Ｖて＋くださいませんか', 'Ｖて＋くださいませんか', 'Ｖて＋くださいませんか', 'Cái này nặng quá, anh có thể giúp tôi được không?', '4. Ｖて＋くださいませんか / これは 重 / おも', 2, 4, TRUE, 1),
(198, 41, 'N に Ｖ', 'N に Ｖ / Ｖて＋くださいませんか', 'N に Ｖ', 'Tôi chọn khăn tắm để làm quà cưới cho cô ấy.', '5. N に Ｖ / N に Ｖ / Ｖて＋くださいませんか', 2, 5, TRUE, 1),
(199, 42, '～ために', '+ために / Ｖる', '～ために', 'Tôi được trưởng phòng sửa cho lỗi sai trong báo cáo. Tôi được anh trai mua cho xe máy mới.', '1. ～ために / 2. N/V る の＋に / 3. 助数詞＋は/も', 2, 1, TRUE, 1),
(200, 42, 'くれます→ くださいます', '❖ A cho tôi cái gì đó. / ❖ くださいます： Dùng với người bề trên.', 'くれます→ くださいます', 'Thầy Tanaka cho tôi tivi mới. Con trai tặng tôi bức tranh đẹp vào sinh nhật. ❖ A làm cho tôi cái gì đó.', '2. くれます→ くださいます / ❖ A cho tôi cái gì đó. / ❖ くださいます： Dùng với người bề trên.', 2, 2, TRUE, 1),
(201, 42, 'あげます→ やります', 'あげます→ やります', 'あげます→ やります', 'Mẫu ngữ pháp N4: あげます→ やります.', 'あげます→ やります', 2, 3, TRUE, 1),
(202, 42, '～によって', '+ために / Ｖる', '～によって', 'Tôi được trưởng phòng sửa cho lỗi sai trong báo cáo. Tôi được anh trai mua cho xe máy mới. ❖ A cho tôi cái gì đó.', '４. ～によって / +ために / Ｖる', 2, 4, TRUE, 1),
(203, 42, 'N に Ｖ', '⮚ Trợ từ 「に」 được dùng để diễn tả mục đích / N に Ｖ', 'N に Ｖ', 'Tôi chọn khăn tắm để làm quà cưới cho cô ấy.', '5. N に Ｖ / ⮚ Trợ từ 「に」 được dùng để diễn tả mục đích / N に Ｖ', 2, 5, TRUE, 1),
(204, 43, 'V ます ＋ そうです', 'V ます ＋ そうです', 'V ます ＋ そうです', 'Mẫu ngữ pháp N4: V ます ＋ そうです.', '1. V ます ＋ そうです / 2. A い・A な＋ そうです / 3. V てきます', 2, 1, TRUE, 1),
(205, 43, 'A い・A な＋ そうです', 'cảm xúc như: うれしい、 かなしい、さびしい thì / thêm 「そうです」.', 'A い・A な＋ そうです', 'Trông anh ấy có vẻ kỳ lạ nhỉ. Món mì này trông có vẻ cay.', '2. A い・A な＋ そうです / cảm xúc như: うれしい、 かなしい、さびしい thì / thêm 「そうです」.', 2, 2, TRUE, 1),
(206, 43, 'V てきます', 'V てきます', 'V てきます', 'Tôi đi hỏi đường rồi về.', '3. V てきます / 道 / みち', 2, 3, TRUE, 1),
(207, 43, 'V てくれませんか', 'V て ＋ きます / V て いただけませんか', 'V てくれませんか', 'Anh kiểm tra lại báo cáo giúp tôi được không?', '4. V てくれませんか / V て ＋ きます / V て いただけませんか', 2, 4, TRUE, 1),
(208, 44, '～すぎる', 'V ます / A い', '～すぎる', 'Mẫu ngữ pháp N4: ～すぎる.', '1. ～すぎる / 2. Ⅴやすい/Ⅴにくい / 3. A くする/A にする', 2, 1, TRUE, 1),
(209, 44, 'Ⅴやすい/Ⅴにくい', '❖ ～やすい và ～にくい chia giống như A い.', 'Ⅴやすい/Ⅴにくい', 'Vì thuốc này ngọt nên dễ uống. Cách dạy của thầy Nghĩa thì dễ hiểu.', '2. Ⅴやすい/Ⅴにくい / ❖ ～やすい và ～にくい chia giống như A い. / この薬', 2, 2, TRUE, 1),
(210, 44, 'A くする/A にする', 'A い ＋ くします / V ます ＋ やすいです。 Dễ làm V', 'A くする/A にする', 'Vì nóng nên em hãy điều chỉnh cho phòng mát lên.', '3. A くする/A にする / A い ＋ くします / V ます ＋ やすいです。 Dễ làm V', 2, 3, TRUE, 1),
(211, 44, 'N にする', 'N にする', 'N にする', 'Kỳ thi JLPT tháng 12 tôi sẽ quyết định thi N4.', '4. N にする / 12 月の JLPT は N4 にします。 / Kỳ thi JLPT tháng 12 tôi sẽ quyết định thi N4.', 2, 4, TRUE, 1),
(212, 45, '場合', 'ばあい / は、～', '場合', 'Trong trường hợp gặp tai nạn giao thông hãy gọi ngay cho 110. Trong trường hợp có động đất thì việc tắt lửa là quan trọng.', '1. 場合 / ばあい / は、～', 2, 1, TRUE, 1),
(213, 45, 'のに、～', '「V る場合」: trong TH trước khi xảy ra ∼, cần làm gì / 「V た場合」: trong TH đã xảy ra ∼, cần làm gì ∼', 'のに、～', 'Đã có hẹn rồi thế mà cô ấy không đến. Điện thoại này đắt vậy mà rất hay hỏng hóc.', '2. のに、～ / 「V る場合」: trong TH trước khi xảy ra ∼, cần làm gì / 「V た場合」: trong TH đã xảy ra ∼, cần làm gì ∼', 2, 2, TRUE, 1),
(214, 46, '～ところ', '❖ Thường đi kèm với: たった今', '～ところ', 'Tôi vừa mới ăn cơm xong.', '1. ～ところ / 2. ～ばかり / 3. ～はず', 2, 1, TRUE, 1),
(215, 46, '～ばかり', '• V たところです： Sự việc vừa xảy ra và / • V たばかりです：Thời điểm xảy ra sự việc', '～ばかり', 'Chú ý: vừa mới kết thúc, thời điểm xảy ra sự việc ngắn. ngắn hay dài tùy vào cảm nhận của người nói.', '2. ～ばかり / • V たところです： Sự việc vừa xảy ra và / • V たばかりです：Thời điểm xảy ra sự việc', 2, 2, TRUE, 1),
(216, 46, '～はず', '～はず', '～はず', 'Tối nay chắc chắn sẽ mưa. Vì sáng nay tôi đã xem dự báo thời tiết.', '3. ～はず / 今晩 / こんばん', 2, 3, TRUE, 1),
(217, 47, '～そうです', '(N によると）普通形 + そうです / PHÂN BIỆT', '～そうです', 'PHÂN BIỆT Cách kết hợp', '1. ～そうです / 2. ～ようです / 3. ～N がします', 2, 1, TRUE, 1),
(218, 47, '～ようです', '～ようです', '～ようです', 'Hình như Nam thích sách. Lúc nào cũng thấy đang cầm quyển sách. Hình như em bé không thích sữa này.', '2. ～ようです / ナムさんは 本 / ほん', 2, 2, TRUE, 1),
(219, 47, '～N がします', '～N がします', '～N がします', 'Có tiếng ồn ào nhỉ.', '3. ～N がします / にぎやかな声 / こえ', 2, 3, TRUE, 1),
(220, 48, '使役形', 'しえきかたち / しえきけい', '使役形', 'Cách dùng: ❖ Sai khiến, cho phép (không dùng với người trên). Chú ý: V sau khi chia về thể sai khiến được coi như V nhóm 2.', '1. 使役形 / しえきかたち / 2. N をV（使役形', 2, 1, TRUE, 1),
(221, 48, 'N をV（使役形', 'しえきけい / ❖ A sai/ bắt/ phân công/ để/ cho B làm V.', 'N をV（使役形', 'Chú ý: ❖ Cấu trúc này cũng có ý nghĩa: A làm cho/khiến B cảm thấy V (tâm trạng, cảm xúc)', '2. N をV（使役形 / しえきけい / ❖ A sai/ bắt/ phân công/ để/ cho B làm V.', 2, 2, TRUE, 1),
(222, 48, 'N１にN2 をV（使役形', 'しえきけい / ❖ A sai, bắt, phân công, để, cho B làm N.', 'N１にN2 をV（使役形', 'Khi còn nhỏ, mẹ tôi bắt tôi ăn nhiều rau. Tôi muốn cho con gái học piano. Chú ý: ❖ Trường hợp muốn nhận sự giúp đỡ từ người trên thì ❖ Trường hợp muốn nhận sự giúp đỡ từ người ngang bằng hoặc người dưới thì dùng mẫu Người bị sai khiến Người sai khiến Nội động từ Người bị sai khiến', '3. N１にN2 をV（使役形 / しえきけい / ❖ A sai, bắt, phân công, để, cho B làm N.', 2, 3, TRUE, 1),
(223, 48, 'V させてていただけませんか', '「～てもいいですか。」.', 'V させてていただけませんか', 'Cho phép tôi ghi âm cuộc họp có được không ạ? ❖ Để xin phép mà không cần sự đồng ý của đối phương ta dùng mẫu câu:', '4. V させてていただけませんか / 「～てもいいですか。」. / 会議', 2, 4, TRUE, 1),
(224, 49, 'Đối với các động từ có cách nói tôn kính đặc biệt', 'thì không dùng hình thức thể bị động và mẫu「お / ～になります」mà sử dụng dạng đặc biệt của', 'Đối với các động từ có cách nói tôn kính đặc biệt', 'động từ đó.', 'thì không dùng hình thức thể bị động và mẫu「お / ～になります」mà sử dụng dạng đặc biệt của', 2, 1, TRUE, 1),
(225, 49, 'Không sử dụng 2 tầng kính ngữ trong 1 từ', 'Không sử dụng 2 tầng kính ngữ trong 1 từ', 'Không sử dụng 2 tầng kính ngữ trong 1 từ', 'Mẫu ngữ pháp N4: Không sử dụng 2 tầng kính ngữ trong 1 từ.', 'Không sử dụng 2 tầng kính ngữ trong 1 từ', 2, 2, TRUE, 1),
(226, 49, 'お～になります', '❖ Có mức độ lịch sự cao hơn 「V られます」. / ❖ Không dùng với V đứng trước ます có 1 âm tiết như い', 'お～になります', 'Chú ý: ❖ Không dùng cho V nhóm 3', '3. お～になります / ❖ Có mức độ lịch sự cao hơn 「V られます」. / ❖ Không dùng với V đứng trước ます có 1 âm tiết như い', 2, 3, TRUE, 1),
(227, 49, '特別', 'とくべつ / な尊敬語', '特別', 'Chú ý: 1. Đối với các động từ có cách nói tôn kính đặc biệt động từ đó.', '4. 特別 / とくべつ / な尊敬語', 2, 4, TRUE, 1),
(228, 49, 'お/ご～ください', '➢ 召し上がります / ➢ ごらんになります', 'お/ご～ください', 'Chú ý: ❖ Không dùng cấu trúc này với các kính ngữ đặc biệt, trừ 2 động từ.', '5. お/ご～ください / ➢ 召し上がります / ➢ ごらんになります', 2, 5, TRUE, 1),
(229, 49, 'お/ご～ですか', '申 / もう', 'お/ご～ですか', 'Anh chị đăng kí không ạ? Quý khách có mang theo thẻ thư viện không ạ?', '6. お/ご～ですか / 申 / もう', 2, 6, TRUE, 1),
(230, 50, '謙譲語', 'けんじょうご / V(I,II)', '謙譲語', 'Tôi sẽ thông báo thời gian cuộc họp cho giám đốc.', '1. 謙譲語 / けんじょうご / V(I,II)', 2, 1, TRUE, 1),
(231, 50, '謙譲語', 'けんじょうご / V(III)', '謙譲語', 'Sau đây tôi xin phép giới thiệu về Tokyo ạ.', '2. 謙譲語 / けんじょうご / V(III)', 2, 2, TRUE, 1),
(232, 50, '謙譲語', 'けんじょうご / の特別', '謙譲語', 'Tôi sẽ đến vào 9 giờ sáng mai. Tôi biết anh/chị bận nhưng nếu có thời gian rảnh thì mời anh chị đến nhà tôi chơi.', '3. 謙譲語 / けんじょうご / の特別', 2, 3, TRUE, 1)
ON DUPLICATE KEY UPDATE
    grammar_chapter_id = VALUES(grammar_chapter_id),
    title = VALUES(title),
    pattern = VALUES(pattern),
    meaning_vi = VALUES(meaning_vi),
    explanation = VALUES(explanation),
    formation = VALUES(formation),
    jlpt_level_id = VALUES(jlpt_level_id),
    display_order = VALUES(display_order),
    is_published = VALUES(is_published),
    version = VALUES(version);

INSERT INTO grammar_examples (id, grammar_lesson_id, japanese_text, reading, meaning_vi, display_order) VALUES
(154, 120, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: ～んです.', 1),
(155, 121, 'こいびとが できたんですか。', NULL, 'Ly hôm nay vui nhỉ. Bạn có người yêu à?', 1),
(156, 121, 'どうして日本語を 勉強しているんですか。', NULL, 'Tại sao bạn học tiếng Nhật thế?', 2),
(157, 122, '名前を書いてください。', NULL, 'Hãy viết tên.', 1),
(158, 123, 'もう いちど おしえていただけませんか。', NULL, 'Câu hỏi này tôi vẫn chưa hiểu. Bạn chỉ cho tôi thêm 1 lần nữa được không?', 1),
(159, 124, 'ご飯を食べてから、勉強します。', NULL, 'Sau khi ăn cơm, tôi học.', 1),
(160, 125, '母： たろうくん、やさいを 食べてください。', NULL, 'Tarou ơi, ăn rau đi con.', 1),
(161, 125, '子： いいえ、やさいは きらいです。', NULL, 'Không, con ghét rau.', 2),
(162, 126, 'が かえられます。', NULL, 'Tại ngân hàng có thể đổi tiền.', 1),
(163, 127, '聞こえます', NULL, 'CHỦ QUAN KHÁCH QUAN PHÂN BIỆT', 1),
(164, 127, 'られます。', NULL, 'Đeo kính thì nhìn thấy chữ.', 2),
(165, 128, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: 場所 (địa điểm) にN が できます.', 1),
(166, 129, 'せません。', NULL, 'Tôi chỉ nói được tiếng Nhật.', 1),
(167, 130, 'ひらがなは 書けますが、漢字は 書けません。', NULL, 'Tôi thì có thể viết Hiragana nhưng, kanji thì không thể viết.', 1),
(168, 131, 'ちちは ビールを のみながら、はたらきます。', NULL, 'Bố tôi vừa uống bia vừa làm việc.', 1),
(169, 131, 'しています。', NULL, 'Maria vừa đi làm vừa học đại học.', 2),
(170, 132, 'ともだちと テニスを しています。。', NULL, 'Ngày nghỉ tôi thường chơi tennis với bạn bè.', 1),
(171, 133, '私もベトナム人です。', NULL, 'Tôi cũng là người Việt Nam.', 1),
(172, 134, 'きたいです。', NULL, 'Công việc vừa thú vị, lương cao, vì vậy tôi muốn làm việc ở công ty này.', 1),
(173, 135, 'も おいしいですから。', NULL, 'Q: Tại sao bạn thích sống ở nông thôn?', 1),
(174, 136, '教室に学生がいます。', NULL, 'Trong lớp có học sinh.', 1),
(175, 137, 'を ぜんぶ ふいてしまいます。', NULL, 'Tôi sẽ lau xong toàn bộ bàn của cửa hàng.', 1),
(176, 138, '私もベトナム人です。', NULL, 'Tôi cũng là người Việt Nam.', 1),
(177, 139, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: N(nơi chốn) に行きます／来ます／帰ります.', 1),
(178, 140, 'なんです。', NULL, 'Từ tháng sau, tôi sẽ chuyển việc về công ty mẹ ở Osaka', 1),
(179, 140, 'B: それ おめでとうございます。', NULL, 'Xin chúc mừng anh/chị về điều đó Đi đến nhà ga Đến trường Trở về nhà', 2),
(180, 141, 'をもってください。', NULL, 'Lấy cho tôi tài liệu ở trên bàn.', 1),
(181, 141, 'B: はい、へー、ありません。', NULL, 'Vâng, nó không có ở đây.', 2),
(182, 142, 'としちゃったんです。', NULL, 'Tôi lỡ đánh rơi mất ví ở đâu đó rồi.', 1),
(183, 143, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: Chuẩn bị.', 1),
(184, 144, 'しておきます。', NULL, 'Trước giờ học, tôi chuẩn bị trước bài mới. Ví dụ', 1),
(185, 144, 'めてあります。', NULL, 'V Tự động từ', 2),
(186, 145, 'が まだ ふっています。', NULL, 'Trời vẫn còn đang mưa.', 1),
(187, 145, 'べていません。', NULL, 'Tôi vẫn chưa ăn trưa.', 2),
(188, 146, 'どんな スポーツを していますか。', NULL, 'B: À vâng, tôi chơi mấy môn như là quần vợt, bơi lội,...', 1),
(189, 146, '...そうですね。 テニスとか 水泳', NULL, 'Kết hợp với N Kết hợp với V × Trường hợp sử dụng Văn viết Văn nói', 2),
(190, 147, 'きません。', NULL, 'Ngày nghỉ tôi chẳng đi đâu cả.', 1),
(191, 148, '教室に学生がいます。', NULL, 'Trong lớp có học sinh.', 1),
(192, 149, 'っています。', NULL, 'Tôi đang định đi xem phim vào tuần sau.', 1),
(193, 150, 'つけていません。', NULL, 'Tôi vẫn chưa tìm thấy cái túi xách màu trắng của mẹ tôi.', 1),
(194, 151, 'つもりです。', NULL, 'Tôi sẽ không chơi game từ thứ 2 đến thứ 6.', 1),
(195, 152, '私は学生です。', NULL, 'Tôi là học sinh.', 1),
(196, 153, '私は学生です。', NULL, 'Tôi là học sinh.', 1),
(197, 154, '、たいふうが くるでしょう。', NULL, 'Cuối tuần có lẽ bão sẽ đến.', 1),
(198, 155, 'かもしれません。', NULL, 'Lạnh thế nhỉ. Chắc là tối nay tuyết sẽ rơi.', 1),
(199, 156, 'できますか。', NULL, '15 man yên có đi du lịch Nhật Bản được không?', 1),
(200, 157, 'なことが あるんですか。', NULL, 'A: Tôi đang lo lắng cho sức khỏe của mẹ.', 1),
(201, 158, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: 命令形.', 1),
(202, 159, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: ～と読.', 1),
(203, 160, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: ～という意味.', 1),
(204, 161, 'っていました。', NULL, 'Nam đã nói là bữa tiệc sẽ tổ chức vào 6 giờ.', 1),
(205, 162, 'えていただけませんか。', NULL, 'Bà nhắn cho ông giúp cháu là ông nên tập thể dục nhiều được không ạ?', 1),
(206, 163, 'ってください。', NULL, 'Sau đây, các bạn hãy cùng nói theo những gì tôi nói. Lưu ý:', 1),
(207, 163, 'ってください。', NULL, 'Bạn hãy nói lại những gì tôi đã nói.', 2),
(208, 164, 'サッカーを したあとで、シャワーを あびます。', NULL, 'Tôi tắm sau khi chơi bóng đá xong.', 1),
(209, 164, 'きてから、はを みがきました。', NULL, 'Sáng nay sau khi thức dậy tôi đã đánh răng. thực hiện khi nào?”', 2),
(210, 165, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: ～という意味.', 1),
(211, 166, 'レーバーを ひけば、ドアが ひらきます。', NULL, 'Nếu kéo cần gạt thì cửa sẽ mở ra.', 1),
(212, 167, '彼が 行けば、私も行きます。', NULL, 'Nếu anh ấy đi thì tôi cũng đi. V1 + V2 PHÂN BIỆT Hễ mà ~ , cứ ~ thì sẽ ~ → diễn tả sự thật hiển nhiên, quy luật Sử dụng nói trong câu điều kiện : Nếu…..thì…..', 1),
(213, 168, 'すればいいですか。', NULL, 'Tỏ tình khi nào thì tốt nhỉ?', 1),
(214, 169, 'がいいですよ。', NULL, 'A: Tôi muốn đi Hokaido ấy... B: Nếu mà là Hokaido, thì tháng 6 đi ok đấy.', 1),
(215, 170, 'B: いいえ、ありません。', NULL, 'A: Anh có ý kiến gì khác không? B: Không, tôi không có.', 1),
(216, 171, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: V1 る・V1 ない ＋ように、V2.', 1),
(217, 172, 'べられる ようになりました。', NULL, 'Nếu kéo cần gạt thì cửa sẽ mở ra.', 1),
(218, 172, 'ジョギングをするようになりました。', NULL, 'Từ tháng trước tôi đã bắt đầu chạy bộ mỗi buổi sáng. ＊ Bạn đã có thể ~ chưa? Bạn đã có thể đọc được báo Nhật chưa?', 2),
(219, 173, 'ようにしています。', NULL, 'Vì có hại cho cơ thể nên tôi cố gắng không uống nhiều rượu.', 1),
(220, 174, '名前を書いてください。', NULL, 'Hãy viết tên.', 1),
(221, 175, 'きる ようにしています。', NULL, 'Mỗi sáng tôi cố gắng thức dậy sớm.', 1),
(222, 175, 'すみませんが、まどを開けてください。', NULL, '＋ V', 2),
(223, 176, '教室に学生がいます。', NULL, 'Trong lớp có học sinh.', 1),
(224, 177, 'に たのまれました。', NULL, 'Tôi đã bị trưởng phòng nhờ vả. ⮚ A là người BỊ hành động tác động vào. ⮚ B là người thực hiện hành động tác động vào N đồ sở hữu của A. ⮚ N là những thứ thuộc sở hữu của A (đồ vật, bộ phận cơ thể : chân, tay...vv)', 1),
(225, 177, '弟に おもちゃを こわされました。', NULL, 'Tôi bị em trai làm hỏng đồ chơi. (thể bị động) (thực hiện hành vi) (tiếp nhận hành vi)', 2),
(226, 178, 'せきゆは ふねで はこばれます。', NULL, 'Dầu mỏ được vận chuyển bằng thuyền.', 1),
(227, 179, 'られました。', NULL, 'Mì ăn liền được làm từ lúa mì.', 1),
(228, 180, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: Ⅴる/N ＋ の.', 1),
(229, 181, 'このかばんはいくらですか。', NULL, 'Cái cặp này giá bao nhiêu?', 1),
(230, 182, 'うのを 忘れました。', NULL, 'Tôi quên mua thịt rồi.', 1),
(231, 183, 'ていますか。', NULL, 'Bạn có biết anh Yamada đã nghỉ việc tuần trước rồi không?', 1),
(232, 183, 'Phân biệt 知りません và 知りませんでした', NULL, 'chưa nhận được thông tin từ câu hỏi.', 2),
(233, 184, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: V/A/N１ ＋のはN2 です.', 1),
(234, 185, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: V て/A いくて・A なで、～.', 1),
(235, 186, 'で、けがを してしまいました。', NULL, 'Vì tai nạn giao thông nên bị thương.', 1),
(236, 187, 'れました。', NULL, 'Vì xe bus đến muộn nên tôi đến trường muộn.', 1),
(237, 188, 'が かかりました。', NULL, 'Đang trong giờ học thì có điện thoại.', 1),
(238, 189, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: ～ か、～.', 1),
(239, 190, 'えていません。', NULL, 'Tôi không nhớ là trước khi đi ra ngoài đã tắt đèn hay chưa.', 1),
(240, 191, 'みたいです。', NULL, 'Tối nay em muốn ăn thử ở nhà hàng gần ga.', 1),
(241, 192, 'っていますか。', NULL, 'Bạn có biết người ta đo chiều dài của con sông này như thế nào không?', 1),
(242, 193, 'でどうでしょうか。', NULL, 'Cháu Minh và My ở trường như thế nào ạ?', 1),
(243, 194, 'して いただきます。', NULL, 'Tôi được trưởng phòng sửa cho lỗi sai trong báo cáo.', 1),
(244, 194, 'ってもらいます。', NULL, 'Tôi được anh trai mua cho xe máy mới.', 2),
(245, 195, 'くださいました。', NULL, 'Thầy Tanaka cho tôi tivi mới.', 1),
(246, 195, 'を くれました。', NULL, 'Con trai tặng tôi bức tranh đẹp vào sinh nhật.', 2),
(247, 196, 'に みずを やります。', NULL, 'Mỗi ngày tôi đều tưới nước cho hoa.', 1),
(248, 196, 'ってやります。', NULL, 'Tôi thường hay hát cho con nghe.', 2),
(249, 197, 'いませんか。', NULL, 'Cái này nặng quá, anh có thể giúp tôi được không?', 1),
(250, 198, 'びました。', NULL, 'Tôi chọn khăn tắm để làm quà cưới cho cô ấy.', 1),
(251, 199, 'して いただきます。', NULL, 'Tôi được trưởng phòng sửa cho lỗi sai trong báo cáo.', 1),
(252, 199, 'ってもらいます。', NULL, 'Tôi được anh trai mua cho xe máy mới.', 2),
(253, 200, 'くださいました。', NULL, 'Thầy Tanaka cho tôi tivi mới.', 1),
(254, 200, 'を くれました。', NULL, 'Con trai tặng tôi bức tranh đẹp vào sinh nhật.', 2),
(255, 201, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: あげます→ やります.', 1),
(256, 202, 'して いただきます。', NULL, 'Tôi được trưởng phòng sửa cho lỗi sai trong báo cáo.', 1),
(257, 202, 'ってもらいます。', NULL, 'Tôi được anh trai mua cho xe máy mới.', 2),
(258, 203, 'びました。', NULL, 'Tôi chọn khăn tắm để làm quà cưới cho cô ấy.', 1),
(259, 204, '私は学生です。', NULL, 'Tôi là học sinh.', 1),
(260, 205, '彼は へんそうですね。', NULL, 'Trông anh ấy có vẻ kỳ lạ nhỉ.', 1),
(261, 205, 'そうです。', NULL, 'Món mì này trông có vẻ cay.', 2),
(262, 206, 'いてきます。', NULL, 'Tôi đi hỏi đường rồi về.', 1),
(263, 207, 'レポートを チェックしてくれませんか。', NULL, 'Anh kiểm tra lại báo cáo giúp tôi được không?', 1),
(264, 208, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: ～すぎる.', 1),
(265, 209, 'みやすいです。', NULL, 'Vì thuốc này ngọt nên dễ uống.', 1),
(266, 209, 'は わかりやすいです。', NULL, 'Cách dạy của thầy Nghĩa thì dễ hiểu.', 2),
(267, 210, 'しくしてください。', NULL, 'Vì nóng nên em hãy điều chỉnh cho phòng mát lên.', 1),
(268, 211, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: N にする.', 1),
(269, 212, 'してください。', NULL, 'Trong trường hợp gặp tai nạn giao thông hãy gọi ngay cho 110. Trong trường hợp có động đất thì việc tắt lửa là quan trọng.', 1),
(270, 213, 'ませんでした。', NULL, 'Đã có hẹn rồi thế mà cô ấy không đến.', 1),
(271, 213, 'こしょう', NULL, 'Điện thoại này đắt vậy mà rất hay hỏng hóc.', 2),
(272, 214, 'べたところです。', NULL, 'Tôi vừa mới ăn cơm xong.', 1),
(273, 215, 'したばかりです。', NULL, 'Chúng tôi vừa mới kết hôn năm ngoái.', 1),
(274, 215, 'れたばかりです。', NULL, 'Tôi vừa mới chia tay với người yêu hôm qua.', 2),
(275, 216, 'ましたから。', NULL, 'Tối nay chắc chắn sẽ mưa. Vì sáng nay tôi đã xem dự báo thời tiết.', 1),
(276, 217, '私は学生です。', NULL, 'Tôi là học sinh.', 1),
(277, 218, 'ていますよ。', NULL, 'Hình như Nam thích sách. Lúc nào cũng thấy đang cầm quyển sách.', 1),
(278, 218, 'きじゃないようです。', NULL, 'Hình như em bé không thích sữa này.', 2),
(279, 219, 'がしますね。', NULL, 'Có tiếng ồn ào nhỉ.', 1),
(280, 220, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: 使役形.', 1),
(281, 221, 'かせたことがあります。', NULL, 'Khi còn nhỏ tôi đã từng làm cho mẹ khóc.', 1),
(282, 221, 'ばせました。', NULL, 'Vì tôi đã đỗ đại học nên bố mẹ vui mừng. Người bị sai khiến Người sai khiến Nội động từ', 2),
(283, 222, 'べさせました。', NULL, 'Khi còn nhỏ, mẹ tôi bắt tôi ăn nhiều rau.', 1),
(284, 222, 'わせたいです。', NULL, 'Tôi muốn cho con gái học piano. Chú ý:', 2),
(285, 223, 'させていただけませんか。', NULL, 'Cho phép tôi ghi âm cuộc họp có được không ạ?', 1),
(286, 223, 'めさせていただきます。', NULL, 'Tôi xin phép bắt đầu cuộc họp.', 2),
(287, 224, '日本語が上手になりました。', NULL, 'Tiếng Nhật của tôi đã trở nên giỏi hơn.', 1),
(288, 225, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: Không sử dụng 2 tầng kính ngữ trong 1 từ.', 1),
(289, 226, 'めになりましたか。', NULL, 'Trưởng phòng đã làm ở công ty được bao lâu rồi ạ.', 1),
(290, 226, 'みになりますか。', NULL, 'Hàng tối sếp ngủ lúc mấy giờ vậy ạ?', 2),
(291, 227, 'おやめられになります', NULL, 'Anh có chơi golf không ạ?', 1),
(292, 228, 'きください。', NULL, 'Xin hãy viết tên vào đây. Xin mời anh/ chị dùng bữa.', 1),
(293, 229, '私もベトナム人です。', NULL, 'Tôi cũng là người Việt Nam.', 1),
(294, 230, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: 謙譲語.', 1),
(295, 231, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: 謙譲語.', 1),
(296, 232, '日本語を勉強します。', NULL, 'Ví dụ minh họa cho mẫu: 謙譲語.', 1)
ON DUPLICATE KEY UPDATE
    grammar_lesson_id = VALUES(grammar_lesson_id),
    japanese_text = VALUES(japanese_text),
    reading = VALUES(reading),
    meaning_vi = VALUES(meaning_vi),
    display_order = VALUES(display_order);
