SET NAMES utf8mb4;

DELETE ge FROM grammar_examples ge JOIN grammar_lessons gl ON gl.id = ge.grammar_lesson_id WHERE gl.jlpt_level_id = 3;

DELETE FROM grammar_lessons WHERE jlpt_level_id = 3;

DELETE FROM grammar_chapters WHERE jlpt_level_id = 3;

INSERT INTO grammar_chapters (id, jlpt_level_id, chapter_number, name, description, display_order, is_published, version) VALUES
(51, 3, 1, 'Bài 1 (Mẫu 1-5)', 'Ngữ pháp N3 - Mẫu 1-5', 1, TRUE, 1),
(52, 3, 2, 'Bài 2 (Mẫu 6-10)', 'Ngữ pháp N3 - Mẫu 6-10', 2, TRUE, 1),
(53, 3, 3, 'Bài 3 (Mẫu 11-15)', 'Ngữ pháp N3 - Mẫu 11-15', 3, TRUE, 1),
(54, 3, 4, 'Bài 4 (Mẫu 16-20)', 'Ngữ pháp N3 - Mẫu 16-20', 4, TRUE, 1),
(55, 3, 5, 'Bài 5 (Mẫu 21-25)', 'Ngữ pháp N3 - Mẫu 21-25', 5, TRUE, 1),
(56, 3, 6, 'Bài 6 (Mẫu 26-30)', 'Ngữ pháp N3 - Mẫu 26-30', 6, TRUE, 1),
(57, 3, 7, 'Bài 7 (Mẫu 31-35)', 'Ngữ pháp N3 - Mẫu 31-35', 7, TRUE, 1),
(58, 3, 8, 'Bài 8 (Mẫu 36-40)', 'Ngữ pháp N3 - Mẫu 36-40', 8, TRUE, 1),
(59, 3, 9, 'Bài 9 (Mẫu 41-45)', 'Ngữ pháp N3 - Mẫu 41-45', 9, TRUE, 1),
(60, 3, 10, 'Bài 10 (Mẫu 46-50)', 'Ngữ pháp N3 - Mẫu 46-50', 10, TRUE, 1),
(61, 3, 11, 'Bài 11 (Mẫu 51-55)', 'Ngữ pháp N3 - Mẫu 51-55', 11, TRUE, 1),
(62, 3, 12, 'Bài 12 (Mẫu 56-60)', 'Ngữ pháp N3 - Mẫu 56-60', 12, TRUE, 1),
(63, 3, 13, 'Bài 13 (Mẫu 61-62)', 'Ngữ pháp N3 - Mẫu 61-62', 13, TRUE, 1)
ON DUPLICATE KEY UPDATE
    jlpt_level_id = VALUES(jlpt_level_id),
    chapter_number = VALUES(chapter_number),
    name = VALUES(name),
    description = VALUES(description),
    display_order = VALUES(display_order),
    is_published = VALUES(is_published),
    version = VALUES(version);

INSERT INTO grammar_lessons (id, grammar_chapter_id, title, pattern, meaning_vi, explanation, formation, jlpt_level_id, display_order, is_published, version) VALUES
(233, 51, 'Mẫu 1 - ～うちに', '～うちに', 'Trong lúc', 'Thực hiện một hành động trước khi một trạng thái khác thay đổi Trong khoảng thời gian một hành động, sự việc xảy ra, có một trạng thái thay đổi, không mang ý chí', '～うちに', 3, 1, TRUE, 1),
(234, 51, 'Mẫu 2 - 間 (あいだ) … / ～間に(あいだに)…', '間 (あいだ) … / ～間に(あいだに)…', 'Trong khoảng thời gian', '～間… : Khi một hành động xảy ra trong một thời gian dài, một hành động khác cũng xảy ra kéo dài đồng thời trong khoảng thời gian đó ～間に: Khi một hành động xảy ra trong một thời gian dài, một hành động khác xảy ra chỉ tại một thời điểm trong khoảng thời gian đó', '間 (あいだ) … / ～間に(あいだに)…', 3, 2, TRUE, 1),
(235, 51, 'Mẫu 3 - ～てからでないと… / ～てからでなければ…', '～てからでないと… / ～てからでなければ…', 'Nếu không phải là sau khi ～ thì không thể…', 'Cho đến khi việc gì đó được thực hiện xong, thì một việc khác cũng vẫn chưa làm được. Câu được dùng ở dạng phủ định', '～てからでないと… / ～てからでなければ…', 3, 3, TRUE, 1),
(236, 51, 'Mẫu 4 - ～ところだ / ～ところ (+trợ từ)', '～ところだ / ～ところ (+trợ từ)', 'Vào thời điểm', 'Khoảnh khắc ngay trước, khoảnh khắc ngay sau, hay vào chính giữa khoảnh khắc đó', '～ところだ / ～ところ (+trợ từ)', 3, 4, TRUE, 1),
(237, 51, 'Mẫu 5 - N ＋ ～どおりだ /～どおり（に）', 'N ＋ ～どおりだ /～どおり（に）', 'Dựa theo', 'Thực hiện một hành động giống như hướng dẫn có sẵn, hoặc giống như cách người khác làm trước', 'N ＋ ～どおりだ /～どおり（に）', 3, 5, TRUE, 1),
(238, 52, 'Mẫu 6 - ～によって… ～によっては…', '～によって… ～によっては…', 'Tùy vào, tùy theo', 'Thể hiện trạng thái không nhất định mà thay đổi tùy thuộc vào một yếu tố nào đó', '～によって… ～によっては…', 3, 1, TRUE, 1),
(239, 52, 'Mẫu 7 - N の/ Vる ＋ ～たびに…', 'N の/ Vる ＋ ～たびに…', 'Mỗi lần', 'Mỗi khi điều gì xảy ra thì có điều khác cũng xảy ra theo. Nhấn mạnh sự lặp lại của hành động, nhưng không dùng cho những hiện tượng tự nhiên diễn ra hàng ngày', 'N の/ Vる ＋ ～たびに…', 3, 2, TRUE, 1),
(240, 52, 'Mẫu 8 - （～ば）～ほど /（～なら）～ほど/ ～ほど', '（～ば）～ほど /（～なら）～ほど/ ～ほど', 'Càng - càng', 'Phía sau ほど ・・・ là một vế thể hiện sự thay đổi tương ứng, tỉ lệ với vế trước', '（～ば）～ほど /（～なら）～ほど/ ～ほど', 3, 3, TRUE, 1),
(241, 52, 'Mẫu 9 - Nの/Vる/Vた + ～ついでに', 'Nの/Vる/Vた + ～ついでに', 'Tiện thể', 'Nhân lúc thực hiện một hành động này thì thì thực hiện thêm một hành động khác', 'Nの/Vる/Vた + ～ついでに', 3, 4, TRUE, 1),
(242, 52, 'Mẫu 10 - N / Vる・ない (Naだ -な) ＋ ～くらい・～ぐらい・ ～ほど…', 'N / Vる・ない (Naだ -な) ＋ ～くらい・～ぐらい・ ～ほど…', 'Tới mức', 'Biểu thị mức độ của một trạng thái sự vật, hiện tượng bằng cách đưa ra một sự vật hiện tượng khác', 'N / Vる・ない (Naだ -な) ＋ ～くらい・～ぐらい・ ～ほど…', 3, 5, TRUE, 1),
(243, 53, 'Mẫu 11 - ない', 'ない', 'Không có gì … tới mức…', 'Thể hiện sự đánh giá về một sự vật, hiện tượng là nhất, không gì bằng, mang tính chủ quan của người nói, không phải sự vật hiện tượng hiển nhiên, khách quan', 'ない', 3, 1, TRUE, 1),
(244, 53, 'Mẫu 12 - Vる + ～くらいなら/～ぐらいなら', 'Vる + ～くらいなら/～ぐらいなら', 'Nếu phải đến mức… thì', 'Đưa ra một giải pháp, lựa chọn tốt hơn khi so sánh với một sự lựa chọn khác. Trong đó, vế đằng sau được người nói đưa ra để so sánh là tốt hơn so với lựa chọn ở vế đằng trước, theo như chủ quan của người nói', 'Vる + ～くらいなら/～ぐらいなら', 3, 2, TRUE, 1),
(245, 53, 'Mẫu 13 - N / Vる/ Vない + ～に限る …', 'N / Vる/ Vない + ～に限る …', 'Nhất', 'Đưa ra một cách làm, một phương pháp, hành động tối ưu nhất, là phương pháp đã tốt tới “giới hạn”, không thể tốt hơn được', 'N / Vる/ Vない + ～に限る …', 3, 3, TRUE, 1),
(246, 53, 'Mẫu 14 - N / 普通刑 の + ～に対して…', 'N / 普通刑 の + ～に対して…', 'Không giống như', 'Thể hiện sự đối lập giữa hai hành động hoặc sự vật cùng loại', 'N / 普通刑 の + ～に対して…', 3, 4, TRUE, 1),
(247, 53, 'Mẫu 15 - 普通刑 + ～反面…', '普通刑 + ～反面…', 'Mặt khác, ngược lại', 'Mẫu câu này thể hiện hai mặt đối lập của một vấn đề', '普通刑 + ～反面…', 3, 5, TRUE, 1),
(248, 54, 'Mẫu 16 - 普通刑 + ～ 一方 (で)…', '普通刑 + ～ 一方 (で)…', 'Đồng thời, ở mặt khác', 'Thể hiện hai mặt của một vấn đề. Đó là hai mặt có thể xảy ra đồng thời , mang ý trái ngược nhau', '普通刑 + ～ 一方 (で)…', 3, 1, TRUE, 1),
(249, 54, 'Mẫu 17 - ～というより…', '～というより…', 'Thay vì nói là…', 'Mẫu câu này dùng để đưa ra cách nhìn nhận thích hợp hơn về một vấn đề (Có ý so sánh)', '～というより…', 3, 2, TRUE, 1),
(250, 54, 'Mẫu 18 - 普通刑 (Naだ - な) + ～かわりに…', '普通刑 (Naだ - な) + ～かわりに…', 'Mặt khác, thay vì', 'Mẫu câu này vừa có thể sử dụng với hai ý nghĩa: ý nghĩa “đồng thời, mặt khác”', '普通刑 (Naだ - な) + ～かわりに…', 3, 3, TRUE, 1),
(251, 54, 'Mẫu 19 - N・普通刑 + の + ～ためだ/ ～ため(に)…', 'N・普通刑 + の + ～ためだ/ ～ため(に)…', 'Vì', 'Cách nói biểu đạt nguyên nhân, có một chút trang trọng. Cách nói này không thể hiện hi vọng, ý hướng của người nói', 'N・普通刑 + の + ～ためだ/ ～ため(に)…', 3, 4, TRUE, 1),
(252, 54, 'Mẫu 20 - N + による +N...', 'N + による +N...', 'N + による +N...', 'Biểu đạt một tác nhân gây ra hậu quả Với ý nghĩa biểu đạt phương pháp, cách làm', 'N + による +N...', 3, 5, TRUE, 1),
(253, 55, 'Mẫu 21 - N / 普通刑 + ～から…/ことから…', 'N / 普通刑 + ～から…/ことから…', 'Vì, từ', 'Biểu thị lí do này là một sự thật đã diễn ra và phát triển đến một kết quả, hoặc là kết luận của người nói, không dùng để thuyết phục người khác làm một hành động', 'N / 普通刑 + ～から…/ことから…', 3, 1, TRUE, 1),
(254, 55, 'Mẫu 22 - N の / 普通刑 (Naだ -な)+ ～おかげだ/ ～おかげで…', 'N の / 普通刑 (Naだ -な)+ ～おかげだ/ ～おかげで…', 'Nhờ có', 'Dùng để chỉ nguyên do, mang ý nghĩa tích cực. Nhờ có ai, việc gì mà đạt được, hoàn thành được điều gì đó. Một số ít trường hợp mang tính mỉa mai', 'N の / 普通刑 (Naだ -な)+ ～おかげだ/ ～おかげで…', 3, 2, TRUE, 1),
(255, 55, 'Mẫu 23 - N の / 普通刑 (Naだ -な) + ～せいだ/ ～せいで…', 'N の / 普通刑 (Naだ -な) + ～せいだ/ ～せいで…', 'Bởi tại', 'Cũng dùng để chỉ nguyên do nhưng mang ý nghĩa tiêu cực, mang ý “bởi tại”, “chỉ vì”... mà làm hỏng việc gì đó, không làm được việc gì đó hoặc dẫn đến kết quả không tốt', 'N の / 普通刑 (Naだ -な) + ～せいだ/ ～せいで…', 3, 3, TRUE, 1),
(256, 55, 'Mẫu 24 - 普通刑 (Na/Nだ -な) + ～のだから…', '普通刑 (Na/Nだ -な) + ～のだから…', 'Bởi lẽ', 'Nêu ra một lí do mà cả người nói và người nghe đều hiểu, một sự thật hiển nhiên', '普通刑 (Na/Nだ -な) + ～のだから…', 3, 4, TRUE, 1),
(257, 55, 'Mẫu 25 - 普通刑 (Na/Nだ -な) + ～(の)なら…', '普通刑 (Na/Nだ -な) + ～(の)なら…', 'Nếu là…', 'Nhắc lại thông tin hoặc sự việc để đưa ra hành động tiếp theo. Với Naだ / Nだ thì', '普通刑 (Na/Nだ -な) + ～(の)なら…', 3, 5, TRUE, 1),
(258, 56, 'Mẫu 26 - 普通刑 (Na/Nだ -な) + (の)では…', '普通刑 (Na/Nだ -な) + (の)では…', '普通刑 (Na/Nだ -な) + (の)では…', 'Đưa ra một giả định, phán đoán sẽ gây ra kết quả tiêu cực', '普通刑 (Na/Nだ -な) + (の)では…', 3, 1, TRUE, 1),
(259, 56, 'Mẫu 27 - ～さえ～ば… / ～さえ～なら…', '～さえ～ば… / ～さえ～なら…', 'Nếu chỉ cần có…', 'Đưa ra điều kiện tối thiểu nhất để điều gì đó có thể xảy ra', '～さえ～ば… / ～さえ～なら…', 3, 2, TRUE, 1),
(260, 56, 'Mẫu 28 - たとえ～ても…/ たとえ～でも…', 'たとえ～ても…/ たとえ～でも…', 'Cho dù … thì', 'Đưa ra giả định, trường hợp mà dù có nó, một điều gì đó cũng sẽ xảy ra mà không bị ảnh hưởng bởi giả định. Có thể dịch là ‘Cho dù… thì…”, “Kể cả…thì…”', 'たとえ～ても…/ たとえ～でも…', 3, 3, TRUE, 1),
(261, 56, 'Mẫu 29 - ～ば …/ ～たら… / ～なら…', '～ば …/ ～たら… / ～なら…', 'Giá như, chẳng hạn như', 'Đưa ra một giả định không có thật, khả năng thực hiện được không cao', '～ば …/ ～たら… / ～なら…', 3, 4, TRUE, 1),
(262, 56, 'Mẫu 30 - 普通刑 + ～ということだ ・ ～とのことだ', '普通刑 + ～ということだ ・ ～とのことだ', 'Có vẻ như, nghe nói...', 'Là cách truyền đạt lại thông tin, trang trọng hơn 「～だそうだ」. Vế trước thường', '普通刑 + ～ということだ ・ ～とのことだ', 3, 5, TRUE, 1),
(263, 57, 'Mẫu 31 - 普通刑 + ～と言われている', '普通刑 + ～と言われている', 'Có người nói rằng...', 'Sử dụng để thuật lại một thông tin nghe được, biết được,... từ người khác', '普通刑 + ～と言われている', 3, 1, TRUE, 1),
(264, 57, 'Mẫu 32 - 普通刑 + 「～とか」', '普通刑 + 「～とか」', 'Nghe nói là, nghe đồn...', 'Sử dụng khi dựa vào nguồn thông tin mang tính gián tiếp, không chắc chắn', '普通刑 + 「～とか」', 3, 2, TRUE, 1),
(265, 57, 'Mẫu 33 - 普通刑 + ～って', '普通刑 + ～って', '~ Nói rằng...., Tôi nghe bảo rằng...', 'Sử dụng trong câu trích dẫn, là cách nói rút gọn của 「言っている・聞いたなど」', '普通刑 + ～って', 3, 3, TRUE, 1),
(266, 57, 'Mẫu 34 - 普通刑 + ～という', '普通刑 + ～という', 'Nghe nói...', 'Văn phong trang trọng hơn một chút của ～だそうだ, hay sử dụng trong văn viết', '普通刑 + ～という', 3, 4, TRUE, 1),
(267, 57, 'Mẫu 35 - 普通形 + 「～はずがない・～わけがない」', '普通形 + 「～はずがない・～わけがない」', 'Tuyệt đối không, không thể nào...', 'Thể hiện thái độ phủ định mạnh mẽ dựa trên quan điểm, góc nhìn của người nói', '普通形 + 「～はずがない・～わけがない」', 3, 5, TRUE, 1),
(268, 58, 'Mẫu 36 - 普通形（な形―だ／名―だ） + 「～とは限らない」', '普通形（な形―だ／名―だ） + 「～とは限らない」', 'Chưa chắc đã, không hẳn là....', 'Sử dụng để phủ định lại một quan điểm, một ý kiến (mang tính chủ quan của người nói)', '普通形（な形―だ／名―だ） + 「～とは限らない」', 3, 1, TRUE, 1),
(269, 58, 'Mẫu 37 - ではない', 'ではない', 'Không phải là, không hẳn là...', 'Dùng để phủ định một phát ngôn hay một vấn để, quan điểm, dựa trên các yếu tố phong không trang trọng', 'ではない', 3, 2, TRUE, 1),
(270, 58, 'Mẫu 38 - 「～ないことはない」', '「～ないことはない」', 'Không thể nói rằng không, cũng', 'Thường được sử dụng để khẳng định một cách nhẹ nhàng qua hình thức phủ định hai lần', '「～ないことはない」', 3, 3, TRUE, 1),
(271, 58, 'Mẫu 39 - 「～ことは～が、・・・」', '「～ことは～が、・・・」', 'Dù là thế, nhưng....', 'Cách kết hợp: 動・刑普通刑（ナ刑だーな） ＋ ことは ＋ 動・刑普通刑・丁寧刑 ＋ が Sử dụng khi muốn diễn đạt ý rằng sự việc ấy là đúng là như vậy thật nhưng không quan trọng lắm', '「～ことは～が、・・・」', 3, 4, TRUE, 1),
(272, 58, 'Mẫu 40 - 「～てもらいたい・～ていただきたい・～てほしい」', '「～てもらいたい・～ていただきたい・～てほしい」', '~Muốn được...', 'Cách kết hợp: 動―て刑 / ない刑＋で ＋ もらいたい・いただきたい・ほしい Cách dùng: Dùng khi muốn nhờ vả, yêu cầu đối phương làm gì đó cho mình (một', '「～てもらいたい・～ていただきたい・～てほしい」', 3, 5, TRUE, 1),
(273, 59, 'Mẫu 41 - + いただきたい', '+ いただきたい', '+ いただきたい', 'Cách kết hợp: Dùng để bày tỏ nguyện vọng, mong muốn được người khác sắp xếp, cho phép mình được làm gì đó', '+ いただきたい', 3, 1, TRUE, 1),
(274, 59, 'Mẫu 42 - 普通刑（過去形だけ） ＋ ら', '普通刑（過去形だけ） ＋ ら', '普通刑（過去形だけ） ＋ ら', 'Cách kết hợp: Bày tỏ một mong muốn một việc gì đó sẽ xảy ra, tuy nhiên điều đó không thành hiện thực nếu chỉ phụ thuộc vào mong muốn của bản thân người nói Cách kết hợp: Gợi ý người khác làm gì/ không nên làm gì', '普通刑（過去形だけ） ＋ ら', 3, 2, TRUE, 1),
(275, 59, 'Mẫu 43 - ＊ 例外', '＊ 例外', 'くれる → くれ', '* Cách kết hợp: * Là một cách thể hiện mệnh lệnh cấm đoán mạnh, thường chỉ có nam giới sử dụng. Ngoài ra, còn dùng trong một số trường hợp như la hét cổ vũ trong thể thao, in ấn trên các banner, khẩu hiệu,... hoặc hướng dẫn ý nghĩa của biển báo, tín hiệu...', '＊ 例外', 3, 3, TRUE, 1),
(276, 59, 'Mẫu 44 - 動―辞書刑/ない刑 + ～こと', '動―辞書刑/ない刑 + ～こと', 'Phải...~ Không được/ Cấm...', 'Sử dụng khi đưa ra mệnh lệnh, lời cảnh báo hoặc truyền tải lại thông điệp từ các biển hiệu, thông báo', '動―辞書刑/ない刑 + ～こと', 3, 4, TRUE, 1),
(277, 59, 'Mẫu 45 - ＊例外', '＊例外', 'する → するべきだ ・ するべき', '* Cách kết hợp: * Sử dụng để thể hiện quan điểm của người nói rằng việc đó không phải là quy tắc nhưng nên làm như vậy, nếu không sau này tất yếu sẽ cảm thấy hối hân, nuối tiếc', '＊例外', 3, 5, TRUE, 1),
(278, 60, 'Mẫu 46 - V + ～たらどうか', 'V + ～たらどうか', 'Nếu... thì thế nào', 'Sử dụng khi đưa ra lời khuyên cho đối phương, có thể có hàm ý trách móc về một sự việc đã xảy ra trong quá khứ, tại sao lại không làm việc này thay vì việc kia', 'V + ～たらどうか', 3, 1, TRUE, 1),
(279, 60, 'Mẫu 47 - 動―辞書刑/ない刑 ＋ 「～ようにする・～ようにしている」', '動―辞書刑/ない刑 ＋ 「～ようにする・～ようにしている」', '~Chắc chắn làm.../ Cố gắng làm...', 'Biểu hiện sự quyết tâm, nỗ lực thể tạo lập được một thói quen, một hành vi (mang tính giải pháp), mang ý chí cao của người nói', '動―辞書刑/ない刑 ＋ 「～ようにする・～ようにしている」', 3, 2, TRUE, 1),
(280, 60, 'Mẫu 48 - 動―う・よう刑 ＋ 「～（よ）うとする」', '動―う・よう刑 ＋ 「～（よ）うとする」', '~Thử làm gì... ~ Cố gắng làm gì...~', 'Cách dùng: Sử dụng để diễn đạt những điều mình muốn làm, đề cập đến những sử dụng', '動―う・よう刑 ＋ 「～（よ）うとする」', 3, 3, TRUE, 1),
(281, 60, 'Mẫu 49 - 辞書刑 ＋ ～ことにする', '辞書刑 ＋ ～ことにする', 'Quyết định', 'Quyết định làm gì/ không làm gì – sự việc do tự bản thân mình quyết định. Không dùng với thể khả năng và ý chí', '辞書刑 ＋ ～ことにする', 3, 4, TRUE, 1),
(282, 60, 'Mẫu 50 - 辞書刑 + ～ ・ ～ことにしている', '辞書刑 + ～ ・ ～ことにしている', 'Quyết định', 'Dùng để diễn tả thói quen mà mình đang lên kế hoạch thực hiện, cố gắng để duy trì với quyết tâm cao', '辞書刑 + ～ ・ ～ことにしている', 3, 5, TRUE, 1),
(283, 61, 'Mẫu 51 - 辞書刑 + 「～ことになる」', '辞書刑 + 「～ことになる」', 'Được quyết định là...', 'Dùng để nói về các thói quen, quy tắc, dự định đã được định trước, nhấn mạnh việc đã được người khác quyết định – không mang tính chủ quan, ý chí', '辞書刑 + 「～ことになる」', 3, 1, TRUE, 1),
(284, 61, 'Mẫu 52 - 辞書刑 + 「～ことになっている」', '辞書刑 + 「～ことになっている」', 'Chỉ được...', 'Diễn tả các tập quán, quy tắc, dự định (xảy ra không liên quan đến ý chỉ của người nói)', '辞書刑 + 「～ことになっている」', 3, 2, TRUE, 1),
(285, 61, 'Mẫu 53 - 「～みたい」', '「～みたい」', '「～みたい」', 'N/V ＋ みたい（だ）: Hình như… (Diễn tả hành động, sự việc theo suy đoán của người nói. Điều đó không hoàn toàn là chính xác nhưng từ kinh nghiệm thì có thể suy luận ra như vậy) N ＋ みたい（だ）: Giống như là... (Biểu thị hành động, sự vật, sự việc cứ như thể là….', '「～みたい」', 3, 3, TRUE, 1),
(286, 61, 'Mẫu 54 - 「～らしい」', '「～らしい」', '「～らしい」', 'N/V/A-い/A-な ＋ らしい： ~Có vẻ là, nghe nói là… (Truyền đạt lại những gì nghe được từ người khác hoặc suy luận từ một thông tin nào đó) N ＋ らしい: ~ Giống như… (Giống về bản chất, thứ thực sự có ở sự vật, hiện tượng đó. Hầu như là sự đánh giá tích cực)', '「～らしい」', 3, 4, TRUE, 1),
(287, 61, 'Mẫu 55 - 「～そうだ」', '「～そうだ」', '~Nghe nói là…', 'Truyền đạt lại nguyên văn những gì nghe được từ ai đó cho đối phương, thường không thay đổi hay thêm bớt thông tin', '「～そうだ」', 3, 5, TRUE, 1),
(288, 62, 'Mẫu 56 - N・Vます + 「～っぽい」', 'N・Vます + 「～っぽい」', 'Hệt như...', 'Miêu tả một người, sự vật, hiện tượng,… có yếu tố, tính chất là như vậy (nhưng trên thực tế thì 2 đối tượng được nêu ra hoàn toàn khác nhau)', 'N・Vます + 「～っぽい」', 3, 1, TRUE, 1),
(289, 62, 'Mẫu 57 - V-た ＋ 「～たばかり」', 'V-た ＋ 「～たばかり」', '~ Vừa mới...', 'Dùng để thể hiện hành động vừa mới xảy ra, cách thời điểm hiện tại chưa lâu theo QUAN ĐIỂM và CẢM NHẬN của người nói. Sử dụng cả khi khoảng thời gian không thực sự ngắn nhưng người nói có dụng ý rằng nó ngắn ngủi đối với mình', 'V-た ＋ 「～たばかり」', 3, 2, TRUE, 1),
(290, 62, 'Mẫu 58 - V-た + 「～たところ」', 'V-た + 「～たところ」', '~Vừa mới.... ~Ngay sau khi...', 'Dùng khi muốn đưa ra một trường hợp hay một hành động vừa mới xảy ra, theo quan điểm của người nói. Và chỉ sử dụng được cho những hành động chính xác là vừa mới xảy ra', 'V-た + 「～たところ」', 3, 3, TRUE, 1),
(291, 62, 'Mẫu 59 - 普通刑 + ～はずだ', '普通刑 + ～はずだ', '~ Chắc là...', 'Sự phỏng đoán mang tính chủ quan của người nói nhưng dựa trên cơ sở khá vững chắc và mức độ chính xác cao', '普通刑 + ～はずだ', 3, 4, TRUE, 1),
(292, 62, 'Mẫu 60 - 普通刑 ＋ ～わけだ', '普通刑 ＋ ～わけだ', '~ Chắc là, vì vậy mà, chẳng nào...', 'Không phải là phỏng đoán mà là suy luận, lý giải của người nói về một hiện tượng, quá trình nào đó (nhấn mạnh rằng nó là đương nhiên)', '普通刑 ＋ ～わけだ', 3, 5, TRUE, 1),
(293, 63, 'Mẫu 61 - Tôn kính ngữ - 尊敬語', 'Tôn kính ngữ - 尊敬語', 'Tôn kính ngữ - 尊敬語', 'Sử dụng khi đề cập tới hành động, trạng thái của người ở vị trí cao hơn, ở trên mình hoặc những đối tượng đặc biệt như khách hàng, đối tác... trong những bối cảnh, trường hợp trang trọng Các cách biến đổi: Lưu ý: Thường tôn kính ngữ sẽ kết hợp với các cách nói lịch sự như: 「 ～ ていただ', 'Tôn kính ngữ - 尊敬語', 3, 1, TRUE, 1),
(294, 63, 'Mẫu 62 - Khiêm nhường ngữ', 'Khiêm nhường ngữ', 'Khiêm nhường ngữ', 'Khiêm nhường ngữ * Sử dụng khi đề cập đến hành động, tình trạng, đồ vật của mình với những người trên, với các đối tượng đặc biệt như khách hàng, đối tác,..., thể hiện sự khiêm nhường, khiêm tốn, lịch sự và tôn trọng đối phương * Các cách biến đổi:', 'Khiêm nhường ngữ', 3, 2, TRUE, 1)
ON DUPLICATE KEY UPDATE
    grammar_chapter_id = VALUES(grammar_chapter_id),
    title = VALUES(title),
    pattern = VALUES(pattern),
    meaning_vi = VALUES(meaning_vi),
    explanation = VALUES(explanation),
    formation = VALUES(formation),
    jlpt_level_id = VALUES(jlpt_level_id),
    display_order = VALUES(display_order),
    is_published = VALUES(is_published),
    version = VALUES(version);

INSERT INTO grammar_examples (id, grammar_lesson_id, japanese_text, reading, meaning_vi, display_order) VALUES
(297, 233, '日本にいるうちに一度富士山に登ってみたい。', NULL, 'Trong lúc còn đang ở Nhật, tôi muốn thử leo núi Phú Sĩ một lần.', 1),
(298, 233, '明るいうちに庭の掃除をしてしまおう。', NULL, 'Hãy dọn vệ sinh vườn cho xong nhân lúc trời còn sáng.', 2),
(299, 234, 'お母さんが昼寝をしている間、 子どもたちはテレビを見ていた。', NULL, 'Trong khi người mẹ đang ngủ trưa thì bọn trẻ ngồi xem tivi.', 1),
(300, 234, '私が旅行で留守の間、うちの犬の世話をお願いできないでしょうか。', NULL, 'Trong khi tôi vắng nhà đi du lịch, chị có thể làm ơn chăm sóc con chó giúp tôi không.', 2),
(301, 235, '運転免許を取ってからでなければ車を運転してはいけない。', NULL, 'Nếu chưa có bằng thì không được phép lái xe.', 1),
(302, 235, '病気が治ってからでなければ激しい運動は無理だ。', NULL, 'Nếu chưa khỏi ốm thì chưa thể vận động mạnh được.', 2),
(303, 236, 'ロケットは間もなく飛び立つところです。緊張の瞬間です。', NULL, 'Quả tên lửa chuẩn bị được phóng đi rồi. Khoảnh khắc này thật là hồi hộp.', 1),
(304, 236, '試験中、となりの人の答えを見ているところを先生に注意された。', NULL, 'Trong giờ thi, tôi bị cô giáo nhắc đúng lúc đang nhìn bài bạn bên cạnh.', 2),
(305, 237, '交番で 教えてもらったとおりに歩いていったので、迷わず会場に着いた。', NULL, 'Nhờ đi theo chỉ dẫn của cảnh sát, tôi đã đến được hội trường mà không bị lạc.', 1),
(306, 237, 'サッカーの試合の結果はわたしたちの期待どおりだった。', NULL, 'Kết quả trận bóng đúng như những gì tôi mong đợi.', 2),
(307, 238, 'わたしの帰宅時間は毎日違う。日によって 夜中になることもある。', NULL, 'Giờ giấc về nhà của tôi mỗi ngày một khác nhau. Tùy hôm, có lúc đêm muộn mới về được.', 1),
(308, 238, '国によって習慣が違う。', NULL, 'Tùy từng nước, tập quán lại khác nhau.', 2),
(309, 239, 'この地方は台風が来るたびに大水の害が起こる。', NULL, 'Khu vực này mỗi khi có bão lại phải chịu thiệt hại do ngập lụt.', 1),
(310, 239, 'このチームは試合のたびに強くなっていく。', NULL, 'Đội (bóng) nay mạnh dần lên sau mỗi trận đấu.', 2),
(311, 240, 'ものが増えれば増えるほど整理が大変になる。', NULL, 'Càng nhiều đồ thì việc sắp xếp càng khó hơn.', 1),
(312, 240, '忙しい人ほど時間の使い方が上手だ。', NULL, 'Những người càng bận rộn thì càng giỏi quản lý thời gian hơn.', 2),
(313, 241, '散歩のついでにこのはがきをポストに出してきた。', NULL, 'Nhân tiện ra ngoài đi dạo, tôi đã đi gửi bưu thiếp.', 1),
(314, 241, 'インタネットで本を注文したついでに新しく出たDVDも調べた。', NULL, 'Nhân tiện đặt mua sách trên mạng, tôi cũng thử tìm hiểu đĩa DVD mới ra.', 2),
(315, 242, '天気予報によると、今日は台風ぐらい風が吹くそうだ。', NULL, 'Theo dự báo thời tiết, hôm nay có gió mạnh như bão.', 1),
(316, 242, 'さっき地震があった。本棚が倒れるかと思うほど激しく揺れた。', NULL, 'Vừa mới có động đất. Mặt đất rung mạnh đến mức tôi tưởng kệ sách bị đổ.', 2),
(317, 243, 'あしたも漢字テストがある。テストほどいやなものはない。', NULL, 'Ngày mai lại có bài kiểm tra chữ Hán. Tôi ghét nhất là kiểm tra.', 1),
(318, 244, '気が合わない人といっしょに生活するぐらいなら、このまま独身でいたい。', NULL, 'Nếu phải sống với một người không hợp, thì thà độc thân mãi còn hơn.', 1),
(319, 244, 'やせるために好きなケーキをがまんするくらいなら、今の体型のままでかまわない。', NULL, 'Nếu để có thể giảm cân mà phải nhịn ăn loại bánh mình rất thích, thì tôi cứ giữ nguyên cân nặng như bây giờ cũng được.', 2),
(320, 245, '風邪(かぜ)が流行っているときは、人が多いところに行かないに限る。', NULL, 'Khi đang có dịch cúm, thì tốt nhất không nên đến những chỗ đông người.', 1),
(321, 245, '湖の写真を取るならこの場所に限ります。 すてきな写真をとれますよ。', NULL, 'Nếu chụp ảnh cái hồ này thì đứng chỗ này là tốt nhất. Từ đây có thể chụp đươc những bức ảnh đẹp.', 2),
(322, 246, '大阪では大雨だったのに対して、東京はいい天気だった。', NULL, 'Khác với ở Osaka trời mưa thì ở Tokyo trời rất đẹp.', 1),
(323, 246, '外遊びが好きな長男に対して、次男は家の中で遊ぶことが好きだ。', NULL, 'Khác với đứa con cả thích ra ngoài chạy nhảy thì người con thứ lại thích chơi đùa trong nhà.', 2),
(324, 247, '都会の生活は面白いことが多い反面、ストレスとも多い。', NULL, 'Cuộc sống ở thành phố rất thú vị, tuy nhiên cũng nhiều stress.', 1),
(325, 247, '一人旅（ひとりたび）は気楽な反面、なんでも一人でやらなければならないので、不便だ。', NULL, 'Đi du lịch một mình thì rất thoải mái, nhưng mặt khác cũng bất tiện vì tự mình phải làm tất cả mọi việc.', 2),
(326, 248, '子どもが生まれてうれしかった一方で、重い責任も感じだ。', NULL, 'Tôi rất vui vì con vừa chào đời, nhưng đồng thời cũng cảm thấy trách nhiệm nặng nề hơn.', 1),
(327, 248, '会では自分の意見を言う一方、ほかの人の話もよく聞いてください。', NULL, 'Trong cuộc họp, ngoài việc phát biểu ý kiến thì đồng thời cũng phải nghe người khác nói.', 2),
(328, 249, '僕と彼がともだち？いや、ぼくたちはともだちというよりいい競争相手なんだよ。', NULL, 'Tôi và anh ta là bạn á? Không, chúng tôi đúng ra là những đối thủ cạnh tranh hơn là những người bạn.', 1),
(329, 249, 'Aさんは歩くのは速い。歩くというより走るという感じだ。', NULL, 'Anh A đi bộ rất nhanh. Cảm giác như là anh ấy chạy chứ không phải đi nữa.', 2),
(330, 250, 'Aさんに英語を教えてもらっているかわりに、Aさんの仕事を手伝っている。', NULL, 'Tôi nhờ anh A dạy tiếng Anh, đồng thời cũng trợ giúp anh ấy trong công việc.', 1),
(331, 250, '今度の正月はいつものようにふるさとに帰るかわりに、両親と海外旅行をしたい。', NULL, 'Tết năm nay, thay vì về quê như mọi khi, tôi muốn đi du lịch nước ngoài cùng bố mẹ.', 2),
(332, 251, '出張のため、明日の会議は欠席させていただきます。', NULL, 'Vì phải đi công tác, tôi xin phép vắng mặt cuộc họp ngày mai.', 1),
(333, 251, 'この村には医者がないために、病気のときはとなりの町で行かなければならない。', NULL, 'Vì ngôi làng này không có bệnh viện nên khi bị ốm phải đi sang làng bên cạnh.', 2),
(334, 252, 'うちの工場では、材料不足によってたたみの生産はもうできなかった。', NULL, 'Ở xưởng của chúng tôi, vì thiếu nguyên liệu nên không thể sản xuất chiếu được nữa.', 1),
(335, 252, '今年のインフルエンザは、今までにない型のウイルスによるものである。', NULL, 'Dịch cúm năm nay là do một loại virus chưa từng xuất hiện gây nên.', 2),
(336, 253, 'わずかな誤解から友達の関係が悪くなってしまった。', NULL, 'Chỉ vì hiểu nhầm mà tình cảm bạn bè bị rạn nứt.', 1),
(337, 253, '日本語の授業でとなりの席になったことから、わたしたちは親したくなった。', NULL, 'Vì ngồi cạnh nhau trong giờ học tiếng Nhật mà chúng tôi đã trở nên thân thiết.', 2),
(338, 254, '天気の良い日が続いたおかげで、工事が早く終わった。', NULL, 'Nhờ thời tiết đẹp kéo dài nên việc thi công đã hoàn thành sớm.', 1),
(339, 254, '先生が薬をくれたので、おかげさまで、元気になりました。どうもありがとうございました。', NULL, 'Nhờ có thuốc của cô giáo cho mà em đã khỏe lại. Em xin cảm ơn cô!', 2),
(340, 255, '最近忙しかったせいで、かなり疲れている。', NULL, 'Dạo này vì bận rộn nên tôi khá mệt mỏi.', 1),
(341, 255, '隣の部屋の音楽の音のせいで、勉強に集中できない。', NULL, 'Tại tiếng nhạc của phòng bên cạnh mà tôi không thể tập trung vào học được.', 2),
(342, 256, '世界が広いのだから、いろいろな習慣があるのは当然だ。', NULL, 'Bởi vì thế giới này rộng lớn, nên đương nhiên là có nhiều tập quán khác nhau.', 1),
(343, 257, 'その箱、もう使わないんですか、使わないなら私にください。', NULL, 'Anh không dùng cái hộp đó nữa à. Nếu không dùng nữa thì cho tôi nhé.', 1),
(344, 257, 'その本、読んでしまったのなら私に貸してくれませんか。', NULL, 'Nếu anh đọc xong cuốn sách đó rồi thì hãy cho tôi mượn nhé.', 2),
(345, 258, 'そんな無責任な態度ではみんなにきらわれますよ。', NULL, 'Nếu anh có thái độ vô trách nhiệm như thế thì sẽ bị mọi người ghét đấy.', 1),
(346, 258, 'Aさんは手術したばかりだから、お見舞いに行ってはかえって迷惑だ。', NULL, 'Vì anh A mới phẫu thuật xong, nên nếu bây giờ đi thăm thì ngược lại còn gây phiền toái cho anh ấy đấy.', 2),
(347, 259, '体さえ丈夫ならどんなことにも挑戦できる。', NULL, 'Chỉ cần có sức khỏe thì tôi có thể trải qua bất cứ thử thách nào.', 1),
(348, 259, '「ごめんなさい」 さえ言えば、 相手は許してくれるだろう。', NULL, 'Chỉ cần nói xin lỗi thì sẽ được tha thứ thôi.', 2),
(349, 260, 'たとえ周りの人たちにどんなに反対されても、僕はプロの歌集になりたい。', NULL, 'Kể cả những người xung quanh phản đối thế nào thì tôi vẫn muốn trở thành ca sĩ chuyên nghiệp.', 1),
(350, 260, 'たとえ高くても、仕事に必要なものは買わなければならない。', NULL, 'Dù có đắt thế nào đi nữa thì cũng phải mua những thứ cần dùng cho công việc.', 2),
(351, 261, 'お金とひまがあればわたしも海外旅行するんだけど。。。', NULL, 'Giá mà có thời gian và có tiền, tôi cũng sẽ đi du lịch nước ngoài.', 1),
(352, 261, 'もし寝坊していたらこの飛行機に乗れなかった。 間に合わってよかった。', NULL, 'Nếu ngủ quá giờ thì đã không lên được máy bay rồi. May là đến đúng giờ.', 2),
(353, 262, '市のお知らせによれば、この道路は来週から工事が始まるということだ。', NULL, 'Theo như thông báo của quận thì hình như từ tuần sau con đường này sẽ bắt đầu được thi công.', 1),
(354, 262, '店の人の話では、この地方の米はとてもおいしいということだ。', NULL, 'Theo người bán hàng nói thì gạo của vùng này dường như rất ngon.', 2),
(355, 263, '今年は黒い服が流行（りゅうこう）するといわれている。', NULL, 'Người ta nói rằng năm nay quần áo màu đen sẽ được thịnh hành.', 1),
(356, 263, '納豆は体にいいといわれている。', NULL, 'Người ta nói rằng món natto tốt cho sức khỏe.', 2),
(357, 264, '来月また出張だとか。今度はどちらに行かれるんですか。', NULL, 'Nghe đồn tháng sau anh lại đi công tác. Lần này không biết anh sẽ đi đâu?', 1),
(358, 264, '足の裏を日に当てると健康にいいとか。本当だろうか。', NULL, 'Nghe nói nếu phơi lòng bàn chân ra nắng sẽ khỏe hơn. Không biết có thật không nhỉ.', 2),
(359, 265, '小川さん、今日は休むって言ってたよ。', NULL, 'Tôi có nghe anh Ogawa nói rằng hôm nay nghỉ.', 1),
(360, 265, '駅前にタイ料理レストランができたんだって。行ってみようよ。', NULL, 'Nghe nói rằng một quán ăn Thái mới mở trước nhà ga. Lúc nào đi ăn thử nhé.', 2),
(361, 266, 'この辺りは昔、広い野原（のはら）だったという。', NULL, 'Nghe nói vùng này trước đây là một thảo nguyên rộng lớn.', 1),
(362, 266, 'この祭りは村で古くから行われてきたという。', NULL, 'Nghe nói lễ hội này được tổ chức từ xa xưa tại ngôi làng này.', 2),
(363, 267, 'ちゃんと約束したんだから、彼がこないはずがない。 どうしたのかな。', NULL, 'Đã hẹn rồi thì không có chuyện anh ta không đến. Không biết có chuyện gì không.', 1),
(364, 267, '試合に勝っために目に練習しているのだ。 練習が厳しくないわけがない。', NULL, 'Tôi đang tập luyện để có thể thắng trận đấu tới đây. Việc luyện tập chắc chắn là không thể không nghiêm khắc được.', 2),
(365, 268, 'この歌は古くから歌われているが、日本人がみんな知っているとは限らない。', NULL, 'Bài hát này đã có từ lâu nhưng không hẳn là người Nhật nào cũng biết.', 1),
(366, 268, '値段が高いものが必ず質がいいとは限らない。', NULL, 'Không phải cứ đồ đắt tiền là chất lượng sẽ tốt.', 2),
(367, 269, '長い間本をお借りしたままでしたが、忘れていたわけではありません。', NULL, 'Tôi đã mượn sách suốt mà không trả nhưng không phải là do quên. (có thể do bận không có thời gian)', 1),
(368, 269, 'いつでも電話に出られるわけではありません。連絡はメールでお願いします。', NULL, 'Không phải lúc nào tôi cũng trả lời điện thoại được. Làm ơn hãy liên lạc bằng email.', 2),
(369, 270, 'ここから駅まで歩けないことはありませんが、かなり時間がかかりますよ。', NULL, 'Từ đây có thể đi bộ ra ga được, nhưng khá là mất thời gian.', 1),
(370, 270, 'この店のカレーもおいしくないことはないが、私はもっと辛いのが好きだ。', NULL, 'Không phải cari của quán không ngon, mà tôi thích loại cay hơn.', 2),
(371, 271, '彼からの手紙は読んだことは読んだんですが、 意味がよくわかりませんでした。', NULL, 'Dù là anh ấy đã đọc rồi, nhưng không hiểu ý nghĩa bức thư cho lắm.', 1),
(372, 271, '私は泳げることは泳げますが、長い距離（きょり）はだめなんです。', NULL, 'Đúng là tôi biết bới, nhưng không thể bơi xa được.', 2),
(373, 272, 'この書類、ちょっと見ていただきたいんですが、今よろしいでしょうか。', NULL, 'Tôi muốn nhờ ông xem qua chỗ hồ sơ này, không biết bây giờ có tiện không?', 1),
(374, 272, 'この仕事はだれにも手伝ってもらいたくない。 自分一人でやりたい。', NULL, 'Tôi không muốn ai giúp làm công việc này cả, mà muốn tự mình làm.', 2),
(375, 273, 'すみません、今日は体調が悪いので、早く帰らせていただきたいのですが・・・', NULL, 'Xin lỗi, hôm nay tôi không được khỏe nên ông có thể cho tôi về sớm không?', 1),
(376, 274, '最近ずっと体の調子が悪い。悪い病気でなければいいが・・・。', NULL, 'Gần đây sức khỏe không được tốt. Mong rằng không phải là bệnh nặng…', 1),
(377, 274, '【卒業式】先生：「このクラスも今日でお別れです。いつかまたみんなで会えるといいですね。」', NULL, '(Tại buổi lễ tốt nghiệp) Cô giáo: Lớp chúng ta hôm nay chia tay tại đây. Sau này mong rằng mọi người sẽ có dịp gặp lại nhau. B. ~ nên...', 2),
(378, 275, '犬に「座れ。」とめいれいした。 犬は命令に従（したが）った。', NULL, 'Tôi ra lệnh cho con chó ngồi xuống và nó đã nghe theo mệnh lệnh.', 1),
(379, 275, '【試合で】監督（かんとく）「走れ、走れ！」', NULL, '(Trong trận đấu) Huấn luyện viên: Chạy nhiều nữa lên!', 2),
(380, 276, '申込書を書く前に注意書きをよく読むこと。', NULL, 'Trước khi viết đơn đăng kí phải đọc kĩ tờ hướng dẫn.', 1),
(381, 276, '教室を出る前に、電気を消すこと。', NULL, 'Trước khi ra khỏi lớp, hãy tắt điện.', 2),
(382, 277, 'せっかく会社に入っただから、簡単にやめるべきではない。', NULL, 'Đã mất công xin vào công ty rồi, đừng nên bỏ cuộc quá dễ dàng.', 1),
(383, 277, 'これは大事なことですから、もう少し話合ってから決めるべきだとおもいます。', NULL, 'Vì đây là việc quan trọng, nên tôi nghĩ rằng anh nên bàn bạc thêm chút nữa rồi hãy quyết định.', 2),
(384, 278, '体のことが心配なら、 一度健康診断を受けたらどうでしょうか。', NULL, 'Nếu lo lắng về sức khỏe thì hãy đi khám thử một lần, anh thấy sao?', 1),
(385, 278, '悪いのはそっちですよ。 一言謝ったらどうですか。', NULL, 'Anh mới là người có lỗi. Hãy xin lỗi một câu thì sao?', 2),
(386, 279, '健康のために、毎日一時間は歩くようにしている。', NULL, 'Hàng ngày tôi đều cố gắng đi bộ một tiếng cho khỏe mạnh.', 1),
(387, 279, '日本語が上手に話せるために、できるだけ会話を練習するようにしている。', NULL, 'Để nói được tiếng Nhật, ngày nào tôi cũng cố tập luyện.', 2),
(388, 280, '父に事情を説明しようとしたが、父は話を聞こうとはしなかった。', NULL, 'Tôi định giải thích rõ sự tình cho bố, nhưng bố tôi không hề có ý định muốn nghe.', 1),
(389, 280, '明日は大切なテストなので早く寝るうとしても、なかなか眠れなかった。', NULL, 'Vì mai có bài kiểm tra quan trọng nên tôi cố đi ngủ sớm, nhưng mãi mà không ngủ được.', 2),
(390, 281, 'コセイセンタはハノイに一番良さそうなので、ここで日本語を勉強することにします。', NULL, 'Trung tâm nhật ngữ Kosei có vẻ rất tốt nên tôi quyết định học tiếng Nhật ở đây.', 1),
(391, 281, '冷蔵庫がこわれたので、新しいのを買うことにした。', NULL, 'Vì tủ lạnh hỏng mất rồi nên tôi quyết định mua cái mới.', 2),
(392, 282, '健康のため、毎朝牛乳を飲むことにしている。', NULL, 'Để khỏe mạnh, tôi tập duy trì thói quen uống sữa mỗi sáng.', 1),
(393, 282, '部長の言葉はいつもとてもきびしいが、わたしは気にしないことにしている。', NULL, 'Lời nói của trưởng phòng thường rất nghiêm khắc, nhưng tôi quyết định không quan tâm.', 2),
(394, 283, '本校では、教室で日本語しか話せないことになる。', NULL, 'Ở trường này, trong lớp học sẽ chỉ được dùng tiếng Nhật.', 1),
(395, 283, 'この仕事を引き受けると他の町へ引っ越すことになる。', NULL, 'Nếu nhận công việc này thì phải chuyển nhà đến thành phố khác.', 2),
(396, 284, '本校では、教室では日本語しか話せないことになっている。', NULL, 'Ở trường này, trong lớp học người ta vẫn chỉ nói tiếng Nhật.', 1),
(397, 284, '法律では、２０歳未満はお酒を飲んではいけなおことになっている。', NULL, 'Theo quy định của pháp luật, những người dưới 20 tuổi thì không được uống rượu.', 2),
(398, 285, '部長は怒ると怖いみたいだ。', NULL, 'Hình như trưởng phòng mà tức giận thì rất đáng sợ.', 1),
(399, 285, 'こんなに遅かったら、たぶん、田中さんは来ないみたいだね。', NULL, 'Muộn thế này rồi, hình như anh Tanaka sẽ không đến nữa.', 2),
(400, 286, '部長は怒ると怖らしい', NULL, 'Khi trưởng phòng tức giận hình như là rất đáng sợ.', 1),
(401, 286, '田中さんは来ないらしいよ。', NULL, 'Hình như anh Tanaka không đến đâu.', 2),
(402, 287, '部長は怒るとそうだ。', NULL, 'Nghe nói trưởng phòng mà tức giận thì rất đáng sợ.', 1),
(403, 287, '田中さんって来ないそうだよ。', NULL, 'Anh Tanaka nghe nói sẽ không đến đâu.', 2),
(404, 288, '彼女はわがままばかり言って、子供っぽい人だ。', NULL, 'Anh ta toàn nói những điều ngang bướng giống như trẻ con vậy.', 1),
(405, 288, '弟はあきっぽくて、何でも途中でやめてしまう。', NULL, 'Em trai tôi làm gì cũng bỏ dở giữa chừng, dường như là do chán nản.', 2),
(406, 289, 'でき上がったばかりのケーキをみんなで食べた。', NULL, 'Mọi người cùng ăn cái bánh vừa mới ra lò.', 1),
(407, 289, 'さっきご飯を食べたばかりなのに、もうおなかがすいてしまった。', NULL, 'Vừa ăn lúc nãy xong, bây giờ lại thấy đói rồi.', 2),
(408, 290, 'もしもし、今、駅に着いたところです。', NULL, 'Alo, tôi vừa đến nhà ga xong.', 1),
(409, 290, 'ケーキができ上がったところへ子供たちが帰って来た。', NULL, 'Lúc vừa làm xong cái bánh thì bọn trẻ về.', 2),
(410, 291, 'いい薬を使ったから、きっとすぐ治るはずですよ。', NULL, 'Nếu uống loại thuốc tốt, chắc chắn sẽ khỏi ngay thôi.', 1),
(411, 291, 'この商品は人気があるから、十日ぐらいで売り切れるはずだ。', NULL, 'Sản phẩm này rất được ưa chuộng nên chắc chắn sẽ bán hết trong vòng 10 ngày.', 2),
(412, 292, 'なるほど、この薬を使えば早く治るわけですね。じゃあ使ってみましょう。', NULL, 'À ra là vậy, uống loại thuốc này sẽ nhanh khỏi hơn. Vậy thì tôi sẽ uống thử.', 1),
(413, 292, '彼はあんなに食べたら、太るわけだ。 なるほどな。 わかった。 わかった。', NULL, 'Anh ta ăn nhiều thế, vì vậy mới béo. Tôi đã hiểu lý do rồi.', 2),
(414, 293, '今晩はお宅にいらっしゃるでしょう。', NULL, '(Tối nay ông có nhà không ạ?)', 1),
(415, 293, '和食を召し上がります。お酒も召し上がります。', NULL, 'Ông ấy ăn đồ Nhật và cả uống rượu nữa.', 2),
(416, 294, '（先生の）ご本をお借りしてもよろしいでしょうか。', NULL, 'Em mượn sách của cô được không ạ?', 1),
(417, 294, 'ご返信をお待ちいたしております。', NULL, 'Tôi sẽ đợi hồi âm của anh.', 2)
ON DUPLICATE KEY UPDATE
    grammar_lesson_id = VALUES(grammar_lesson_id),
    japanese_text = VALUES(japanese_text),
    reading = VALUES(reading),
    meaning_vi = VALUES(meaning_vi),
    display_order = VALUES(display_order);
