SET NAMES utf8mb4;

DELETE ge FROM grammar_examples ge JOIN grammar_lessons gl ON gl.id = ge.grammar_lesson_id WHERE gl.jlpt_level_id = 4;

DELETE FROM grammar_lessons WHERE jlpt_level_id = 4;

DELETE FROM grammar_chapters WHERE jlpt_level_id = 4;

INSERT INTO grammar_chapters (id, jlpt_level_id, chapter_number, name, description, display_order, is_published, version) VALUES
(64, 4, 1, 'Bài 1', 'Ngữ pháp N2 - Bài 1 (5 mẫu, lesson 295-299)', 1, TRUE, 1),
(65, 4, 2, 'Bài 2', 'Ngữ pháp N2 - Bài 2 (8 mẫu, lesson 300-307)', 2, TRUE, 1),
(66, 4, 3, 'Bài 3', 'Ngữ pháp N2 - Bài 3 (6 mẫu, lesson 308-313)', 3, TRUE, 1),
(67, 4, 4, 'Bài 4', 'Ngữ pháp N2 - Bài 4 (7 mẫu, lesson 314-320)', 4, TRUE, 1),
(68, 4, 5, 'Bài 5', 'Ngữ pháp N2 - Bài 5 (6 mẫu, lesson 321-326)', 5, TRUE, 1),
(69, 4, 6, 'Bài 6', 'Ngữ pháp N2 - Bài 6 (5 mẫu, lesson 327-331)', 6, TRUE, 1),
(70, 4, 7, 'Bài 7', 'Ngữ pháp N2 - Bài 7 (5 mẫu, lesson 332-336)', 7, TRUE, 1),
(71, 4, 8, 'Bài 8', 'Ngữ pháp N2 - Bài 8 (5 mẫu, lesson 337-341)', 8, TRUE, 1),
(72, 4, 9, 'Bài 9', 'Ngữ pháp N2 - Bài 9 (5 mẫu, lesson 342-346)', 9, TRUE, 1),
(73, 4, 10, 'Bài 10', 'Ngữ pháp N2 - Bài 10 (4 mẫu, lesson 347-350)', 10, TRUE, 1),
(74, 4, 11, 'Bài 11', 'Ngữ pháp N2 - Bài 11 (5 mẫu, lesson 351-355)', 11, TRUE, 1),
(75, 4, 12, 'Bài 12', 'Ngữ pháp N2 - Bài 12 (6 mẫu, lesson 356-361)', 12, TRUE, 1),
(76, 4, 13, 'Bài 13', 'Ngữ pháp N2 - Bài 13 (6 mẫu, lesson 362-367)', 13, TRUE, 1),
(77, 4, 14, 'Bài 14', 'Ngữ pháp N2 - Bài 14 (7 mẫu, lesson 368-374)', 14, TRUE, 1),
(78, 4, 15, 'Bài 15', 'Ngữ pháp N2 - Bài 15 (6 mẫu, lesson 375-380)', 15, TRUE, 1),
(79, 4, 16, 'Bài 16', 'Ngữ pháp N2 - Bài 16 (7 mẫu, lesson 381-387)', 16, TRUE, 1),
(80, 4, 17, 'Bài 17', 'Ngữ pháp N2 - Bài 17 (5 mẫu, lesson 388-392)', 17, TRUE, 1),
(81, 4, 18, 'Bài 18', 'Ngữ pháp N2 - Bài 18 (6 mẫu, lesson 393-398)', 18, TRUE, 1),
(82, 4, 19, 'Bài 19', 'Ngữ pháp N2 - Bài 19 (6 mẫu, lesson 399-404)', 19, TRUE, 1),
(83, 4, 20, 'Bài 20', 'Ngữ pháp N2 - Bài 20 (6 mẫu, lesson 405-410)', 20, TRUE, 1),
(84, 4, 21, 'Bài 21', 'Ngữ pháp N2 - Bài 21 (9 mẫu, lesson 411-419)', 21, TRUE, 1),
(85, 4, 22, 'Bài 22', 'Ngữ pháp N2 - Bài 22 (7 mẫu, lesson 420-426)', 22, TRUE, 1),
(86, 4, 23, 'Bài 23', 'Ngữ pháp N2 - Bài 23 (7 mẫu, lesson 427-433)', 23, TRUE, 1),
(87, 4, 24, 'Bài 24', 'Ngữ pháp N2 - Bài 24 (6 mẫu, lesson 434-439)', 24, TRUE, 1),
(88, 4, 25, 'Bài 25', 'Ngữ pháp N2 - Bài 25 (5 mẫu, lesson 440-444)', 25, TRUE, 1),
(89, 4, 26, 'Bài 26', 'Ngữ pháp N2 - Bài 26 (7 mẫu, lesson 445-451)', 26, TRUE, 1)
ON DUPLICATE KEY UPDATE
    jlpt_level_id = VALUES(jlpt_level_id),
    chapter_number = VALUES(chapter_number),
    name = VALUES(name),
    description = VALUES(description),
    display_order = VALUES(display_order),
    is_published = VALUES(is_published),
    version = VALUES(version);

INSERT INTO grammar_lessons (id, grammar_chapter_id, title, pattern, meaning_vi, explanation, formation, jlpt_level_id, display_order, is_published, version) VALUES
(295, 64, 'Bài 1.1 - ～際(に)', '～際(に)', 'Khi, nhân lúc, nhân dịp', 'Dùng để diễn đạt ý ''Khi, nhân lúc, nhân dịp''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～際(に)', 4, 1, TRUE, 1),
(296, 64, 'Bài 1.2 - ～に際して／～にあたって', '～に際して／～にあたって', 'Tại thời điểm, nhân dịp', 'Dùng để diễn đạt ý ''Tại thời điểm, nhân dịp''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～に際して／～にあたって', 4, 2, TRUE, 1),
(297, 64, 'Bài 1.3 - ～たとたん(に)', '～たとたん(に)', 'Ngay khi vừa mới thì', 'Dùng để diễn đạt ý ''Ngay khi vừa mới thì''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～たとたん(に)', 4, 3, TRUE, 1),
(298, 64, 'Bài 1.4 - ～(か)と思うと／～(か)と思ったら', '～(か)と思うと／～(か)と思ったら', 'Vừa mới thì lập tức', 'Dùng để diễn đạt ý ''Vừa mới thì lập tức''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～(か)と思うと／～(か)と思ったら', 4, 4, TRUE, 1),
(299, 64, 'Bài 1.5 - ～(か)～ないかのうちに', '～(か)～ないかのうちに', 'Ngay sau khi vừa', 'Dùng để diễn đạt ý ''Ngay sau khi vừa''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～(か)～ないかのうちに', 4, 5, TRUE, 1),
(300, 65, 'Bài 2.1 - ～最中だ', '～最中だ', 'Đúng lúc, ngay trong lúc', 'Dùng để diễn đạt ý ''Đúng lúc, ngay trong lúc''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～最中だ', 4, 1, TRUE, 1),
(301, 65, 'Bài 2.2 - ～うちに(P1)', '～うちに(P1)', 'Nhân lúc, khi còn', 'Dùng để diễn đạt ý ''Nhân lúc, khi còn''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～うちに(P1)', 4, 2, TRUE, 1),
(302, 65, 'Bài 2.3 - ～うちに(P2)', '～うちに(P2)', 'Trong khi đang thì dần', 'Dùng để diễn đạt ý ''Trong khi đang thì dần''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～うちに(P2)', 4, 3, TRUE, 1),
(303, 65, 'Bài 2.4 - ～ばかりだ', '～ばかりだ', 'Ngày càng, cứ mãi', 'Dùng để diễn đạt ý ''Ngày càng, cứ mãi''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ばかりだ', 4, 4, TRUE, 1),
(304, 65, 'Bài 2.5 - ～一方だ', '～一方だ', 'Ngày càng theo một chiều hướng', 'Dùng để diễn đạt ý ''Ngày càng theo một chiều hướng''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～一方だ', 4, 5, TRUE, 1),
(305, 65, 'Bài 2.6 - ～ようとしている', '～ようとしている', 'Sắp sửa, đang định', 'Dùng để diễn đạt ý ''Sắp sửa, đang định''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ようとしている', 4, 6, TRUE, 1),
(306, 65, 'Bài 2.7 - ～つつある', '～つつある', 'Đang dần', 'Dùng để diễn đạt ý ''Đang dần''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～つつある', 4, 7, TRUE, 1),
(307, 65, 'Bài 2.8 - ～つつ', '～つつ', 'Vừa vừa, trong lúc', 'Dùng để diễn đạt ý ''Vừa vừa, trong lúc''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～つつ', 4, 8, TRUE, 1),
(308, 66, 'Bài 3.1 - ～てはじめて', '～てはじめて', 'Chỉ sau khi mới nhận ra', 'Dùng để diễn đạt ý ''Chỉ sau khi mới nhận ra''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～てはじめて', 4, 1, TRUE, 1),
(309, 66, 'Bài 3.2 - ～上で', '～上で', 'Sau khi, trên cơ sở', 'Dùng để diễn đạt ý ''Sau khi, trên cơ sở''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～上で', 4, 2, TRUE, 1),
(310, 66, 'Bài 3.3 - ～次第', '～次第', 'Sau khi xong thì sẽ ngay', 'Dùng để diễn đạt ý ''Sau khi xong thì sẽ ngay''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～次第', 4, 3, TRUE, 1),
(311, 66, 'Bài 3.4 - ～以来', '～以来', 'Suốt từ sau khi', 'Dùng để diễn đạt ý ''Suốt từ sau khi''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～以来', 4, 4, TRUE, 1),
(312, 66, 'Bài 3.5 - ～このかた', '～このかた', 'Suốt từ sau khi', 'Dùng để diễn đạt ý ''Suốt từ sau khi''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～このかた', 4, 5, TRUE, 1),
(313, 66, 'Bài 3.6 - ～からでないと／～からでなければ', '～からでないと／～からでなければ', 'Nếu không sau khi thì không thể', 'Dùng để diễn đạt ý ''Nếu không sau khi thì không thể''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～からでないと／～からでなければ', 4, 6, TRUE, 1),
(314, 67, 'Bài 4.1 - ～をはじめ(として)', '～をはじめ(として)', 'Trước hết phải kể tới', 'Dùng để diễn đạt ý ''Trước hết phải kể tới''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～をはじめ(として)', 4, 1, TRUE, 1),
(315, 67, 'Bài 4.2 - ～をはじめとする', '～をはじめとする', 'Bao gồm tiêu biểu là', 'Dùng để diễn đạt ý ''Bao gồm tiêu biểu là''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～をはじめとする', 4, 2, TRUE, 1),
(316, 67, 'Bài 4.3 - ～からして', '～からして', 'Ngay từ, xét ngay từ', 'Dùng để diễn đạt ý ''Ngay từ, xét ngay từ''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～からして', 4, 3, TRUE, 1),
(317, 67, 'Bài 4.4 - ～にわたって／～にわたる', '～にわたって／～にわたる', 'Trải suốt, trải khắp', 'Dùng để diễn đạt ý ''Trải suốt, trải khắp''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～にわたって／～にわたる', 4, 4, TRUE, 1),
(318, 67, 'Bài 4.5 - ～を通じて／～を通して', '～を通じて／～を通して', 'Suốt, thông qua', 'Dùng để diễn đạt ý ''Suốt, thông qua''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～を通じて／～を通して', 4, 5, TRUE, 1),
(319, 67, 'Bài 4.6 - ～限り', '～限り', 'Bằng tất cả, chừng nào còn', 'Dùng để diễn đạt ý ''Bằng tất cả, chừng nào còn''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～限り', 4, 6, TRUE, 1),
(320, 67, 'Bài 4.7 - ～だけ', '～だけ', 'Đến mức, chỉ tới mức', 'Dùng để diễn đạt ý ''Đến mức, chỉ tới mức''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～だけ', 4, 7, TRUE, 1),
(321, 68, 'Bài 5.1 - ～に限り', '～に限り', 'Chỉ đối với, chỉ riêng', 'Dùng để diễn đạt ý ''Chỉ đối với, chỉ riêng''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～に限り', 4, 1, TRUE, 1),
(322, 68, 'Bài 5.2 - ～に限り(は)', '～に限り(は)', 'Đến chừng nào thì còn', 'Dùng để diễn đạt ý ''Đến chừng nào thì còn''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～に限り(は)', 4, 2, TRUE, 1),
(323, 68, 'Bài 5.3 - ～に限っては', '～に限っては', 'Theo như tôi biết về riêng', 'Dùng để diễn đạt ý ''Theo như tôi biết về riêng''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～に限っては', 4, 3, TRUE, 1),
(324, 68, 'Bài 5.4 - ～に限って(P1)', '～に限って(P1)', 'Khác với mọi khi', 'Dùng để diễn đạt ý ''Khác với mọi khi''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～に限って(P1)', 4, 4, TRUE, 1),
(325, 68, 'Bài 5.5 - ～に限って(P2)', '～に限って(P2)', 'Đúng lúc, đúng vào', 'Dùng để diễn đạt ý ''Đúng lúc, đúng vào''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～に限って(P2)', 4, 5, TRUE, 1),
(326, 68, 'Bài 5.6 - ～に限って(P3)', '～に限って(P3)', 'Riêng, chỉ riêng', 'Dùng để diễn đạt ý ''Riêng, chỉ riêng''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～に限って(P3)', 4, 6, TRUE, 1),
(327, 69, 'Bài 6.1 - ～限らず', '～限らず', 'Không chỉ, không giới hạn ở', 'Dùng để diễn đạt ý ''Không chỉ, không giới hạn ở''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～限らず', 4, 1, TRUE, 1),
(328, 69, 'Bài 6.2 - ～のみならず', '～のみならず', 'Không chỉ, mà còn', 'Dùng để diễn đạt ý ''Không chỉ, mà còn''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～のみならず', 4, 2, TRUE, 1),
(329, 69, 'Bài 6.3 - ～ばかりか', '～ばかりか', 'Không chỉ mà còn', 'Dùng để diễn đạt ý ''Không chỉ mà còn''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ばかりか', 4, 3, TRUE, 1),
(330, 69, 'Bài 6.4 - ～はもとより', '～はもとより', 'Dĩ nhiên, không nói cũng biết', 'Dùng để diễn đạt ý ''Dĩ nhiên, không nói cũng biết''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～はもとより', 4, 4, TRUE, 1),
(331, 69, 'Bài 6.5 - ～上(に)', '～上(に)', 'Hơn nữa, thêm vào đó', 'Dùng để diễn đạt ý ''Hơn nữa, thêm vào đó''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～上(に)', 4, 5, TRUE, 1),
(332, 70, 'Bài 7.1 - ～に関して／～に関する', '～に関して／～に関する', 'Liên quan tới', 'Dùng để diễn đạt ý ''Liên quan tới''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～に関して／～に関する', 4, 1, TRUE, 1),
(333, 70, 'Bài 7.2 - ～をめぐって／～をめぐる', '～をめぐって／～をめぐる', 'Xung quanh vấn đề', 'Dùng để diễn đạt ý ''Xung quanh vấn đề''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～をめぐって／～をめぐる', 4, 2, TRUE, 1),
(334, 70, 'Bài 7.3 - ～にかけては', '～にかけては', 'Riêng về mặt', 'Dùng để diễn đạt ý ''Riêng về mặt''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～にかけては', 4, 3, TRUE, 1),
(335, 70, 'Bài 7.4 - ～に対して／～に対する', '～に対して／～に対する', 'Đối với', 'Dùng để diễn đạt ý ''Đối với''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～に対して／～に対する', 4, 4, TRUE, 1),
(336, 70, 'Bài 7.5 - ～にこたえて／～にこたえる', '～にこたえて／～にこたえる', 'Đáp ứng', 'Dùng để diễn đạt ý ''Đáp ứng''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～にこたえて／～にこたえる', 4, 5, TRUE, 1),
(337, 71, 'Bài 8.1 - ～をもとに(して)', '～をもとに(して)', 'Dựa trên, căn cứ trên', 'Dùng để diễn đạt ý ''Dựa trên, căn cứ trên''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～をもとに(して)', 4, 1, TRUE, 1),
(338, 71, 'Bài 8.2 - ～に基づいて／～に基づく', '～に基づいて／～に基づく', 'Dựa vào, theo cơ sở', 'Dùng để diễn đạt ý ''Dựa vào, theo cơ sở''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～に基づいて／～に基づく', 4, 2, TRUE, 1),
(339, 71, 'Bài 8.3 - ～に沿って／～に沿う', '～に沿って／～に沿う', 'Theo, phù hợp với', 'Dùng để diễn đạt ý ''Theo, phù hợp với''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～に沿って／～に沿う', 4, 3, TRUE, 1),
(340, 71, 'Bài 8.4 - ～のもとで／～のもとに', '～のもとで／～のもとに', 'Dưới sự, trong điều kiện', 'Dùng để diễn đạt ý ''Dưới sự, trong điều kiện''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～のもとで／～のもとに', 4, 4, TRUE, 1),
(341, 71, 'Bài 8.5 - ～向けだ／～向けの', '～向けだ／～向けの', 'Dành cho', 'Dùng để diễn đạt ý ''Dành cho''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～向けだ／～向けの', 4, 5, TRUE, 1),
(342, 72, 'Bài 9.1 - ～につれて／～にしたがって', '～につれて／～にしたがって', 'Theo, càng thì càng', 'Dùng để diễn đạt ý ''Theo, càng thì càng''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～につれて／～にしたがって', 4, 1, TRUE, 1),
(343, 72, 'Bài 9.2 - ～に伴って／～とともに', '～に伴って／～とともに', 'Kéo theo, cùng với', 'Dùng để diễn đạt ý ''Kéo theo, cùng với''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～に伴って／～とともに', 4, 2, TRUE, 1),
(344, 72, 'Bài 9.3 - ～次第だ', '～次第だ', 'Tùy thuộc vào', 'Dùng để diễn đạt ý ''Tùy thuộc vào''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～次第だ', 4, 3, TRUE, 1),
(345, 72, 'Bài 9.4 - ～に応じて／～に応じた', '～に応じて／～に応じた', 'Ứng với, tùy theo', 'Dùng để diễn đạt ý ''Ứng với, tùy theo''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～に応じて／～に応じた', 4, 4, TRUE, 1),
(346, 72, 'Bài 9.5 - ～につけて', '～につけて', 'Hễ mỗi lần là', 'Dùng để diễn đạt ý ''Hễ mỗi lần là''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～につけて', 4, 5, TRUE, 1),
(347, 73, 'Bài 10.1 - ～やら…やら', '～やら…やら', 'Nào là, nào là', 'Dùng để diễn đạt ý ''Nào là, nào là''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～やら…やら', 4, 1, TRUE, 1),
(348, 73, 'Bài 10.2 - ～というか…というか', '～というか…というか', 'Có thể nói là, vừa như vừa như', 'Dùng để diễn đạt ý ''Có thể nói là, vừa như vừa như''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～というか…というか', 4, 2, TRUE, 1),
(349, 73, 'Bài 10.3 - ～にしても…にしても', '～にしても…にしても', 'Cho dù là cái này hay cái kia', 'Dùng để diễn đạt ý ''Cho dù là cái này hay cái kia''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～にしても…にしても', 4, 3, TRUE, 1),
(350, 73, 'Bài 10.4 - ～といった', '～といった', 'Như là, kiểu như', 'Dùng để diễn đạt ý ''Như là, kiểu như''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～といった', 4, 4, TRUE, 1),
(351, 74, 'Bài 11.1 - ～を問わず', '～を問わず', 'Không kể, bất kể', 'Dùng để diễn đạt ý ''Không kể, bất kể''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～を問わず', 4, 1, TRUE, 1),
(352, 74, 'Bài 11.2 - ～にかかわりなく／～にかかわらず', '～にかかわりなく／～にかかわらず', 'Bất chấp, bất kể', 'Dùng để diễn đạt ý ''Bất chấp, bất kể''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～にかかわりなく／～にかかわらず', 4, 2, TRUE, 1),
(353, 74, 'Bài 11.3 - ～(の)もかまわず', '～(の)もかまわず', 'Chẳng quan tâm đến', 'Dùng để diễn đạt ý ''Chẳng quan tâm đến''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～(の)もかまわず', 4, 3, TRUE, 1),
(354, 74, 'Bài 11.4 - ～はともかく(として)', '～はともかく(として)', 'Khoan bàn đến, trước hết', 'Dùng để diễn đạt ý ''Khoan bàn đến, trước hết''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～はともかく(として)', 4, 4, TRUE, 1),
(355, 74, 'Bài 11.5 - ～はさておき', '～はさておき', 'Gác sang một bên', 'Dùng để diễn đạt ý ''Gác sang một bên''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～はさておき', 4, 5, TRUE, 1),
(356, 75, 'Bài 12.1 - ～わけがない', '～わけがない', 'Tuyệt đối không, nhất định không', 'Dùng để diễn đạt ý ''Tuyệt đối không, nhất định không''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～わけがない', 4, 1, TRUE, 1),
(357, 75, 'Bài 12.2 - ～どころではない', '～どころではない', 'Không chỉ mà còn hơn thế, không còn tâm trí', 'Dùng để diễn đạt ý ''Không chỉ mà còn hơn thế, không còn tâm trí''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～どころではない', 4, 2, TRUE, 1),
(358, 75, 'Bài 12.3 - ～どころか', '～どころか', 'Không những không mà còn', 'Dùng để diễn đạt ý ''Không những không mà còn''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～どころか', 4, 3, TRUE, 1),
(359, 75, 'Bài 12.4 - ～ものか', '～ものか', 'Làm gì có chuyện', 'Dùng để diễn đạt ý ''Làm gì có chuyện''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ものか', 4, 4, TRUE, 1),
(360, 75, 'Bài 12.5 - ～わけではない', '～わけではない', 'Không hẳn là, không phải là', 'Dùng để diễn đạt ý ''Không hẳn là, không phải là''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～わけではない', 4, 5, TRUE, 1),
(361, 75, 'Bài 12.6 - ～というものではない／～というものでもない', '～というものではない／～というものでもない', 'Không phải cứ là được', 'Dùng để diễn đạt ý ''Không phải cứ là được''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～というものではない／～というものでもない', 4, 6, TRUE, 1),
(362, 76, 'Bài 13.1 - ～とは', '～とは', 'Định nghĩa là, nghĩa là', 'Dùng để diễn đạt ý ''Định nghĩa là, nghĩa là''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～とは', 4, 1, TRUE, 1),
(363, 76, 'Bài 13.2 - ～といえば(1)', '～といえば(1)', 'Nói đến thì', 'Dùng để diễn đạt ý ''Nói đến thì''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～といえば(1)', 4, 2, TRUE, 1),
(364, 76, 'Bài 13.3 - ～といえば(2)', '～といえば(2)', 'Nếu nói thì', 'Dùng để diễn đạt ý ''Nếu nói thì''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～といえば(2)', 4, 3, TRUE, 1),
(365, 76, 'Bài 13.4 - ～というと', '～というと', 'Nhắc đến, nghĩ ngay tới', 'Dùng để diễn đạt ý ''Nhắc đến, nghĩ ngay tới''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～というと', 4, 4, TRUE, 1),
(366, 76, 'Bài 13.5 - ～(のこと)となると', '～(のこと)となると', 'Cứ nghĩ đến là, hễ nói về', 'Dùng để diễn đạt ý ''Cứ nghĩ đến là, hễ nói về''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～(のこと)となると', 4, 5, TRUE, 1),
(367, 76, 'Bài 13.6 - ～といったら', '～といったら', 'Nhắc đến thì, hơn mức thường', 'Dùng để diễn đạt ý ''Nhắc đến thì, hơn mức thường''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～といったら', 4, 6, TRUE, 1),
(368, 77, 'Bài 14.1 - ～にもかかわらず', '～にもかかわらず', 'Bất chấp, mặc dù', 'Dùng để diễn đạt ý ''Bất chấp, mặc dù''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～にもかかわらず', 4, 1, TRUE, 1),
(369, 77, 'Bài 14.2 - ～ものの', '～ものの', 'Tuy nhưng', 'Dùng để diễn đạt ý ''Tuy nhưng''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ものの', 4, 2, TRUE, 1),
(370, 77, 'Bài 14.3 - ～とはいうものの', '～とはいうものの', 'Tuy nói là nhưng', 'Dùng để diễn đạt ý ''Tuy nói là nhưng''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～とはいうものの', 4, 3, TRUE, 1),
(371, 77, 'Bài 14.4 - ～ながら(も)', '～ながら(も)', 'Dù nhưng', 'Dùng để diễn đạt ý ''Dù nhưng''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ながら(も)', 4, 4, TRUE, 1),
(372, 77, 'Bài 14.5 - ～つつ(も)', '～つつ(も)', 'Mặc dù nhưng', 'Dùng để diễn đạt ý ''Mặc dù nhưng''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～つつ(も)', 4, 5, TRUE, 1),
(373, 77, 'Bài 14.6 - ～といっても', '～といっても', 'Dù nói là thế chứ', 'Dùng để diễn đạt ý ''Dù nói là thế chứ''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～といっても', 4, 6, TRUE, 1),
(374, 77, 'Bài 14.7 - ～からといって', '～からといって', 'Cho dù cũng không', 'Dùng để diễn đạt ý ''Cho dù cũng không''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～からといって', 4, 7, TRUE, 1),
(375, 78, 'Bài 15.1 - ～としたら／～とすれば／～とすると', '～としたら／～とすれば／～とすると', 'Giả định là, nếu vậy thì', 'Dùng để diễn đạt ý ''Giả định là, nếu vậy thì''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～としたら／～とすれば／～とすると', 4, 1, TRUE, 1),
(376, 78, 'Bài 15.2 - ～となったら／～となれば／～となると', '～となったら／～となれば／～となると', 'Nếu tình huống trở thành', 'Dùng để diễn đạt ý ''Nếu tình huống trở thành''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～となったら／～となれば／～となると', 4, 2, TRUE, 1),
(377, 78, 'Bài 15.3 - ～ものなら', '～ものなら', 'Nếu có thể thì', 'Dùng để diễn đạt ý ''Nếu có thể thì''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ものなら', 4, 3, TRUE, 1),
(378, 78, 'Bài 15.4 - ～(よ)うものなら', '～(よ)うものなら', 'Nếu lỡ thì hậu quả', 'Dùng để diễn đạt ý ''Nếu lỡ thì hậu quả''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～(よ)うものなら', 4, 4, TRUE, 1),
(379, 78, 'Bài 15.5 - ～ないことには', '～ないことには', 'Nếu chưa thì không', 'Dùng để diễn đạt ý ''Nếu chưa thì không''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ないことには', 4, 5, TRUE, 1),
(380, 78, 'Bài 15.6 - ～を抜きにしては', '～を抜きにしては', 'Nếu không có thì', 'Dùng để diễn đạt ý ''Nếu không có thì''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～を抜きにしては', 4, 6, TRUE, 1),
(381, 79, 'Bài 16.1 - ～によって／～によっては', '～によって／～によっては', 'Vì, bằng, tùy theo', 'Dùng để diễn đạt ý ''Vì, bằng, tùy theo''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～によって／～によっては', 4, 1, TRUE, 1),
(382, 79, 'Bài 16.2 - ～ものだから／～もので', '～ものだから／～もので', 'Vì nên', 'Dùng để diễn đạt ý ''Vì nên''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ものだから／～もので', 4, 2, TRUE, 1),
(383, 79, 'Bài 16.3 - ～もの', '～もの', 'Vì mà, dùng giải thích thân mật', 'Dùng để diễn đạt ý ''Vì mà, dùng giải thích thân mật''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～もの', 4, 3, TRUE, 1),
(384, 79, 'Bài 16.4 - ～おかげだ／～おかげで', '～おかげだ／～おかげで', 'Nhờ có', 'Dùng để diễn đạt ý ''Nhờ có''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～おかげだ／～おかげで', 4, 4, TRUE, 1),
(385, 79, 'Bài 16.5 - ～せいだ／～せいで', '～せいだ／～せいで', 'Chỉ vì, do lỗi', 'Dùng để diễn đạt ý ''Chỉ vì, do lỗi''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～せいだ／～せいで', 4, 5, TRUE, 1),
(386, 79, 'Bài 16.6 - ～あまり', '～あまり', 'Vì quá mà', 'Dùng để diễn đạt ý ''Vì quá mà''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～あまり', 4, 6, TRUE, 1),
(387, 79, 'Bài 16.7 - ～につき', '～につき', 'Vì lý do, thông báo', 'Dùng để diễn đạt ý ''Vì lý do, thông báo''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～につき', 4, 7, TRUE, 1),
(388, 80, 'Bài 17.1 - ～ことだし', '～ことだし', 'Vả lại, cũng vì', 'Dùng để diễn đạt ý ''Vả lại, cũng vì''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ことだし', 4, 1, TRUE, 1),
(389, 80, 'Bài 17.2 - ～のことだから', '～のことだから', 'Vì là người đó nên chắc', 'Dùng để diễn đạt ý ''Vì là người đó nên chắc''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～のことだから', 4, 2, TRUE, 1),
(390, 80, 'Bài 17.3 - ～だけに', '～だけに', 'Chính vì', 'Dùng để diễn đạt ý ''Chính vì''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～だけに', 4, 3, TRUE, 1),
(391, 80, 'Bài 17.4 - ～ばかりに', '～ばかりに', 'Chỉ vì mà', 'Dùng để diễn đạt ý ''Chỉ vì mà''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ばかりに', 4, 4, TRUE, 1),
(392, 80, 'Bài 17.5 - ～からには／～以上(は)', '～からには／～以上(は)', 'Một khi đã thì', 'Dùng để diễn đạt ý ''Một khi đã thì''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～からには／～以上(は)', 4, 5, TRUE, 1),
(393, 81, 'Bài 18.1 - ～がたい', '～がたい', 'Khó mà, không thể', 'Dùng để diễn đạt ý ''Khó mà, không thể''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～がたい', 4, 1, TRUE, 1),
(394, 81, 'Bài 18.2 - ～わけにはいかない', '～わけにはいかない', 'Không thể làm vì lý do xã hội', 'Dùng để diễn đạt ý ''Không thể làm vì lý do xã hội''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～わけにはいかない', 4, 2, TRUE, 1),
(395, 81, 'Bài 18.3 - ～わけにもいかない', '～わけにもいかない', 'Không thể nào cứ', 'Dùng để diễn đạt ý ''Không thể nào cứ''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～わけにもいかない', 4, 3, TRUE, 1),
(396, 81, 'Bài 18.4 - ～かねる', '～かねる', 'Khó mà, không thể', 'Dùng để diễn đạt ý ''Khó mà, không thể''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～かねる', 4, 4, TRUE, 1),
(397, 81, 'Bài 18.5 - ～ようがない', '～ようがない', 'Không có cách nào', 'Dùng để diễn đạt ý ''Không có cách nào''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ようがない', 4, 5, TRUE, 1),
(398, 81, 'Bài 18.6 - ～得る／～得ない', '～得る／～得ない', 'Có thể, không thể có khả năng', 'Dùng để diễn đạt ý ''Có thể, không thể có khả năng''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～得る／～得ない', 4, 6, TRUE, 1),
(399, 82, 'Bài 19.1 - ～わりには', '～わりには', 'So với thì tương đối', 'Dùng để diễn đạt ý ''So với thì tương đối''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～わりには', 4, 1, TRUE, 1),
(400, 82, 'Bài 19.2 - ～にしては', '～にしては', 'Tuy là vậy mà', 'Dùng để diễn đạt ý ''Tuy là vậy mà''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～にしては', 4, 2, TRUE, 1),
(401, 82, 'Bài 19.3 - ～だけ(のことは)ある', '～だけ(のことは)ある', 'Quả đúng là, đáng công', 'Dùng để diễn đạt ý ''Quả đúng là, đáng công''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～だけ(のことは)ある', 4, 3, TRUE, 1),
(402, 82, 'Bài 19.4 - ～として', '～として', 'Với tư cách là', 'Dùng để diễn đạt ý ''Với tư cách là''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～として', 4, 4, TRUE, 1),
(403, 82, 'Bài 19.5 - ～にとって', '～にとって', 'Đối với', 'Dùng để diễn đạt ý ''Đối với''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～にとって', 4, 5, TRUE, 1),
(404, 82, 'Bài 19.6 - ～にしたら／～にすれば／～にしても', '～にしたら／～にすれば／～にしても', 'Đối với lập trường của', 'Dùng để diễn đạt ý ''Đối với lập trường của''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～にしたら／～にすれば／～にしても', 4, 6, TRUE, 1),
(405, 83, 'Bài 20.1 - ～ところ', '～ところ', 'Khi thì kết quả', 'Dùng để diễn đạt ý ''Khi thì kết quả''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ところ', 4, 1, TRUE, 1),
(406, 83, 'Bài 20.2 - ～きり', '～きり', 'Cứ mãi không, sau khi rồi', 'Dùng để diễn đạt ý ''Cứ mãi không, sau khi rồi''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～きり', 4, 2, TRUE, 1),
(407, 83, 'Bài 20.3 - ～あげく', '～あげく', 'Sau cùng sau nhiều việc', 'Dùng để diễn đạt ý ''Sau cùng sau nhiều việc''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～あげく', 4, 3, TRUE, 1),
(408, 83, 'Bài 20.4 - ～末に', '～末に', 'Sau cùng, sau quá trình', 'Dùng để diễn đạt ý ''Sau cùng, sau quá trình''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～末に', 4, 4, TRUE, 1),
(409, 83, 'Bài 20.5 - ～ところだった', '～ところだった', 'Suýt nữa, sắp đúng lúc', 'Dùng để diễn đạt ý ''Suýt nữa, sắp đúng lúc''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ところだった', 4, 5, TRUE, 1),
(410, 83, 'Bài 20.6 - ～ずじまいだ', '～ずじまいだ', 'Cuối cùng vẫn không', 'Dùng để diễn đạt ý ''Cuối cùng vẫn không''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ずじまいだ', 4, 6, TRUE, 1),
(411, 84, 'Bài 21.1 - ～くらい／～ぐらい', '～くらい／～ぐらい', 'Cỡ như, chỉ mới', 'Dùng để diễn đạt ý ''Cỡ như, chỉ mới''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～くらい／～ぐらい', 4, 1, TRUE, 1),
(412, 84, 'Bài 21.2 - ～など', '～など', 'Chẳng hạn như, coi nhẹ', 'Dùng để diễn đạt ý ''Chẳng hạn như, coi nhẹ''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～など', 4, 2, TRUE, 1),
(413, 84, 'Bài 21.3 - ～なんか', '～なんか', 'Chẳng hạn như, coi nhẹ', 'Dùng để diễn đạt ý ''Chẳng hạn như, coi nhẹ''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～なんか', 4, 3, TRUE, 1),
(414, 84, 'Bài 21.4 - ～なんて', '～なんて', 'Chẳng hạn như, cảm thán', 'Dùng để diễn đạt ý ''Chẳng hạn như, cảm thán''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～なんて', 4, 4, TRUE, 1),
(415, 84, 'Bài 21.5 - ～まで／～までして', '～まで／～までして', 'Thậm chí đến mức', 'Dùng để diễn đạt ý ''Thậm chí đến mức''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～まで／～までして', 4, 5, TRUE, 1),
(416, 84, 'Bài 21.6 - ～として～ない', '～として～ない', 'Không một, dù chỉ', 'Dùng để diễn đạt ý ''Không một, dù chỉ''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～として～ない', 4, 6, TRUE, 1),
(417, 84, 'Bài 21.7 - ～さえ(1)', '～さえ(1)', 'Ngay cả, đến cả', 'Dùng để diễn đạt ý ''Ngay cả, đến cả''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～さえ(1)', 4, 7, TRUE, 1),
(418, 84, 'Bài 21.8 - ～さえ(2)', '～さえ(2)', 'Chỉ cần là', 'Dùng để diễn đạt ý ''Chỉ cần là''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～さえ(2)', 4, 8, TRUE, 1),
(419, 84, 'Bài 21.9 - ～でも', '～でも', 'Cho dù, ngay cả', 'Dùng để diễn đạt ý ''Cho dù, ngay cả''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～でも', 4, 9, TRUE, 1),
(420, 85, 'Bài 22.1 - ～とみえる', '～とみえる', 'Dường như', 'Dùng để diễn đạt ý ''Dường như''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～とみえる', 4, 1, TRUE, 1),
(421, 85, 'Bài 22.2 - ～かねない', '～かねない', 'Có thể sẽ xảy ra điều xấu', 'Dùng để diễn đạt ý ''Có thể sẽ xảy ra điều xấu''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～かねない', 4, 2, TRUE, 1),
(422, 85, 'Bài 22.3 - ～おそれがある', '～おそれがある', 'Có nguy cơ, e rằng', 'Dùng để diễn đạt ý ''Có nguy cơ, e rằng''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～おそれがある', 4, 3, TRUE, 1),
(423, 85, 'Bài 22.4 - ～まい', '～まい', 'Chắc là không, sẽ không', 'Dùng để diễn đạt ý ''Chắc là không, sẽ không''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～まい', 4, 4, TRUE, 1),
(424, 85, 'Bài 22.5 - ～ではあるまいか', '～ではあるまいか', 'Chẳng phải là sao', 'Dùng để diễn đạt ý ''Chẳng phải là sao''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ではあるまいか', 4, 5, TRUE, 1),
(425, 85, 'Bài 22.6 - ～に違いない／～に相違ない', '～に違いない／～に相違ない', 'Chắc chắn là', 'Dùng để diễn đạt ý ''Chắc chắn là''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～に違いない／～に相違ない', 4, 6, TRUE, 1),
(426, 85, 'Bài 22.7 - ～にきまっている', '～にきまっている', 'Nhất định là', 'Dùng để diễn đạt ý ''Nhất định là''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～にきまっている', 4, 7, TRUE, 1),
(427, 86, 'Bài 23.1 - ～ものだ', '～ものだ', 'Vốn là, bản chất là', 'Dùng để diễn đạt ý ''Vốn là, bản chất là''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ものだ', 4, 1, TRUE, 1),
(428, 86, 'Bài 23.2 - ～というものだ', '～というものだ', 'Chính là, đúng là', 'Dùng để diễn đạt ý ''Chính là, đúng là''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～というものだ', 4, 2, TRUE, 1),
(429, 86, 'Bài 23.3 - ～にすぎない', '～にすぎない', 'Chẳng qua chỉ là', 'Dùng để diễn đạt ý ''Chẳng qua chỉ là''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～にすぎない', 4, 3, TRUE, 1),
(430, 86, 'Bài 23.4 - ～にほかならない', '～にほかならない', 'Chính là, không gì khác hơn', 'Dùng để diễn đạt ý ''Chính là, không gì khác hơn''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～にほかならない', 4, 4, TRUE, 1),
(431, 86, 'Bài 23.5 - ～に越したことはない', '～に越したことはない', 'Tốt nhất là', 'Dùng để diễn đạt ý ''Tốt nhất là''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～に越したことはない', 4, 5, TRUE, 1),
(432, 86, 'Bài 23.6 - ～しかない／～よりほかない', '～しかない／～よりほかない', 'Chỉ còn cách là', 'Dùng để diễn đạt ý ''Chỉ còn cách là''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～しかない／～よりほかない', 4, 6, TRUE, 1),
(433, 86, 'Bài 23.7 - ～べきだ／～べきではない', '～べきだ／～べきではない', 'Nên, không nên', 'Dùng để diễn đạt ý ''Nên, không nên''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～べきだ／～べきではない', 4, 7, TRUE, 1),
(434, 87, 'Bài 24.1 - ～ではないか', '～ではないか', 'Hãy cùng, đề nghị mạnh', 'Dùng để diễn đạt ý ''Hãy cùng, đề nghị mạnh''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ではないか', 4, 1, TRUE, 1),
(435, 87, 'Bài 24.2 - ～ことだ', '～ことだ', 'Phải, nên, đừng', 'Dùng để diễn đạt ý ''Phải, nên, đừng''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ことだ', 4, 2, TRUE, 1),
(436, 87, 'Bài 24.3 - ～ものだ', '～ものだ', 'Nên, không nên, lẽ thường', 'Dùng để diễn đạt ý ''Nên, không nên, lẽ thường''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ものだ', 4, 3, TRUE, 1),
(437, 87, 'Bài 24.4 - ～ものではない', '～ものではない', 'Không nên, không được làm', 'Dùng để diễn đạt ý ''Không nên, không được làm''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ものではない', 4, 4, TRUE, 1),
(438, 87, 'Bài 24.5 - ～ことはない', '～ことはない', 'Không cần phải', 'Dùng để diễn đạt ý ''Không cần phải''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ことはない', 4, 5, TRUE, 1),
(439, 87, 'Bài 24.6 - ～ものか', '～ものか', 'Nhất định không', 'Dùng để diễn đạt ý ''Nhất định không''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ものか', 4, 6, TRUE, 1),
(440, 88, 'Bài 25.1 - ～しかたがない／～しょうがない', '～しかたがない／～しょうがない', 'Không chịu nổi, vô cùng', 'Dùng để diễn đạt ý ''Không chịu nổi, vô cùng''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～しかたがない／～しょうがない', 4, 1, TRUE, 1),
(441, 88, 'Bài 25.2 - ～たまらない', '～たまらない', 'Không chịu nổi', 'Dùng để diễn đạt ý ''Không chịu nổi''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～たまらない', 4, 2, TRUE, 1),
(442, 88, 'Bài 25.3 - ～ならない', '～ならない', 'Vô cùng, không thể kìm', 'Dùng để diễn đạt ý ''Vô cùng, không thể kìm''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ならない', 4, 3, TRUE, 1),
(443, 88, 'Bài 25.4 - ～てはいられない／～ずにはいられない', '～てはいられない／～ずにはいられない', 'Không thể cứ, không thể không', 'Dùng để diễn đạt ý ''Không thể cứ, không thể không''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～てはいられない／～ずにはいられない', 4, 4, TRUE, 1),
(444, 88, 'Bài 25.5 - ～ざるを得ない', '～ざるを得ない', 'Đành phải, buộc phải', 'Dùng để diễn đạt ý ''Đành phải, buộc phải''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ざるを得ない', 4, 5, TRUE, 1),
(445, 89, 'Bài 26.1 - ～たいものだ／～ほしいものだ', '～たいものだ／～ほしいものだ', 'Thật rất muốn, ước gì', 'Dùng để diễn đạt ý ''Thật rất muốn, ước gì''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～たいものだ／～ほしいものだ', 4, 1, TRUE, 1),
(446, 89, 'Bài 26.2 - ～ものだ(1)', '～ものだ(1)', 'Thường hay, hồi tưởng', 'Dùng để diễn đạt ý ''Thường hay, hồi tưởng''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ものだ(1)', 4, 2, TRUE, 1),
(447, 89, 'Bài 26.3 - ～ものだ(2)', '～ものだ(2)', 'Làm sao mà, biết bao', 'Dùng để diễn đạt ý ''Làm sao mà, biết bao''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ものだ(2)', 4, 3, TRUE, 1),
(448, 89, 'Bài 26.4 - ～もの(だろう)か', '～もの(だろう)か', 'Phải chi, có thể nào', 'Dùng để diễn đạt ý ''Phải chi, có thể nào''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～もの(だろう)か', 4, 4, TRUE, 1),
(449, 89, 'Bài 26.5 - ～ものがある', '～ものがある', 'Cảm thấy, có điều gì đó', 'Dùng để diễn đạt ý ''Cảm thấy, có điều gì đó''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ものがある', 4, 5, TRUE, 1),
(450, 89, 'Bài 26.6 - ～ことだ', '～ことだ', 'Thật là, làm sao mà', 'Dùng để diễn đạt ý ''Thật là, làm sao mà''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ことだ', 4, 6, TRUE, 1),
(451, 89, 'Bài 26.7 - ～ことか／～ことだろう', '～ことか／～ことだろう', 'Tới cỡ nào, biết bao', 'Dùng để diễn đạt ý ''Tới cỡ nào, biết bao''. Khi dùng trong câu, hãy chú ý thể đứng trước mẫu và sắc thái trang trọng/thân mật theo ngữ cảnh.', '～ことか／～ことだろう', 4, 7, TRUE, 1)
ON DUPLICATE KEY UPDATE
    grammar_chapter_id = VALUES(grammar_chapter_id),
    title = VALUES(title),
    pattern = VALUES(pattern),
    meaning_vi = VALUES(meaning_vi),
    explanation = VALUES(explanation),
    formation = VALUES(formation),
    jlpt_level_id = VALUES(jlpt_level_id),
    display_order = VALUES(display_order),
    is_published = VALUES(is_published),
    version = VALUES(version);

INSERT INTO grammar_examples (id, grammar_lesson_id, japanese_text, reading, meaning_vi, display_order) VALUES
(418, 295, 'お申し込みの際に、身分証明書をお持ちください。', 'おもうしこみのさいに、みぶんしょうめいしょをおもちください。', 'Khi đăng ký, vui lòng mang theo giấy tờ tùy thân.', 1),
(419, 296, '入学に際して、必要な書類を提出してください。', 'にゅうがくにさいして、ひつようなしょるいをていしゅつしてください。', 'Khi nhập học, hãy nộp các giấy tờ cần thiết.', 1),
(420, 297, 'ドアを開けたとたん、電話が鳴った。', 'ドアをあけたとたん、でんわがなった。', 'Ngay khi tôi vừa mở cửa thì điện thoại reo.', 1),
(421, 298, '赤ちゃんは泣いたかと思うと、すぐ笑い出した。', 'あかちゃんはないたかとおもうと、すぐわらいだした。', 'Em bé vừa khóc xong đã bật cười ngay.', 1),
(422, 299, '布団に入るか入らないかのうちに、眠ってしまった。', 'ふとんにはいるかはいらないかのうちに、ねむってしまった。', 'Tôi vừa chui vào chăn là ngủ mất ngay.', 1),
(423, 300, '会議の最中に、急な電話が入った。', 'かいぎのさいちゅうに、きゅうなでんわがはいった。', 'Đúng lúc đang họp thì có cuộc gọi gấp.', 1),
(424, 301, '若いうちに、いろいろな経験をしておきたい。', 'わかいうちに、いろいろなけいけんをしておきたい。', 'Tôi muốn trải nghiệm nhiều thứ khi còn trẻ.', 1),
(425, 302, '本を読んでいるうちに、外が暗くなった。', 'ほんをよんでいるうちに、そとがくらくなった。', 'Trong lúc đọc sách thì trời bên ngoài tối dần.', 1),
(426, 303, '物価は上がるばかりで、生活が大変だ。', 'ぶっかはあがるばかりで、せいかつがたいへんだ。', 'Giá cả cứ tăng mãi nên cuộc sống thật vất vả.', 1),
(427, 304, '仕事は増える一方で、休む時間がない。', 'しごとはふえるいっぽうで、やすむじかんがない。', 'Công việc ngày càng tăng nên không có thời gian nghỉ.', 1),
(428, 305, '空が暗くなり、雨が降ろうとしている。', 'そらがくらくなり、あめがふろうとしている。', 'Trời tối lại và mưa sắp rơi.', 1),
(429, 306, 'この町は少しずつ変わりつつある。', 'このまちはすこしずつかわりつつある。', 'Thị trấn này đang dần thay đổi.', 1),
(430, 307, '悪いと思いつつ、彼に本当のことを言えなかった。', 'わるいとおもいつつ、かれにほんとうのことをいえなかった。', 'Dù biết là không tốt, tôi vẫn không thể nói thật với anh ấy.', 1),
(431, 308, '一人で暮らしてはじめて、親のありがたさが分かった。', 'ひとりでくらしてはじめて、おやのありがたさがわかった。', 'Chỉ sau khi sống một mình tôi mới hiểu sự đáng quý của cha mẹ.', 1),
(432, 309, '内容を確認した上で、契約書にサインしてください。', 'ないようをかくにんしたうえで、けいやくしょにサインしてください。', 'Sau khi kiểm tra nội dung, hãy ký hợp đồng.', 1),
(433, 310, '準備ができ次第、すぐに出発します。', 'じゅんびができしだい、すぐにしゅっぱつします。', 'Ngay khi chuẩn bị xong, chúng tôi sẽ xuất phát.', 1),
(434, 311, '日本に来て以来、毎日日本語を使っています。', 'にほんにきていらい、まいにちにほんごをつかっています。', 'Từ khi đến Nhật, ngày nào tôi cũng dùng tiếng Nhật.', 1),
(435, 312, '卒業してこのかた、彼とは一度も会っていません。', 'そつぎょうしてこのかた、かれとはいちどもあっていません。', 'Từ sau khi tốt nghiệp đến nay tôi chưa gặp anh ấy lần nào.', 1),
(436, 313, '予約してからでないと、この部屋は使えません。', 'よやくしてからでないと、このへやはつかえません。', 'Nếu chưa đặt trước thì không thể sử dụng phòng này.', 1),
(437, 314, '京都には清水寺をはじめ、多くの名所がある。', 'きょうとにはきよみずでらをはじめ、おおくのめいしょがある。', 'Ở Kyoto có nhiều danh thắng, trước hết phải kể đến chùa Kiyomizu.', 1),
(438, 315, '社長をはじめとする社員全員が会議に参加した。', 'しゃちょうをはじめとするしゃいんぜんいんがかいぎにさんかした。', 'Toàn bộ nhân viên gồm cả giám đốc đã tham gia cuộc họp.', 1),
(439, 316, '彼の態度からして、反省していないようだ。', 'かれのたいどからして、はんせいしていないようだ。', 'Xét ngay từ thái độ của anh ấy, có vẻ anh ấy không hối lỗi.', 1),
(440, 317, '台風の影響は広い地域にわたって続いた。', 'たいふうのえいきょうはひろいちいきにわたってつづいた。', 'Ảnh hưởng của bão kéo dài trên một khu vực rộng.', 1),
(441, 318, '一年を通じて、この図書館は多くの学生に利用されている。', 'いちねんをつうじて、このとしょかんはおおくのがくせいにりようされている。', 'Thư viện này được nhiều sinh viên sử dụng suốt cả năm.', 1),
(442, 319, '私の知る限り、彼は約束を破ったことがない。', 'わたしのしるかぎり、かれはやくそくをやぶったことがない。', 'Theo những gì tôi biết, anh ấy chưa từng thất hứa.', 1),
(443, 320, 'できるだけ早く返事をください。', 'できるだけはやくへんじをください。', 'Hãy trả lời sớm hết mức có thể.', 1),
(444, 321, '本日に限り、入場料が半額になります。', 'ほんじつにかぎり、にゅうじょうりょうがはんがくになります。', 'Chỉ hôm nay, phí vào cửa giảm một nửa.', 1),
(445, 322, '雨が降らない限り、試合は予定通り行われます。', 'あめがふらないかぎり、しあいはよていどおりおこなわれます。', 'Chừng nào trời không mưa, trận đấu sẽ diễn ra theo lịch.', 1),
(446, 323, '今回の件に限っては、彼に責任はないと思う。', 'こんかいのけんにかぎっては、かれにせきにんはないとおもう。', 'Riêng vụ lần này, tôi nghĩ anh ấy không có trách nhiệm.', 1),
(447, 324, '忙しい日に限って、急な客が来る。', 'いそがしいひにかぎって、きゅうなきゃくがくる。', 'Đúng những ngày bận thì khách đột xuất lại đến.', 1),
(448, 325, '彼に限って、そんな失礼なことはしないはずだ。', 'かれにかぎって、そんなしつれいなことはしないはずだ。', 'Riêng anh ấy thì chắc chắn không làm chuyện thất lễ như vậy.', 1),
(449, 326, '子どもに限って、この薬は使わないでください。', 'こどもにかぎって、このくすりはつかわないでください。', 'Riêng trẻ em thì xin đừng dùng thuốc này.', 1),
(450, 327, '休日に限らず、平日もこの店は混んでいる。', 'きゅうじつにかぎらず、へいじつもこのみせはこんでいる。', 'Không chỉ cuối tuần mà ngày thường cửa hàng này cũng đông.', 1),
(451, 328, '彼は英語のみならず、中国語も話せる。', 'かれはえいごのみならず、ちゅうごくごもはなせる。', 'Anh ấy không chỉ nói được tiếng Anh mà còn nói được tiếng Trung.', 1),
(452, 329, '彼は遅刻したばかりか、宿題も忘れた。', 'かれはちこくしたばかりか、しゅくだいもわすれた。', 'Anh ấy không chỉ đi muộn mà còn quên bài tập.', 1),
(453, 330, 'この商品は若者はもとより、高齢者にも人気がある。', 'このしょうひんはわかものはもとより、こうれいしゃにもにんきがある。', 'Sản phẩm này được yêu thích không chỉ bởi giới trẻ mà cả người cao tuổi.', 1),
(454, 331, 'この部屋は広い上に、駅からも近い。', 'このへやはひろいうえに、えきからもちかい。', 'Căn phòng này rộng, hơn nữa còn gần ga.', 1),
(455, 332, 'この問題に関して、詳しい説明をお願いします。', 'このもんだいにかんして、くわしいせつめいをおねがいします。', 'Về vấn đề này, xin hãy giải thích chi tiết.', 1),
(456, 333, '新しい計画をめぐって、意見が分かれている。', 'あたらしいけいかくをめぐって、いけんがわかれている。', 'Các ý kiến đang chia rẽ xoay quanh kế hoạch mới.', 1),
(457, 334, '料理にかけては、母にかなう人はいない。', 'りょうりにかけては、ははにかなうひとはいない。', 'Riêng về nấu ăn thì không ai bằng mẹ tôi.', 1),
(458, 335, 'お客様に対して、失礼な言い方をしてはいけません。', 'おきゃくさまにたいして、しつれいないいかたをしてはいけません。', 'Không được nói năng thất lễ với khách hàng.', 1),
(459, 336, '皆の期待にこたえて、彼は優勝した。', 'みんなのきたいにこたえて、かれはゆうしょうした。', 'Đáp lại kỳ vọng của mọi người, anh ấy đã vô địch.', 1),
(460, 337, '実話をもとにして、この映画は作られた。', 'じつわをもとにして、このえいがはつくられた。', 'Bộ phim này được làm dựa trên câu chuyện có thật.', 1),
(461, 338, 'データに基づいて、計画を立て直した。', 'データにもとづいて、けいかくをたてなおした。', 'Chúng tôi lập lại kế hoạch dựa trên dữ liệu.', 1),
(462, 339, '会社の方針に沿って、予算を決めます。', 'かいしゃのほうしんにそって、よさんをきめます。', 'Chúng tôi quyết định ngân sách theo phương châm của công ty.', 1),
(463, 340, '先生の指導のもとで、研究を進めた。', 'せんせいのしどうのもとで、けんきゅうをすすめた。', 'Tôi tiến hành nghiên cứu dưới sự hướng dẫn của thầy.', 1),
(464, 341, 'この雑誌は日本語を学ぶ外国人向けだ。', 'このざっしはにほんごをまなぶがいこくじんむけだ。', 'Tạp chí này dành cho người nước ngoài học tiếng Nhật.', 1),
(465, 342, '年を取るにつれて、健康の大切さが分かる。', 'としをとるにつれて、けんこうのたいせつさがわかる。', 'Càng lớn tuổi, tôi càng hiểu tầm quan trọng của sức khỏe.', 1),
(466, 343, '人口の増加に伴って、住宅も必要になった。', 'じんこうのぞうかにともなって、じゅうたくもひつようになった。', 'Dân số tăng kéo theo nhu cầu nhà ở.', 1),
(467, 344, '結果は君の努力次第だ。', 'けっかはきみのどりょくしだいだ。', 'Kết quả tùy thuộc vào nỗ lực của bạn.', 1),
(468, 345, '経験に応じて、給料が決まります。', 'けいけんにおうじて、きゅうりょうがきまります。', 'Lương được quyết định tùy theo kinh nghiệm.', 1),
(469, 346, 'この歌を聞くにつけて、故郷を思い出す。', 'このうたをきくにつけて、ふるさとをおもいだす。', 'Mỗi lần nghe bài hát này, tôi lại nhớ quê.', 1),
(470, 347, '引っ越しの準備やら手続きやらで忙しい。', 'ひっこしのじゅんびやらてつづきやらでいそがしい。', 'Tôi bận nào là chuẩn bị chuyển nhà, nào là làm thủ tục.', 1),
(471, 348, '彼の態度は親切というか、おせっかいというか、少し複雑だ。', 'かれのたいどはしんせつというか、おせっかいというか、すこしふくざつだ。', 'Thái độ của anh ấy có thể nói là tử tế, cũng có thể nói là hơi can thiệp.', 1),
(472, 349, '行くにしても行かないにしても、早く返事をください。', 'いくにしてもいかないにしても、はやくへんじをください。', 'Dù đi hay không đi, hãy trả lời sớm.', 1),
(473, 350, 'この店では、寿司や天ぷらといった日本料理が食べられる。', 'このみせでは、すしやてんぷらといったにほんりょうりがたべられる。', 'Ở cửa hàng này có thể ăn các món Nhật như sushi hay tempura.', 1),
(474, 351, 'このカードは年齢を問わず、誰でも使える。', 'このカードはねんれいをとわず、だれでもつかえる。', 'Thẻ này ai cũng dùng được, không kể tuổi tác.', 1),
(475, 352, '天気にかかわらず、試合は行われます。', 'てんきにかかわらず、しあいはおこなわれます。', 'Trận đấu sẽ diễn ra bất kể thời tiết.', 1),
(476, 353, '人目もかまわず、彼女は大声で泣いた。', 'ひとめもかまわず、かのじょはおおごえでないた。', 'Cô ấy khóc lớn mà chẳng để ý ánh mắt người khác.', 1),
(477, 354, '値段はともかく、品質はとても良い。', 'ねだんはともかく、ひんしつはとてもよい。', 'Khoan nói đến giá, chất lượng thì rất tốt.', 1),
(478, 355, '冗談はさておき、本題に入りましょう。', 'じょうだんはさておき、ほんだいにはいりましょう。', 'Gác chuyện đùa sang một bên, chúng ta vào chủ đề chính.', 1),
(479, 356, 'こんな難しい問題が簡単に解けるわけがない。', 'こんなむずかしいもんだいがかんたんにとけるわけがない。', 'Một bài khó thế này không thể giải dễ dàng được.', 1),
(480, 357, '仕事が忙しくて、旅行どころではない。', 'しごとがいそがしくて、りょこうどころではない。', 'Công việc bận đến mức không còn tâm trí đi du lịch.', 1),
(481, 358, '彼は謝るどころか、怒り出した。', 'かれはあやまるどころか、おこりだした。', 'Anh ấy không những không xin lỗi mà còn nổi giận.', 1),
(482, 359, '二度と彼に頼むものか。', 'にどとかれにたのむものか。', 'Tôi sẽ không bao giờ nhờ anh ấy nữa.', 1),
(483, 360, '日本語が嫌いなわけではないが、漢字は苦手だ。', 'にほんごがきらいなわけではないが、かんじはにがてだ。', 'Không phải tôi ghét tiếng Nhật, nhưng tôi kém kanji.', 1),
(484, 361, '高ければよいというものではない。', 'たかければよいというものではない。', 'Không phải cứ đắt là tốt.', 1),
(485, 362, '友情とは、困った時に助け合うことだ。', 'ゆうじょうとは、こまったときにたすけあうことだ。', 'Tình bạn là giúp đỡ nhau lúc khó khăn.', 1),
(486, 363, '日本の食べ物といえば、寿司を思い出す。', 'にほんのたべものといえば、すしをおもいだす。', 'Nói đến đồ ăn Nhật thì tôi nhớ đến sushi.', 1),
(487, 364, '彼は優しいといえば優しいが、少し頼りない。', 'かれはやさしいといえばやさしいが、すこしたよりない。', 'Nói là anh ấy hiền thì đúng là hiền, nhưng hơi thiếu tin cậy.', 1),
(488, 365, '夏というと、海を思い出します。', 'なつというと、うみをおもいだします。', 'Nhắc đến mùa hè là tôi nhớ đến biển.', 1),
(489, 366, '仕事のこととなると、彼はとても真剣になる。', 'しごとのこととなると、かれはとてもしんけんになる。', 'Hễ nói đến công việc là anh ấy rất nghiêm túc.', 1),
(490, 367, '試験前の忙しさといったら、寝る時間もないほどだ。', 'しけんまえのいそがしさといったら、ねるじかんもないほどだ。', 'Nói đến sự bận rộn trước kỳ thi thì đến mức không có thời gian ngủ.', 1),
(491, 368, '雨にもかかわらず、大勢の人が集まった。', 'あめにもかかわらず、おおぜいのひとがあつまった。', 'Mặc dù trời mưa, rất nhiều người đã tụ tập.', 1),
(492, 369, '新しいパソコンを買ったものの、まだ使い方が分からない。', 'あたらしいパソコンをかったものの、まだつかいかたがわからない。', 'Tôi đã mua máy tính mới nhưng vẫn chưa biết cách dùng.', 1),
(493, 370, '春とはいうものの、まだ寒い日が続いている。', 'はるとはいうものの、まださむいひがつづいている。', 'Tuy nói là mùa xuân nhưng những ngày lạnh vẫn tiếp tục.', 1),
(494, 371, '彼は子どもながら、しっかりしている。', 'かれはこどもながら、しっかりしている。', 'Dù là trẻ con nhưng cậu ấy rất chững chạc.', 1),
(495, 372, '悪いと知りつつも、同じ失敗を繰り返した。', 'わるいとしりつつも、おなじしっぱいをくりかえした。', 'Dù biết là không tốt, tôi vẫn lặp lại lỗi cũ.', 1),
(496, 373, '料理ができるといっても、簡単なものだけです。', 'りょうりができるといっても、かんたんなものだけです。', 'Nói là biết nấu ăn chứ tôi chỉ làm được món đơn giản.', 1),
(497, 374, '日本に住んでいるからといって、日本語が完璧なわけではない。', 'にほんにすんでいるからといって、にほんごがかんぺきなわけではない。', 'Không phải cứ sống ở Nhật là tiếng Nhật hoàn hảo.', 1),
(498, 375, 'もし明日雨だとしたら、試合は中止になる。', 'もしあしたあめだとしたら、しあいはちゅうしになる。', 'Nếu ngày mai mưa thì trận đấu sẽ bị hủy.', 1),
(499, 376, '海外で働くとなると、家族とも相談が必要だ。', 'かいがいではたらくとなると、かぞくともそうだんがひつようだ。', 'Nếu chuyện trở thành đi làm ở nước ngoài thì cần bàn với gia đình.', 1),
(500, 377, 'できるものなら、もう一度あの日に戻りたい。', 'できるものなら、もういちどあのひにもどりたい。', 'Nếu có thể, tôi muốn quay lại ngày hôm đó một lần nữa.', 1),
(501, 378, 'そんなことを言おうものなら、みんなに反対される。', 'そんなことをいおうものなら、みんなにはんたいされる。', 'Nếu lỡ nói chuyện đó thì sẽ bị mọi người phản đối.', 1),
(502, 379, '実際に会ってみないことには、彼の気持ちは分からない。', 'じっさいにあってみないことには、かれのきもちはわからない。', 'Nếu chưa gặp trực tiếp thì không thể hiểu cảm xúc của anh ấy.', 1),
(503, 380, '先生の助けを抜きにしては、この研究は完成しなかった。', 'せんせいのたすけをぬきにしては、このけんきゅうはかんせいしなかった。', 'Nếu không có sự giúp đỡ của thầy, nghiên cứu này đã không hoàn thành.', 1),
(504, 381, '国によって、習慣が違います。', 'くにによって、しゅうかんがちがいます。', 'Tập quán khác nhau tùy từng nước.', 1),
(505, 382, '昨日は熱があったものだから、会社を休みました。', 'きのうはねつがあったものだから、かいしゃをやすみました。', 'Vì hôm qua tôi bị sốt nên đã nghỉ làm.', 1),
(506, 383, 'だって忙しかったんだもの、連絡できなかったよ。', 'だっていそがしかったんだもの、れんらくできなかったよ。', 'Vì tôi bận quá nên đã không thể liên lạc.', 1),
(507, 384, '先生のおかげで、試験に合格できました。', 'せんせいのおかげで、しけんにごうかくできました。', 'Nhờ thầy, tôi đã đỗ kỳ thi.', 1),
(508, 385, '寝不足のせいで、今日は集中できない。', 'ねぶそくのせいで、きょうはしゅうちゅうできない。', 'Do thiếu ngủ nên hôm nay tôi không thể tập trung.', 1),
(509, 386, '心配のあまり、眠れなかった。', 'しんぱいのあまり、ねむれなかった。', 'Vì quá lo lắng nên tôi không ngủ được.', 1),
(510, 387, '工事中につき、この道は通れません。', 'こうじちゅうにつき、このみちはとおれません。', 'Do đang thi công nên không thể đi qua đường này.', 1),
(511, 388, '雨もやんだことだし、そろそろ帰りましょう。', 'あめもやんだことだし、そろそろかえりましょう。', 'Mưa cũng tạnh rồi, chúng ta về thôi.', 1),
(512, 389, '真面目な彼のことだから、約束は守るだろう。', 'まじめなかれのことだから、やくそくはまもるだろう。', 'Vì là người nghiêm túc như anh ấy nên chắc sẽ giữ lời hứa.', 1),
(513, 390, '期待していただけに、失敗した時はとても残念だった。', 'きたいしていただけに、しっぱいしたときはとてもざんねんだった。', 'Chính vì đã kỳ vọng nên khi thất bại tôi rất tiếc.', 1),
(514, 391, '一言余計なことを言ったばかりに、友人を怒らせてしまった。', 'ひとことよけいなことをいったばかりに、ゆうじんをおこらせてしまった。', 'Chỉ vì nói thừa một câu mà tôi làm bạn nổi giận.', 1),
(515, 392, '約束したからには、最後までやります。', 'やくそくしたからには、さいごまでやります。', 'Một khi đã hứa thì tôi sẽ làm đến cùng.', 1),
(516, 393, '彼の行動は理解しがたい。', 'かれのこうどうはりかいしがたい。', 'Hành động của anh ấy thật khó hiểu.', 1),
(517, 394, '大事な会議なので、休むわけにはいかない。', 'だいじなかいぎなので、やすむわけにはいかない。', 'Vì là cuộc họp quan trọng nên tôi không thể nghỉ.', 1),
(518, 395, '親に心配をかけるわけにもいかない。', 'おやにしんぱいをかけるわけにもいかない。', 'Tôi cũng không thể để cha mẹ lo lắng.', 1),
(519, 396, 'そのご依頼にはお答えしかねます。', 'そのごいらいにはおこたえしかねます。', 'Chúng tôi khó có thể đáp ứng yêu cầu đó.', 1),
(520, 397, '住所が分からないので、連絡しようがない。', 'じゅうしょがわからないので、れんらくしようがない。', 'Vì không biết địa chỉ nên không có cách nào liên lạc.', 1),
(521, 398, '誰にでも起こり得る問題です。', 'だれにでもおこりうるもんだいです。', 'Đây là vấn đề có thể xảy ra với bất kỳ ai.', 1),
(522, 399, '彼は若いわりには、考え方がしっかりしている。', 'かれはわかいわりには、かんがえかたがしっかりしている。', 'So với tuổi còn trẻ, cách nghĩ của anh ấy rất chín chắn.', 1),
(523, 400, '初めてにしては、上手にできました。', 'はじめてにしては、じょうずにできました。', 'Tuy là lần đầu nhưng bạn làm rất tốt.', 1),
(524, 401, '高いだけのことはあって、このカメラは性能がいい。', 'たかいだけのことはあって、このカメラはせいのうがいい。', 'Quả đúng là đắt, chiếc máy ảnh này có hiệu năng tốt.', 1),
(525, 402, '教師として、学生の成長を支えたい。', 'きょうしとして、がくせいのせいちょうをささえたい。', 'Với tư cách giáo viên, tôi muốn hỗ trợ sự trưởng thành của học sinh.', 1),
(526, 403, '私にとって、家族は一番大切です。', 'わたしにとって、かぞくはいちばんたいせつです。', 'Đối với tôi, gia đình là quan trọng nhất.', 1),
(527, 404, '親にしたら、子どもの安全が一番心配だ。', 'おやにしたら、こどものあんぜんがいちばんしんぱいだ。', 'Đối với cha mẹ, an toàn của con là điều lo nhất.', 1),
(528, 405, '先生に相談したところ、すぐ返事をくれた。', 'せんせいにそうだんしたところ、すぐへんじをくれた。', 'Khi tôi hỏi thầy thì thầy trả lời ngay.', 1),
(529, 406, '彼は出て行ったきり、帰ってこない。', 'かれはでていったきり、かえってこない。', 'Anh ấy ra đi rồi không quay lại nữa.', 1),
(530, 407, '長く迷ったあげく、留学することにした。', 'ながくまよったあげく、りゅうがくすることにした。', 'Sau khi phân vân lâu, tôi quyết định đi du học.', 1),
(531, 408, '何度も話し合った末に、計画を変更した。', 'なんどもはなしあったすえに、けいかくをへんこうした。', 'Sau nhiều lần bàn bạc, chúng tôi đã đổi kế hoạch.', 1),
(532, 409, 'もう少しで電車に乗り遅れるところだった。', 'もうすこしででんしゃにのりおくれるところだった。', 'Chút nữa là tôi lỡ tàu.', 1),
(533, 410, '忙しくて、友達に会えずじまいだった。', 'いそがしくて、ともだちにあえずじまいだった。', 'Vì bận nên cuối cùng tôi vẫn không gặp được bạn.', 1),
(534, 411, 'このくらいの荷物なら、一人で運べます。', 'このくらいのにもつなら、ひとりではこべます。', 'Hành lý cỡ này thì một mình tôi mang được.', 1),
(535, 412, '忙しくて、昼ご飯など食べる時間がなかった。', 'いそがしくて、ひるごはんなどたべるじかんがなかった。', 'Bận đến mức không có thời gian ăn trưa gì cả.', 1),
(536, 413, '失敗なんか気にしないで、もう一度やってみよう。', 'しっぱいなんかきにしないで、もういちどやってみよう。', 'Đừng bận tâm thất bại gì cả, hãy thử lại lần nữa.', 1),
(537, 414, '一人で全部やるなんて、無理です。', 'ひとりでぜんぶやるなんて、むりです。', 'Tự làm hết một mình thì không thể được.', 1),
(538, 415, '借金までして、そんな高い物を買う必要はない。', 'しゃっきんまでして、そんなたかいものをかうひつようはない。', 'Không cần đến mức vay nợ để mua thứ đắt như vậy.', 1),
(539, 416, '彼は一度として約束を破ったことがない。', 'かれはいちどとしてやくそくをやぶったことがない。', 'Anh ấy chưa từng thất hứa dù chỉ một lần.', 1),
(540, 417, '忙しくて、食事をする時間さえなかった。', 'いそがしくて、しょくじをするじかんさえなかった。', 'Tôi bận đến mức không có cả thời gian ăn.', 1),
(541, 418, '名前さえ分かれば、すぐに調べられます。', 'なまえさえわかれば、すぐにしらべられます。', 'Chỉ cần biết tên là có thể tra ngay.', 1),
(542, 419, '子どもでも分かる説明にしてください。', 'こどもでもわかるせつめいにしてください。', 'Hãy giải thích sao cho ngay cả trẻ con cũng hiểu.', 1),
(543, 420, '窓がぬれている。夜中に雨が降ったとみえる。', 'まどがぬれている。よなかにあめがふったとみえる。', 'Cửa sổ ướt. Có vẻ đêm qua trời đã mưa.', 1),
(544, 421, 'このままでは、大きな事故が起こりかねない。', 'このままでは、おおきなじこがおこりかねない。', 'Cứ thế này có thể xảy ra tai nạn lớn.', 1),
(545, 422, '明日は大雨になるおそれがある。', 'あしたはおおあめになるおそれがある。', 'Ngày mai có nguy cơ mưa lớn.', 1),
(546, 423, '彼はもう二度と来るまい。', 'かれはもうにどとくるまい。', 'Chắc anh ấy sẽ không đến lần nào nữa.', 1),
(547, 424, 'これは重要な問題ではあるまいか。', 'これはじゅうようなもんだいではあるまいか。', 'Chẳng phải đây là vấn đề quan trọng hay sao.', 1),
(548, 425, 'あの人は犯人に違いない。', 'あのひとははんにんにちがいない。', 'Người đó chắc chắn là thủ phạm.', 1),
(549, 426, '彼なら試験に合格するにきまっている。', 'かれならしけんにごうかくするにきまっている。', 'Nếu là anh ấy thì nhất định sẽ đỗ kỳ thi.', 1),
(550, 427, '人は誰でも失敗するものだ。', 'ひとはだれでもしっぱいするものだ。', 'Con người ai cũng có lúc thất bại.', 1),
(551, 428, '努力せずに成功したいなんて、わがままというものだ。', 'どりょくせずにせいこうしたいなんて、わがままというものだ。', 'Muốn thành công mà không nỗ lực thì đúng là ích kỷ.', 1),
(552, 429, 'これは個人的な意見にすぎません。', 'これはこじんてきないけんにすぎません。', 'Đây chẳng qua chỉ là ý kiến cá nhân.', 1),
(553, 430, '成功の理由は努力にほかならない。', 'せいこうのりゆうはどりょくにほかならない。', 'Lý do thành công không gì khác ngoài nỗ lực.', 1),
(554, 431, '準備は早いに越したことはない。', 'じゅんびははやいにこしたことはない。', 'Chuẩn bị càng sớm càng tốt.', 1),
(555, 432, '電車が止まったので、歩くしかない。', 'でんしゃがとまったので、あるくしかない。', 'Vì tàu dừng nên chỉ còn cách đi bộ.', 1),
(556, 433, '約束は守るべきだ。', 'やくそくはまもるべきだ。', 'Nên giữ lời hứa.', 1),
(557, 434, '環境を守るために、今できることを考えようではないか。', 'かんきょうをまもるために、いまできることをかんがえようではないか。', 'Chúng ta hãy cùng nghĩ xem bây giờ có thể làm gì để bảo vệ môi trường.', 1),
(558, 435, '健康になりたいなら、毎日運動することだ。', 'けんこうになりたいなら、まいにちうんどうすることだ。', 'Nếu muốn khỏe mạnh thì nên vận động mỗi ngày.', 1),
(559, 436, '年上の人には丁寧に話すものだ。', 'としうえのひとにはていねいにはなすものだ。', 'Với người lớn tuổi thì nên nói chuyện lịch sự.', 1),
(560, 437, '人の悪口を言うものではない。', 'ひとのわるぐちをいうものではない。', 'Không nên nói xấu người khác.', 1),
(561, 438, 'そんなに心配することはない。', 'そんなにしんぱいすることはない。', 'Không cần lo lắng đến thế.', 1),
(562, 439, 'あんな店には二度と行くものか。', 'あんなみせにはにどといくものか。', 'Tôi nhất định không đến cửa hàng như thế lần nữa.', 1),
(563, 440, 'この映画は面白くてしかたがない。', 'このえいがはおもしろくてしかたがない。', 'Bộ phim này thú vị không chịu nổi.', 1),
(564, 441, '試験の結果が心配でたまらない。', 'しけんのけっかがしんぱいでたまらない。', 'Tôi lo kết quả kỳ thi không chịu nổi.', 1),
(565, 442, '国の家族が思い出されてならない。', 'くにのかぞくがおもいだされてならない。', 'Tôi không thể ngừng nhớ gia đình ở quê.', 1),
(566, 443, '明日試験だから、遊んではいられない。', 'あしたしけんだから、あそんではいられない。', 'Vì mai thi nên không thể cứ chơi được.', 1),
(567, 444, '雨が強くなったので、予定を変更せざるを得ない。', 'あめがつよくなったので、よていをへんこうせざるをえない。', 'Vì mưa to hơn nên chúng tôi buộc phải đổi kế hoạch.', 1),
(568, 445, 'いつか富士山に登りたいものだ。', 'いつかふじさんにのぼりたいものだ。', 'Tôi thật sự muốn một ngày nào đó leo núi Phú Sĩ.', 1),
(569, 446, '子どもの頃、よくこの川で泳いだものだ。', 'こどものころ、よくこのかわでおよいだものだ。', 'Hồi nhỏ tôi thường bơi ở con sông này.', 1),
(570, 447, '時間が過ぎるのは早いものだ。', 'じかんがすぎるのははやいものだ。', 'Thời gian trôi qua thật nhanh biết bao.', 1),
(571, 448, 'どうしたら彼に気持ちを伝えられるものだろうか。', 'どうしたらかれにきもちをつたえられるものだろうか。', 'Không biết làm sao để truyền đạt cảm xúc với anh ấy.', 1),
(572, 449, '彼の話には人を引きつけるものがある。', 'かれのはなしにはひとをひきつけるものがある。', 'Câu chuyện của anh ấy có sức hút người nghe.', 1),
(573, 450, '一人でここまで来たとは、立派なことだ。', 'ひとりでここまできたとは、りっぱなことだ。', 'Một mình đi được đến đây thật là đáng nể.', 1),
(574, 451, '合格の知らせを聞いて、どんなにうれしかったことか。', 'ごうかくのしらせをきいて、どんなにうれしかったことか。', 'Khi nghe tin đỗ, tôi đã vui biết bao.', 1)
ON DUPLICATE KEY UPDATE
    grammar_lesson_id = VALUES(grammar_lesson_id),
    japanese_text = VALUES(japanese_text),
    reading = VALUES(reading),
    meaning_vi = VALUES(meaning_vi),
    display_order = VALUES(display_order);
